// Experimental full-work oracle. No effect on normal serving without explicit research configuration.
#pragma once
#include "strata/research/q4_tape.hpp"
#include <atomic>
#include <cmath>
#include <condition_variable>
#include <functional>
#include <mutex>
#include <thread>
#include <limits>
namespace strata::research {
struct OracleLayer { uint64_t event,begin,plan_end,cpu_end; int32_t layer,n; int32_t ids[40],slots[40],path[40]; };
struct OracleEvent { uint64_t issue_ns,stage_begin,stage_end,copy_begin,copy_end,publish_ns; int32_t trigger,target,published_at,layer,incoming,victim,slot,oldslot,status; uint64_t bytes,uses,victim_uses; };
struct NativeCopy { uint64_t issue_ns,publish_ns,bytes;int32_t window,layer,incoming,victim,slot; };
struct Q4Oracle {
 static constexpr int ne=512,nl=48,classes=3; static constexpr uint64_t sizes[3]={3072000,3584000,3993600};
 bool configured=false,active=false,requested=false,direct=false,check_bytes=false,tracked=false;int horizon=0,strategy=0;
 int32_t* res=nullptr;const float* heat=nullptr;std::vector<uint64_t> blobs;std::array<int32_t*,2> dres{};
 std::function<const uint8_t*(int,int)> source;std::function<void*(int,int)> slot;
 std::vector<std::vector<std::pair<int,int>>> future;std::vector<OracleEvent> events;std::vector<OracleLayer> layers;std::vector<NativeCopy> natives;std::vector<int> incoming_event,victim_event;std::array<unsigned,48*512> candidate_seen{};unsigned seen_generation=0;
 int current=-1;uint64_t planner_ns=0,publication_ns=0,drain_ns=0,restore_ns=0,setup_ns=0,ready_entries=0,late_entries=0,redundant=0,protected_reject=0,opportunities=0;
 double event_us=650,copy_us=750;uint64_t last_boundary=0;int last_event=-1;std::array<std::array<int,3>,2> spare{},donor_layer{},donor_expert{};
 struct Worker {std::mutex mu;std::condition_variable cv;std::thread thread;std::atomic<int> state{0};bool quit=false;int dev=-1,cls=-1,index=-1,layer=-1,expert=-1,victim=-1,destination=-1;size_t n=0;const uint8_t* src=nullptr;uint8_t* staging=nullptr;int32_t* metadata=nullptr;cudaStream_t stream=nullptr;cudaEvent_t done=nullptr;int readbacks=0;};
 std::array<std::array<Worker,3>,2> workers;
 static uint64_t ns(){return Q4Tape::ns();}static void require(bool x,const char* why){Q4Tape::require(x,why);}static void ck(cudaError_t e){require(e==cudaSuccess,cudaGetErrorString(e));}
 int cls(int l)const{auto it=std::find(sizes,sizes+3,blobs[l]);require(it!=sizes+3,"unknown expert size class");return int(it-sizes);}
 Q4Oracle(){const char* p=std::getenv("STRATA_Q4_ORACLE_MODE");requested=p&&(std::string(p)=="full"||std::string(p)=="short");if(requested&&std::string(p)=="short"){p=std::getenv("STRATA_Q4_ORACLE_HORIZON");require(p,"short horizon missing");horizon=std::atoi(p);require(horizon==1||horizon==4||horizon==16||horizon==64,"unsupported horizon");}p=std::getenv("STRATA_Q4_ORACLE_STRATEGY");strategy=p&&std::string(p)=="reuse";p=std::getenv("STRATA_Q4_ORACLE_DIRECT");direct=p&&p[0]=='1';p=std::getenv("STRATA_Q4_ORACLE_CHECK");check_bytes=p&&p[0]=='1';for(auto& a:spare)a.fill(-1);}
 void configure(){const char* p=std::getenv("STRATA_Q4_ORACLE_SUBSTRATE");if(!p||p[0]!='1')return;int old;ck(cudaGetDevice(&old));for(int d=0;d<2;++d)for(int c=0;c<3;++c){if(d==1&&c==2)continue;ck(cudaSetDevice(d));auto& w=workers[d][c];w.dev=d;w.cls=c;ck(cudaHostAlloc(&w.staging,sizes[c],cudaHostAllocDefault));ck(cudaHostAlloc(&w.metadata,8,cudaHostAllocDefault));ck(cudaStreamCreateWithFlags(&w.stream,cudaStreamNonBlocking));ck(cudaEventCreateWithFlags(&w.done,cudaEventDisableTiming));w.thread=std::thread([this,d,c]{worker(d,c);});}ck(cudaSetDevice(old));configured=true;}
 static void publish_state(Worker& w,int s){std::lock_guard<std::mutex> lk(w.mu);w.state.store(s,std::memory_order_release);w.cv.notify_all();}
 void worker(int d,int c){auto& w=workers[d][c];try{ck(cudaSetDevice(d));while(true){int command;{std::unique_lock<std::mutex> lk(w.mu);w.cv.wait(lk,[&]{int s=w.state.load();return w.quit||s==1||s==4||s==6;});if(w.quit)break;command=w.state.load();if(command==1)w.state.store(2,std::memory_order_release);}if(command==1){auto& e=events[w.index];e.stage_begin=ns();if(!direct)std::memcpy(w.staging,w.src,w.n);e.stage_end=ns();const char* delay=std::getenv("STRATA_Q4_ORACLE_DELAY_US");if(delay)std::this_thread::sleep_for(std::chrono::microseconds(std::atoi(delay)));e.copy_begin=ns();ck(cudaMemcpyAsync(slot(d,w.destination),direct?w.src:w.staging,w.n,cudaMemcpyHostToDevice,w.stream));ck(cudaEventRecord(w.done,w.stream));ck(cudaEventSynchronize(w.done));e.copy_end=ns();if(check_bytes&&w.readbacks<2){std::vector<uint8_t> bytes(w.n);ck(cudaMemcpy(bytes.data(),slot(d,w.destination),w.n,cudaMemcpyDeviceToHost));require(std::memcmp(bytes.data(),w.src,w.n)==0,"oracle copied weight bytes mismatch");++w.readbacks;}publish_state(w,3);}else if(command==4){w.metadata[0]=-1;w.metadata[1]=w.destination;ck(cudaMemcpyAsync(dres[d]+w.layer*512+w.victim,w.metadata,4,cudaMemcpyHostToDevice,w.stream));ck(cudaMemcpyAsync(dres[d]+w.layer*512+w.expert,w.metadata+1,4,cudaMemcpyHostToDevice,w.stream));ck(cudaEventRecord(w.done,w.stream));ck(cudaEventSynchronize(w.done));publish_state(w,5);}else if(command==6)publish_state(w,0);}}catch(const std::exception& e){std::fprintf(stderr,"Q4_ORACLE_WORKER_FAIL device%d class%d %s\n",d,c,e.what());publish_state(w,7);}}
 void runtime(int32_t* r,const float* u,std::vector<uint64_t> b,std::array<int32_t*,2> dr,std::function<const uint8_t*(int,int)> src,std::function<void*(int,int)> sl){res=r;heat=u;blobs=std::move(b);dres=dr;source=std::move(src);slot=std::move(sl);prepare();}
 void prepare(){if(!configured||!q4_tape.replaying)return;uint64_t t=ns();future.resize(48*512);for(size_t wi=0;wi<q4_tape.windows.size();++wi){const auto& w=q4_tape.windows[wi];for(int l=0;l<48;++l){int count[512]={};for(int j=0;j<w.T*10;++j)++count[w.routes.ids[l][j]];for(int e=0;e<512;++e)if(count[e])future[l*512+e].emplace_back((int)wi*48+l,count[e]);}}setup_ns=ns()-t;std::fprintf(stderr,"Q4_ORACLE_SETUP future_index_ms=%.3f horizon_main_routed_invocations=%s classes=3072000,3584000,3993600 scope_layers=48\n",setup_ns/1e6,horizon?std::to_string(horizon).c_str():"full");}
 int next(int l,int e,int at)const{const auto& v=future[l*512+e];auto i=std::lower_bound(v.begin(),v.end(),std::make_pair(at,-1));if(i==v.end()||(horizon&&i->first>at+horizon))return -1;return i->first;}
 int count(int l,int e,int at,int until)const{if(horizon)until=std::min(until,at+horizon);const auto& v=future[l*512+e];auto i=std::lower_bound(v.begin(),v.end(),std::make_pair(at,-1));int n=0;for(;i!=v.end()&&i->first<=until;++i)n+=i->second;return n;}
 bool protected_now(int l,int e)const{int at=std::max(0,current);int event=(at/48)*48+l;if(horizon&&event>at+horizon)return false;const auto& w=q4_tape.current;for(int j=0;j<w.T*10;++j)if(w.routes.ids[l][j]==e)return true;return false;}
 int victim(int l,int incoming,int at)const{int best=-1;double score=-1e100;for(int e=0;e<512;++e){if(res[l*512+e]<0||e==incoming||protected_now(l,e))continue;int nx=next(l,e,at);double value;if(!horizon)value=nx<0?1e12:(nx-at);else value=nx<0?double(horizon+1)-std::log1p(std::max(0.f,heat[l*512+e])):double(nx-at);if(value>score){score=value;best=e;}}return best;}
 void begin(){if(!configured||!q4_tape.active)return;tracked=true;active=requested;require(!active||q4_tape.replaying,"oracle requires fixed-work replay");events.clear();layers.clear();natives.clear();events.reserve(q4_tape.header.output_budget*240);layers.reserve(q4_tape.header.output_budget*48);natives.reserve(q4_tape.header.output_budget*96);incoming_event.assign(48*512,-1);victim_event.assign(48*512,-1);planner_ns=publication_ns=drain_ns=restore_ns=ready_entries=late_entries=redundant=protected_reject=opportunities=0;last_boundary=0;last_event=-1;current=-1;
  if(!active)return;uint64_t t=ns();for(int d=0;d<2;++d)for(int c=0;c<3;++c){if(d==1&&c==2)continue;int pick=-1;double value=-1e100;for(int l=d*24;l<(d+1)*24;++l)if(cls(l)==c)for(int e=0;e<512;++e){if(res[l*512+e]<0)continue;const auto& first=q4_tape.windows.front();bool protected_first=false;for(int j=0;j<first.T*10;++j)protected_first|=first.routes.ids[l][j]==e;if(protected_first)continue;int nx=next(l,e,0);double val=!horizon?(nx<0?1e12:nx):(nx<0?double(horizon+1)-std::log1p(std::max(0.f,heat[l*512+e])):nx);if(val>value){value=val;pick=l*512+e;}}require(pick>=0,"no same-class reserve");donor_layer[d][c]=pick/512;donor_expert[d][c]=pick%512;spare[d][c]=res[pick];res[pick]=-1;int old;ck(cudaGetDevice(&old));ck(cudaSetDevice(d));ck(cudaMemcpy(dres[d]+pick,res+pick,4,cudaMemcpyHostToDevice));ck(cudaSetDevice(old));std::fprintf(stderr,"Q4_ORACLE_RESERVE device=%d class=%d bytes=%llu slot=%d layer=%d expert=%d active_minus1\n",d,c,(unsigned long long)sizes[c],spare[d][c],pick/512,pick%512);}planner_ns+=ns()-t;
 }
 void retire(Worker& w,int status){uint64_t t=ns();std::unique_lock<std::mutex> lk(w.mu);require(w.cv.wait_for(lk,std::chrono::seconds(10),[&]{int s=w.state.load();return s==0||s==3||s==7;}),"oracle retirement timeout");require(w.state.load()!=7,"oracle worker failure");if(w.state.load()==3){events[w.index].status=status;w.state.store(6,std::memory_order_release);w.cv.notify_all();require(w.cv.wait_for(lk,std::chrono::seconds(5),[&]{return w.state.load()==0||w.state.load()==7;}),"oracle retirement ack");require(w.state.load()==0,"oracle retirement failure");}drain_ns+=ns()-t;}
 void publish(Worker& w){if(w.state.load(std::memory_order_acquire)!=3)return;auto& e=events[w.index];if(res[w.layer*512+w.expert]>=0){++redundant;retire(w,2);return;}int v=victim(w.layer,w.expert,current);if(v<0){++protected_reject;return;}int old=res[w.layer*512+v];uint64_t t=ns();{std::unique_lock<std::mutex> lk(w.mu);w.victim=v;w.state.store(4,std::memory_order_release);w.cv.notify_all();require(w.cv.wait_for(lk,std::chrono::seconds(5),[&]{return w.state.load()==5||w.state.load()==7;}),"oracle publication timeout");require(w.state.load()==5,"oracle publication failure");}publication_ns+=ns()-t;res[w.layer*512+v]=-1;res[w.layer*512+w.expert]=w.destination;spare[w.dev][w.cls]=old;e.victim=v;e.oldslot=old;e.publish_ns=ns();e.published_at=current;e.status=current<=e.target?1:3;incoming_event[w.layer*512+w.expert]=w.index;victim_event[w.layer*512+v]=w.index;copy_us=.9*copy_us+.1*((e.stage_end-e.stage_begin+e.copy_end-e.copy_begin)/1000.);w.state.store(0,std::memory_order_release);}
 void issue(Worker& w,int l,int expert,int target){require(w.state.load()==0,"issue into busy spare");const uint8_t* src=source(l,expert);require(src,"missing immutable RAM expert");require(blobs[l]==sizes[w.cls]&&l/24==w.dev,"byte-class/device mismatch");OracleEvent e{};e.issue_ns=ns();e.trigger=current;e.target=target;e.published_at=-1;e.layer=l;e.incoming=expert;e.victim=e.oldslot=-1;e.slot=spare[w.dev][w.cls];e.bytes=blobs[l];e.status=0;require(events.size()<events.capacity(),"event buffer capacity");events.push_back(e);{std::lock_guard<std::mutex> lk(w.mu);w.index=(int)events.size()-1;w.layer=l;w.expert=expert;w.destination=e.slot;w.src=src;w.n=e.bytes;w.state.store(1,std::memory_order_release);}w.cv.notify_all();}
 void plan(Worker& w){if(w.state.load()!=0)return;int lead=std::clamp((int)std::ceil(copy_us/std::max(40.,event_us))+1,2,16);int limit=horizon?horizon:64;int end=std::min((int)q4_tape.windows.size()*48-1,current+limit);int bestl=-1,beste=-1,besttarget=-1;double best=-1e100;if(++seen_generation==0){candidate_seen.fill(0);++seen_generation;}
  for(int ev=current+lead;ev<=end;++ev){int l=ev%48;if(l/24!=w.dev||cls(l)!=w.cls)continue;const auto& future_window=q4_tape.windows[ev/48];for(int j=0;j<future_window.T*10;++j){int expert=future_window.routes.ids[l][j],key=l*512+expert;if(candidate_seen[key]==seen_generation||res[key]>=0)continue;candidate_seen[key]=seen_generation;++opportunities;int target=next(l,expert,current+1);if(target<0)continue;int v=victim(l,expert,current);if(v<0)continue;int vn=next(l,v,current);if(vn>=0&&vn<=target)continue;int utility_end=horizon?current+horizon:std::min((int)q4_tape.windows.size()*48-1,current+768);int uses=count(l,expert,current+1,utility_end),damage=count(l,v,current+1,utility_end);double utility=strategy?double(uses-damage)-2.0:double(limit-(target-current))+.05*(uses-damage);if(strategy&&uses-damage<4)continue;if(utility>best){best=utility;bestl=l;beste=expert;besttarget=target;}if(!strategy&&bestl>=0)break;}if(!strategy&&bestl>=0)break;}
  if(bestl>=0)issue(w,bestl,beste,besttarget);
 }
 void host(int l,const int32_t* ids,int n){if(!tracked||!q4_tape.active)return;current=(int)q4_tape.index*48+l;uint64_t t=ns();if(active){if(last_event>=0&&current==last_event+1){double us=(t-last_boundary)/1000.;event_us=.95*event_us+.05*std::clamp(us,40.,5000.);}last_event=current;last_boundary=t;for(auto& a:workers)for(auto& w:a)if(w.dev>=0){require(w.state.load()!=7,"worker error at milestone");publish(w);}for(int j=0;j<n;++j){int key=l*512+ids[j];int i=incoming_event[key];if(i>=0&&res[key]>=0){++events[i].uses;if(current<=events[i].target)++ready_entries;else if(events[i].published_at>events[i].target)++late_entries;}int v=victim_event[key];if(v>=0&&res[key]<0)++events[v].victim_uses;}for(auto& a:workers)for(auto& w:a)if(w.dev>=0)plan(w);}if(!active)last_boundary=t;planner_ns+=ns()-t;}
 void observe_plan(int l,const int32_t* ids,int n,const int32_t* kind){if(!tracked||!q4_tape.active)return;OracleLayer a{};a.event=q4_tape.index*48+l;a.layer=l;a.n=n;a.begin=last_boundary;a.plan_end=ns();for(int j=0;j<n;++j){a.ids[j]=ids[j];a.slots[j]=res[l*512+ids[j]];a.path[j]=kind[j];}layers.push_back(a);}
 void observe_cpu(){if(tracked&&q4_tape.active&&!layers.empty())layers.back().cpu_end=ns();}
 void note_native(int l,int in,int out,int s,uint64_t n){if(!tracked||!q4_tape.active)return;natives.push_back({ns(),0,n,(int)q4_tape.index,l,in,out,s});}
 void native_ready(int l,int expert){if(!tracked||!q4_tape.active)return;for(auto i=natives.rbegin();i!=natives.rend();++i)if(i->layer==l&&i->incoming==expert&&!i->publish_ns){i->publish_ns=ns();break;}}
 void finish(){if(!tracked)return;uint64_t t=ns();if(active){for(auto& a:workers)for(auto& w:a)if(w.dev>=0)retire(w,4);drain_ns+=ns()-t;t=ns();int old;ck(cudaGetDevice(&old));for(int d=0;d<2;++d)for(int c=0;c<3;++c){if(d==1&&c==2)continue;int l=donor_layer[d][c],e=donor_expert[d][c];if(res[l*512+e]>=0){float best=-1;e=-1;for(int x=0;x<512;++x)if(res[l*512+x]<0&&heat[l*512+x]>best){best=heat[l*512+x];e=x;}require(e>=0,"reserve restoration needs a nonresident expert");}ck(cudaSetDevice(d));ck(cudaMemcpy(slot(d,spare[d][c]),source(l,e),blobs[l],cudaMemcpyHostToDevice));res[l*512+e]=spare[d][c];ck(cudaMemcpy(dres[d]+l*512+e,res+l*512+e,4,cudaMemcpyHostToDevice));}ck(cudaSetDevice(old));restore_ns=ns()-t;}
  uint64_t copied=0,published=0,unused=0,uses=0,victims=0,nbytes=0,npub=0,ready=0,late=0;for(auto& e:events){if(e.copy_end)copied+=e.bytes;if(e.publish_ns){++published;uses+=e.uses;victims+=e.victim_uses;if(e.status==1)++ready;else++late;}if(!e.uses)unused+=e.bytes;}for(auto& n:natives){nbytes+=n.bytes;npub+=n.publish_ns!=0;}
  const char* prefix=std::getenv("STRATA_Q4_ORACLE_LOG");if(prefix){auto write=[&](const char* name,auto& values){std::string p=std::string(prefix)+name;FILE* f=std::fopen(p.c_str(),"wbx");require(f,"oracle artifact exists");Q4Tape::io(f,values.data(),values.size(),true);std::fclose(f);};write("-layers.bin",layers);write("-admissions.bin",events);write("-native.bin",natives);}
  std::fprintf(stderr,"Q4_ORACLE_END active=%d scope_layers=48 horizon=%d strategy=%s layers=%zu issued=%zu completed_bytes=%llu published=%llu ready_publications=%llu late_publications=%llu used_entries=%llu target_ready_entries=%llu late_useful_entries=%llu unused_bytes=%llu victim_absent_entries=%llu native_issued=%zu native_bytes=%llu native_published=%llu planner_ms=%.3f publication_ms=%.3f drain_ms=%.3f restoration_ms=%.3f setup_ms=%.3f active_spares=%d\n",active, horizon,strategy?"reuse":"deadline",layers.size(),events.size(),(unsigned long long)copied,(unsigned long long)published,(unsigned long long)ready,(unsigned long long)late,(unsigned long long)uses,(unsigned long long)ready_entries,(unsigned long long)late_entries,(unsigned long long)unused,(unsigned long long)victims,natives.size(),(unsigned long long)nbytes,(unsigned long long)npub,planner_ns/1e6,publication_ns/1e6,drain_ns/1e6,restore_ns/1e6,setup_ns/1e6,active?5:0);active=false;tracked=false;
 }
 ~Q4Oracle(){for(auto& a:workers)for(auto& w:a)if(w.dev>=0){if(w.thread.joinable()){{std::lock_guard<std::mutex> lk(w.mu);w.quit=true;w.cv.notify_all();}w.thread.join();}cudaSetDevice(w.dev);cudaEventDestroy(w.done);cudaStreamDestroy(w.stream);cudaFreeHost(w.staging);cudaFreeHost(w.metadata);}}
};inline Q4Oracle q4_oracle;
}
