#!/usr/bin/env python3
"""Exhaust every maximum-cardinality continuation in small components.

The candidate graph is generated by pinned PR36 positive labels. This checker
uses its exported edges, reconstructs each rank change independently and checks
strict native child moments with outward rational enclosures. It does not prove
the inherited all-size tape or scalar interfaces.
"""
import argparse
from collections import Counter, defaultdict
from concurrent.futures import ProcessPoolExecutor
import csv
from fractions import Fraction as Q
from functools import lru_cache
import json
from pathlib import Path
import time


def serial(x):
    if isinstance(x,Q): return str(x)
    if isinstance(x,dict): return {str(k):serial(v) for k,v in x.items()}
    if isinstance(x,(list,tuple)): return [serial(v) for v in x]
    return x


@lru_cache(None)
def log_bounds(n):
    x = Q(n); k = 0
    while x > 2:
        x /= 2; k += 1
    def small(x):
        z = (x-1)/(x+1)
        lower = 2*sum((z**(2*j+1)/(2*j+1) for j in range(40)),Q())
        return lower,lower+2*z**81/(81*(1-z*z))
    lo,hi=small(x); l2,h2=small(Q(2))
    lo += k*l2; hi += k*h2
    scale=10**36
    return Q((lo*scale).numerator//(lo*scale).denominator,scale),Q(-(-(hi*scale).numerator//(hi*scale).denominator),scale)


@lru_cache(None)
def native_power(width,a):
    if width == 0: return Q(),Q()
    low,high=log_bounds(width); u,v=a*low,a*high
    assert 0 <= u <= v < 1
    return width*(1-v+v*v/2-v*v*v/6),width*(1-u+u*u/2-u*u*u/6+u**4/24)


def inner(h,rank):
    assert 0 <= rank <= h
    if 2*rank <= h:
        return Counter({1:rank}) if rank else Counter()
    out=Counter({1:h-rank});out[2*rank-h]+=1
    return +out


def delta_histogram(h,edge):
    ru,rv,rt = (edge[k] for k in ('ru','rv','rt'))
    assert rt >= ru >= rv >= 1
    out=Counter()
    for rank,sign in ((h-ru,-1),(rv,-1),(rt-rv,-1),(rt-ru,1)):
        for width,count in inner(h,rank).items(): out[width]+=sign*count
    assert sum(w*n for w,n in out.items()) == -h
    return out


def schur_dominates(delta):
    # A has positive difference counts, B negative; pad both with zeros.
    A=sorted((w for w,n in delta.items() for _ in range(max(n,0))),reverse=True)
    B=sorted((w for w,n in delta.items() for _ in range(max(-n,0))),reverse=True)
    size=max(len(A),len(B));A += [0]*(size-len(A));B += [0]*(size-len(B))
    assert sum(A)==sum(B)
    ca=cb=0
    for a,b in zip(A,B):
        ca+=a;cb+=b
        if ca < cb: return False
    return True


def moment_difference(hist,a):
    lower=upper=Q()
    for width,count in hist.items():
        lo,hi=native_power(width,a)
        lower+=count*(lo if count>=0 else hi)
        upper+=count*(hi if count>=0 else lo)
    return lower,upper


def component_job(job):
    h,edges,baseline,a,all_degrees=job
    byleft=defaultdict(list)
    for edge in edges: byleft[edge['donor']].append(edge)
    left=sorted(byleft,key=lambda k:(len(byleft[k]),k))
    assert len(left) <= 12, 'Use another bounded solver for a larger component.'
    maximal=[];maximum=-1;all_count=0;all_selected=[]
    def visit(index,used,chosen):
        nonlocal maximum,maximal,all_count
        if index==len(left):
            all_count+=1;degree=len(chosen)
            if all_degrees:all_selected.append(list(chosen))
            if degree>maximum: maximum=degree;maximal=[]
            if degree==maximum: maximal.append(list(chosen))
            return
        visit(index+1,used,chosen)
        for edge in byleft[left[index]]:
            if edge['use'] not in used:
                visit(index+1,used|{edge['use']},chosen+[edge])
    visit(0,set(),[])
    index={(e['donor'],e['use']):e for e in edges}
    base=[index[e] for e in baseline if e in index]
    assert len(base)==maximum
    def profile(selected):
        out=Counter()
        for edge in selected: out.update(delta_histogram(h,edge))
        if all_degrees:
            # W falls by one copied bank role per matching. Its exterior
            # children h and m-2h disappear, and the denominator W*m^tau
            # loses m^tau. Compare numerator-minus-denominator additively.
            m=23*25; k=len(selected)
            out[h]-=k;out[m-2*h]-=k;out[m]+=k
            assert sum(w*n for w,n in out.items())==0
        return out
    incumbent=profile(base);unique={};schur=0;positive=0;unresolved=0;best=incumbent;best_edges=base
    for selected in (all_selected if all_degrees else maximal):
        p=profile(selected);key=tuple(sorted((w,n) for w,n in p.items() if n))
        unique.setdefault(key,selected)
    differences=[]
    for key,selected in unique.items():
        p=Counter(dict(key));diff=Counter(p)
        for w,n in incumbent.items():diff[w]-=n
        diff=Counter({w:n for w,n in diff.items() if n})
        low,high=moment_difference(diff,a)
        if not diff: verdict='identical'
        elif schur_dominates(Counter({w:-n for w,n in diff.items()})):
            verdict='baseline_schur_optimal';schur+=1
        elif low>0:verdict='baseline_better_at_pinned_saving';positive+=1
        elif high<0:
            verdict='improved_candidate';best=p;best_edges=selected
        else:verdict='unresolved';unresolved+=1
        differences.append({'difference':dict(diff),'lower':low,'upper':high,'verdict':verdict})
    return {'donors':len(left),'uses':len(set(e['use'] for e in edges)),
            'edges':len(edges),'all_matchings':all_count,'maximal_cardinality':maximum,
            'maximum_matchings':len(maximal),'unique_native_profiles':len(unique),
            'schur_exclusions':schur,'pinned_saving_exclusions':positive,'unresolved':unresolved,
            'differences':differences,'selected':[(e['donor'],e['use']) for e in best_edges],
            'selected_delta':dict(best)}


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--edges',nargs='+',type=Path,required=True)
    parser.add_argument('--output',type=Path,required=True)
    parser.add_argument('--workers',type=int,default=7)
    parser.add_argument('--all-degrees',action='store_true')
    args=parser.parse_args();start=time.monotonic();results=[]
    a=Q(962729831,25000000000000)
    for path in args.edges:
        edges=[{k:int(v) for k,v in row.items()} for row in csv.DictReader(path.open())]
        baseline={(int(r['donor']),int(r['use'])) for r in csv.DictReader(Path(str(path)+'.selected.csv').open())}
        original=json.loads(Path(str(path)+'.unmatched.json').read_text());h=original['h']
        adj=defaultdict(set);edge_lookup=defaultdict(list)
        for edge in edges:
            l=('L',edge['donor']);r=('R',edge['use']);adj[l].add(r);adj[r].add(l);edge_lookup[l].append(edge)
        seen=set();components=[]
        for root in adj:
            if root in seen:continue
            todo=[root];left=[]
            while todo:
                v=todo.pop()
                if v in seen:continue
                seen.add(v);todo.extend(adj[v]-seen)
                if v[0]=='L':left.append(v)
            component=[e for l in left for e in edge_lookup[l]]
            basematch={e for e in baseline if ('L',e[0]) in left}
            components.append((h,component,basematch,a,args.all_degrees))
        with ProcessPoolExecutor(max_workers=args.workers) as pool:
            cases=list(pool.map(component_job,components,chunksize=20))
        hist=Counter({i:n for i,n in enumerate(original['histogram'])})
        for c in cases:
            # Convert native-width deltas only for moment comparison; physical
            # rank histograms need selected original edges, not this counter.
            assert sum(int(w)*n for w,n in c['selected_delta'].items()) == (0 if args.all_degrees else -h*c['maximal_cardinality'])
        totals={key:sum(c[key] for c in cases) for key in ['all_matchings','maximal_cardinality','maximum_matchings','unique_native_profiles','schur_exclusions','pinned_saving_exclusions','unresolved']}
        results.append({'h':h,'edge_count':len(edges),'components':len(cases),'largest_donor_component':max(c['donors'] for c in cases),'totals':totals,'component_results':cases})
        print(json.dumps({'h':h,'components':len(cases),'totals':totals}),flush=True)
    args.output.write_text(json.dumps(serial({'saving':a,'workers':args.workers,'all_degrees':args.all_degrees,'elapsed_seconds':time.monotonic()-start,'scope':('All cardinalities; complete generic copied-center numerator minus W*m^tau.' if args.all_degrees else 'All maximum-cardinality matchings in the pinned positive-label continuation graph;')+' No other producer, relabeling or physical compiler family is excluded.','results':results}),indent=2)+'\n')


if __name__ == '__main__':main()
