"""Price observed instrumented tasks; extrapolation is not clean timing or p95."""
import datetime,json,pathlib,statistics,time,re
C=pathlib.Path(__file__).resolve().parents[1]
def load(n):return json.loads((C/n).read_text())
def save(n,x):(C/n).write_text(json.dumps(x,indent=2)+'\n')
s=load('analysis/trace-diversity.json')['tasks'];scan=load('analysis/offline-scan-cost.json');m=load('benchmark-manifest.json');t=load('timing.json')
setup=next(json.loads(x)['elapsed_s'] for x in (C/'progress.jsonl').read_text().splitlines() if json.loads(x)['step']==4 and json.loads(x)['state']=='START')
measured=sum(x['total_operating_s'] for x in s);screen=[x for x in s if x['screening']];costs=[x['total_operating_s'] for x in s];byprofile={p:[x for x in s if x['context_limit']==p] for p in [32768,131072]}
per=[]
for x in s:
 residual=x['request_wall_s']-x['prefill_s']-x['decode_s'];sumphase=x['startup_s']+x['warmup_s']+x['request_wall_s']+x['trace_drain_s']+x['shutdown_s'];misc=x['total_operating_s']-sumphase
 per.append({'task':x['task_id'],'startup_s':x['startup_s'],'warmup_s':x['warmup_s'],'tokenization_prefill_s':x['prefill_s'],'decode_s':x['decode_s'],'request_residual_attestation_streaming_s':residual,'post_stream_trace_drain_s':x['trace_drain_s'],'shutdown_s':x['shutdown_s'],'operational_misc_s':misc,'total_s':x['total_operating_s'],'instrumented':True,'natural_output_cap':2048})
def estimate(rows,arms):
 # Empirical operating cost envelope of this run; one recording per task.
 total=sum(x['total_operating_s'] for x in rows)*arms;lower=0;upper=0
 for x in rows:
  pool=byprofile[x['context_limit']];start=[y['startup_s'] for y in pool];warm=[y['warmup_s'] for y in pool];shutdown=[y['shutdown_s'] for y in pool]
  fixed=x['request_wall_s']+x['trace_drain_s'];lower+=(min(start)+min(warm)+min(shutdown)+fixed)*arms;upper+=(max(start)+max(warm)+max(shutdown)+fixed+5)*arms
 return {'tasks':[x['task_id'] for x in rows],'arms_per_task':arms,'observed_component_projection_s':total,'empirical_component_range_s':[lower,upper],'analysis_cleanup_reserve_s':600,'shared_setup_s':setup,'campaign_projection_s':setup+total+600,'campaign_range_s':[setup+lower+600,setup+upper+600],'phase_cap_upper_operating_s':len(rows)*arms*455,'preflight_and_validation_extra_caps_s':len(rows)*arms*120,'scope':'Instrumented measured task costs repeated; empirical envelope,not CI/p95. Clean timing,policy overhead and future EOS unknown.'}
full=estimate(s,1);fullsix=estimate(s,6);fulltwelve=estimate(s,12);quick=estimate(screen,1);one=estimate(screen,6);four=estimate(screen,12)
selected=screen[:]
while selected and estimate(selected,12)['campaign_range_s'][1]>7200:selected.pop()
reduced=estimate(selected,12)
rawbytes=sum(p.stat().st_size for p in (C/'raw').rglob('*') if p.is_file())
result={'defined_tasks':len(m['tasks']),'new_measured_tasks':len(s),'trace_ready_tasks':len(s),'one_time_recording':{'shared_audit_corpus_harness_setup_s':setup,'sum_model_operation_s':measured,'current_elapsed_s':load('progress.json')['elapsed_s'] if load('progress.json').get('state')=='DONE' else time.monotonic()-t['start_monotonic'],'new_trace_and_log_storage_bytes':rawbytes,'note':'Elapsed also includes validation/reporting and bounded waits. Preparation of analysis code overlapped operation; do not add it twice.'},'components':per,'offline_data_scan':scan,'quick_development_screen':quick,'full_measured_core_one_pass_per_policy':full,'full_core_baseline_one_finalist_three_pairs':fullsix,'full_core_four_policy_three_repetitions':fulltwelve,'baseline_plus_one_finalist_three_pairs':one,'baseline_two_finalists_oracle_three_repetitions':four,'four_policy_reduced_within_empirical_two_hour_upper':reduced,'shared_controls':'Three contemporary baseline arms per task can serve all comparisons within the same four-arm repetition block, with identical tape/work prefix,engine/config/protocol and matched initial state. Correlation must be retained. Do not duplicate baselines per candidate or reuse stale historical controls,other engines,models or trajectories. Fourpolicies x3repetitions=12arms/task; baseline+onefinalist=6arms/task.','instrumentation':'All new timings use recording hooks; original clean0.1.39 baseline is verified but not newly timed here. Prior short development recording was2.3986s decode/7.1197s request versus original2.1953s/6.1720s. Do not extrapolate that overhead as a universal correction.','hard_bound_note':'180s startup+warmup,240s request,35s bounded owned drain/shutdown allowance=455s per operating arm. Budget additionally allows30s preflight and90s structural validation; hardPhase0 deadline remains60min. A future paired matrix requires its own total deadline; empirical ranges are not guaranteed ceilings.','unmeasured':[{k:x[k] for k in ['task_id','profile','actual_input_tokens','measurement_status']} for x in m['tasks'] if x['measurement_status']!='MEASURED'],'selection':'Screening is the predeclared development task per family,chosen for provenance,source diversity and bounded length; not routing or oracle gain. Reduced four-policy subset retains that frozen order until the empirical upper estimate fits two hours; broader suite remains available offline.'}
save('runtime-budget.json',result)
lines=['# Runtime budget\n\nAll new costs are **instrumented natural recording** costs, not clean-baseline speed measurements. One sample per task supplies no robust p95 or confidence interval. Source-group diversity and performance repetitions are different quantities.','`arm_cost = startup + warmup + tokenization/prefill + decode + trace/commit/drain + shutdown`','`campaign_cost = shared_setup + sum(each scheduled arm) + analysis_and_cleanup_reserve`',f"One-time preparation: {setup/60:.2f} min; actual summed model operations: {measured/60:.2f} min; retained new trace/log bytes: {rawbytes/1024**3:.3f} GiB. Data preparation scan: {scan['total_s']:.2f} s across {len(s)} tasks. Policy replay/evaluation execution was not timed; its cost remains unknown, separate from this scan.",'| Future schedule | Tasks | Arms/task | Observed-component projection min | Empirical component range min | With setup + 10min reserve | Phase-cap operating ceiling min |','|---|---:|---:|---:|---:|---:|---:|']
for label,v in [('Quick development screening',quick),('Full measured core / one policy',full),('Full core baseline + finalist / three pairs',fullsix),('Full core four policies / three repetitions',fulltwelve),('Baseline + one finalist / three pairs',one),('Baseline + two finalists + oracle / three repetitions',four),('Reduced four-policy task set',reduced)]:
 lo,hi=v['empirical_component_range_s'];cl,ch=v['campaign_range_s'];lines.append(f"| {label} | {len(v['tasks'])} | {v['arms_per_task']} | {v['observed_component_projection_s']/60:.2f} | {lo/60:.2f}–{hi/60:.2f} | {cl/60:.2f}–{ch/60:.2f} min | {v['phase_cap_upper_operating_s']/60:.2f} |")
lines+=['\nThe empirical envelope varies observed startup/warmup/shutdown components within each context and retains each task\'s observed request cost,plus5s per arm at the upper end. It is an estimate from this hardware/run,not a probabilistic guarantee. Phase caps provide a separate planning ceiling; preflight/validation allowance is additional. CPU/VM scheduling,OS cache,actual EOS and future policy work can change costs.',f"Screening task IDs: {', '.join(x['task_id'] for x in screen)}. The predeclared roles choose them without inspecting routing or oracle benefit.",f"Four-policy reduced IDs: {', '.join(x['task_id'] for x in selected)}. If the larger empirical envelope exceeds120min,this reduction is explicit; it does not delete the remaining corpus.",result['shared_controls'],result['instrumentation'],'Later A/B arms must replay the same validated completed logical tape prefix,including rejected speculative work,or use frozen output/work budgets. Giving each policy60s and comparing raw routed counts would compare different work. Natural output-limit slices do not imply task completion.','Short prompts remain short; a128K context limit does not imply128K input occupancy. No costs from unmeasured tasks are averaged into measured totals. Historical extended tapes have their original protocols and do not substitute for new clean timing.']
(C/'runtime-budget.md').write_text(re.sub(r'(?m)^(\|[^\n]+\|)\n\n(?=\|)',r'\1\n','\n\n'.join(lines)+'\n'));print('RUNTIME BUDGET WRITTEN',len(s),'measured tasks')
