"""Render the final evidence report from audited raw-derived summaries, never invented metrics."""
from pathlib import Path
import json,statistics,datetime
C=Path(__file__).resolve().parents[1]
def load(p):return json.loads(Path(p).read_text())
def med(v):return statistics.median(v)
def fmt(v,n=2):return 'unknown' if v is None else f'{v:,.{n}f}'
def table(headers,rows):return '| '+' | '.join(headers)+' |\n|'+ '|'.join(['---']*len(headers))+'|\n'+'\n'.join('| '+' | '.join(map(str,r))+' |' for r in rows)+'\n'
def render():
 s=load(C/'summary.json');assert s['state']=='COMPLETE' and len(s['rows'])==18
 o=load(C/'phase-a/overhead-v3-summary.json');ind=load(C/'phase-c/independent-v3-summary.json');short=load(C/'phase-c/short64-v3-summary.json')
 def cell(p,policy):return next(x for x in s['cells'] if x['profile']==p and x['policy']==policy)
 def m(c,k):return c['metrics'][k]['median'] if c['metrics'][k] else None
 def rr(p,policy):return [x for x in s['rows'] if x['profile']==p and x['policy']==policy]
 main=[];ranges=[];hardware=[];funnels=[];progress=[];paired=[];numeric=[];reuse=[];residual=[];costs=[];setup=[];cpu_spans=[];capacities=[]
 for p in ['32k','128k','256k']:
  for pol in ['REPLAY_CURRENT','REPLAY_ORACLE_FULL']:
   c=cell(p,pol);a=rr(p,pol);first=a[0]
   main.append([p,str(first['actual_input_tokens'])+'/4096',pol,'48 main layers / 3 classes',f"{c['attempts']}/{c['valid']}",'YES',fmt(m(c,'prefill_s')),fmt(m(c,'decode_s')),fmt(m(c,'replay_equivalent_tok_s')),fmt(m(c,'wall_s')),fmt(m(c,'local_pct')),f"{int(m(c,'CPU_entries')):,} / {int(m(c,'mapped_entries')):,}",fmt(m(c,'copy_GB')),f"{int(m(c,'ready_publications')):,} / {int(m(c,'late_publications')):,}",fmt(m(c,'planner_ms'))])
   for k in ['PP','decode_s','replay_equivalent_tok_s','wall_s','TTFT_s']:
    d=c['metrics'][k];ranges.append([p,pol,k,fmt(d['min']),fmt(d['median']),fmt(d['max'])])
   hw=[load(C/'analysis'/f"{x['label']}-system.json") for x in a]
   hardware.append([p,pol,fmt(m(c,'CPU_mean_decode_pct')),fmt(m(c,'GPU0_mean_decode_pct')),fmt(m(c,'GPU1_mean_decode_pct')),fmt(med(h['rss_gib']['max'] for h in hw)),fmt(med(h['gpus']['0']['vram_mib']['max'] for h in hw)/1024),fmt(med(h['gpus']['1']['vram_mib']['max'] for h in hw)/1024),fmt(med(h['cpu_steal_pct']['mean'] for h in hw)),fmt(med(h['process_cpu_pct']['mean'] for h in hw)),fmt(med(h['gpus']['0']['power_w']['mean'] for h in hw))+' / '+fmt(med(h['gpus']['1']['power_w']['mean'] for h in hw))])
   pp=[load(C/'analysis'/f"{x['label']}-progression.json")['intervals'] for x in a]
   progress.append([p,pol,*[fmt(med(v[j]['interval_equivalent_tok_s'] for v in pp)) for j in range(4)],fmt(m(c,'replay_equivalent_tok_s'))])
   aa=[load(C/'analysis'/f"{x['label']}-oracle.json") for x in a]
   cp=aa[0]['copies']
   funnels.append([p,pol,cp['issued'],fmt(cp['staged_bytes']/1e9),fmt(cp['completed_bytes']/1e9),fmt(cp['native_published_bytes']/1e9),cp['published'],cp['ready_publications'],cp['late_publications'],cp['uses'],cp['victim_absent'],fmt(cp['unused_bytes']/1e6)])
   for x in a:
    f=load(C/'phase-a'/f"{x['label']}-fidelity.json");z=f['selected_activation_check'];h=f['native_main_head_agreement']
    numeric.append([x['label'],str(z['bitwise_equal']),fmt(z['relative_L2'],5),fmt(z['max_abs_error'],5),str(z['first_divergence_window_role_component']),fmt(h['fraction']*100,3)])
    setup.append([x['label'],fmt(f['initial_state']['setup_ms']/1000,3),fmt(f['lookup_ms']),f['tape']['RAM_tape_MB'],f['initial_state']['bytes_checked']])
   z=load(C/'analysis'/f"{a[0]['label']}-event-diagnostics.json")['host_quant_group_compute_completion_span']
   cpu_spans.append([p,pol,z['CPU_positive']['count'],fmt(z['CPU_positive']['median_us']),fmt(z['CPU_positive']['p95_us']),fmt(z['CPU_positive']['sum_ms']/1000,3),z['mapped_positive']['count']])
   if pol=='REPLAY_ORACLE_FULL':
    lab=a[0]['label'];r=load(C/'analysis'/f'{lab}-persistent-lifetimes.json');q=load(C/'analysis'/f'{lab}-residual-misses.json');d=load(C/'analysis'/f'{lab}-event-diagnostics.json')
    reuse.append([p,r['published'],r['admissions_with_repeated_distinct_invocations'],r['admissions_with_use_after_intended_target'],r['total_distinct_resident_uses'],r['resident_lifetime_right_censored_at_end']])
    residual.append([p,q['nonlocal_entries'],q['reasons'].get('victim_absent',0),q['reasons'].get('copy_pending_at_demand',0),q['reasons'].get('copy_complete_not_published_at_demand',0),q['reasons'].get('no_observed_admission_before_demand',0)])
    z=aa[0]['ms'];costs.append([p,fmt(d['future_lead']['logical_invocations']['median']),fmt(d['future_lead']['issue_to_actual_target']['median_us']/1000,3),fmt(z['staging']['median'],3),fmt(z['copy_with_host_wait']['median'],3),fmt(z['publication_delay_after_copy']['median'],3)])
  pair=next(x for x in s['paired'] if x['profile']==p)['median_of_paired_ratios'];a=cell(p,'REPLAY_CURRENT');b=cell(p,'REPLAY_ORACLE_FULL')
  paired.append([p,fmt(100*(pair['throughput_oracle_over_current']-1))+'%',fmt(100*(1-pair['decode_time_oracle_over_current']))+'%',fmt(100*(1-pair['wall_oracle_over_current']))+'%',fmt(100*(m(b,'replay_equivalent_tok_s')/m(a,'replay_equivalent_tok_s')-1))+'%'])
  import numpy as np
  n=rr(p,'REPLAY_CURRENT')[0]['actual_input_tokens'];v=np.fromfile(C/'tapes'/f'capture-{p}-v3.bin',dtype='<i4',count=48*512,offset=64+4*n).reshape(48,512)
  g0=int(np.count_nonzero(v[:24]>=0));g1=int(np.count_nonzero(v[24:]>=0));capacities.append([p,g0,g1,g0-3,g1-2,fmt(100*(g0+g1)/(48*512))])
 conclusion='FEASIBLE_LIVE_ORACLE_GAIN' if all(x['median_of_paired_ratios']['throughput_oracle_over_current']>1.03 for x in s['paired']) and all(x['same_output_ids'] and x['same_MTP'] for x in o['paired']) else 'SCOPED_ORACLE_GAIN_NEEDS_VALIDATION'
 lines=['# Q4 live oracle: fixed logical work and real transfers',f"Generated {datetime.datetime.now(datetime.timezone.utc).isoformat()}. All headline data are from the final v3 binary and fresh paired runs; earlier pilots are excluded.",'',f'**Research conclusion: {conclusion}.** The unchanged Q4/100us serving baseline remains the real-use configuration. Clairvoyant replay is not a production replacement, newly generated text, or a model-quality result.','',
 '## Main controlled matrix', 'One saved tape per profile is repeated three times: timing repeatability, not three independent tasks. Both arms use the same experimental binary, recorded work, exact initial state, fixed warmup (4096 input / 64 output), and natural uncached prefill. Output normalization is 4096 visible recorded output IDs. Internal commit-position advances and end-window excess are retained and charged.', '',
 table(['Context','Tape input/output','Policy','Scope','Attempts/valid','Work hash match','Prefill s','Replay decode s','Replay-equivalent tok/s','Total wall s','Local %','CPU / mapped entries','Copy GB','Ready / late publications','Online planner ms'],main),'',
 'Ready/late in this table counts published admissions, not all routed entries; target-ready demand and later uses are in the raw funnel. Copy GB includes native completed publications, oracle completed copies and mandatory spare-restoration payload. Native pending-at-end bytes remain separately recorded. Planner time includes publication wait and overlaps other work: do not add timers.', '',
 table(['Context','Median paired TG gain','Median paired decode reduction','Median paired wall reduction','Ratio-of-medians TG gain'],paired),'',
 table(['Context','Policy','Metric','Min','Median','Max'],ranges),'',
 '## Logical clock and record/replay contract',
 'Request 1 is the fixed warmup; request 2 is the taped workload. Identity is verifier window, model role (main / actual MTP catchup or draft), absolute position, speculative lane and layer. Main event = window * 48 + layer. Each invocation is the complete T-by-10 routing batch; no concurrent batch is converted to serial individual-expert computation. Main layers retain their normal dependency chain; draft, verify, commit and rollback retain the recorded schedule.',
 'Actual MTP rounds compute native T-row KV-only catchup, including rejected lanes, then a full one-row routed MTP layer for accepted row a and each subsequent recorded draft. Catchup has no router/expert kernel; its invocation count and shape derive from T and draft_count. No catchup kernels are skipped.\n\nThe tape freezes input/output IDs, T, branch proposal/acceptance and draft-count schedule, routing IDs and float32 mixture coefficients, and all 12 sparse-attention selection lists. Causal masks follow unchanged positions/lane shapes. Dense layers, attention/KV/PLE/GDN, router computation, expert/shared kernels, head/draft work and rejected branches still compute normally. Overrides are applied only after native discrete decision computation. No hidden activations are replaced. Physical local/CPU/mapped grouping changes intentionally with residency.',
 'Work SHA256 covers token/window/routes/coefficients/shapes and implicit dependency order, excluding timestamps and service placement. Initial resident slots, usage heat, native adaptation phase, GDN/PLE/HC_R, meaningful KV/QSA mappings and written canonical host prefix, and MTP state have a separate strict sidecar identity. Oracle transfers and five-slot withdrawals start inside timed decode, after this state check. Unwritten host tail and unused old MTP prefix are not meaningful state.', '',
 '## Fidelity and overhead',
 table(['Short development mode','Actual input / output','Decode s','Request wall s','Scope'],[
 ['NATURAL_CONTROL, frozen original','4096/256',fmt(o['original_binary_reference']['decode_s'],4),fmt(o['original_binary_reference']['wall_s'],4),'one reference'],
 ['NATURAL_CONTROL, common v3 ordinary','4096/256',fmt(med(x['decode_s'] for x in o['natural']),4),fmt(med(x['wall_s'] for x in o['natural']),4),'three paired fresh starts'],
 ['CAPTURE, buffered diagnostics','4096/256',fmt(o['recording']['decode_s'],4),fmt(o['recording']['wall_s'],4),'one record, excluded from speed controls'],
 ['REPLAY_CURRENT, common v3','4096/256',fmt(med(x['decode_s'] for x in o['replay']),4),fmt(med(x['wall_s'] for x in o['replay']),4),'three paired fresh starts']]),
 f"All 18 primary executions passed work/count/token/route/coefficient/shape checks and identical initial-state attestation. Replay-current guards showed zero natural router/coefficient/QSA/head disagreement. Natural versus replay-current short-workload median paired decode-time ratio = {o['median_paired_decode_time_ratio']:.4f}; wall ratio = {o['median_paired_wall_ratio']:.4f}. Original frozen-binary output matches all three experimental natural runs: {o['original_binary_output_matches_all_natural']}. These overhead results use the declared 256-output development workload, not the full 4096-output task.",
 'Initial-state attestation is pre-decode setup, outside PP/TG but inside total request wall. The first 256K oracle attestation took 14.084 s versus 3.807 s for its paired control; it remains a valid, included timing observation. Oracle residency is inactive at that boundary, so this drift is not attributed to expert scheduling. See per-run setup times and median paired ratios; no post-hoc outlier exclusion.',
 'Main sparse-attention logical selections and resolver/copy kernel launches are fixed, but native atomic CLOCK page placement can slightly change physical KV refill transactions. Available primary-device cumulative block-lookups agree; 256K first-pair RAM refills are 6075.9 versus 6075.7 MiB. Secondary-device refill counters are unavailable. This limits strict physical-service identity at streamed contexts; 32K has fully resident KV. See phase-a/KV-service-fidelity.md.',
 'Forced output/MTP equality is enforced and is not correctness proof. Residency changes CPU Q8_K versus GPU Q8_1 activation quantization and summation, so natural numerical/head trajectories may diverge. Real Q4 expert tests against dequant reference passed all three byte classes; sampled real copied expert bytes, ownership, publication and cancellation tests provide separate safety evidence. Eight live activation components per routed invocation are compared against capture with first divergence and relative L2; native main-head top-1 agreement is also reported before overrides. These samples remained finite and are numerical diagnostics, not full tensor parity or task-quality evaluation.', '',
 '## Scheduling, physical capacity and traffic',
 'The oracle controls all 48 main routed layers, with K=24 ownership and 3.072/3.584/3.9936 MB physical classes. MTP keeps its unchanged all-resident expert cache. Five existing class-compatible slots are withdrawn inside timed decode: GPU0 has one of each class, GPU1 has the two classes present on its layers. This costs five active residents and 17,305,600 bytes of charged spare payload; original allocated VRAM does not increase. There is no P2P, remote expert execution or combined 48 GiB virtual pool.',
 table(['Context','Initial GPU0 residents/slots','Initial GPU1 residents/slots','Oracle active GPU0','Oracle active GPU1','Initial resident expert %'],capacities),
 'Weights come from the immutable full-RAM arena, through pinned staging and asynchronous H2D copy streams with completion events. The victim remains live until a complete copy can publish at a safe routed-layer boundary. Current full-window demands protect victims. Slot identity and exclusive per-class transaction ownership are checked; this implementation uses single-owner worker state rather than an additional numeric generation counter. A promoted expert persists until a later justified exchange. Late copies fall back to the actual CPU/mapped path, never skipping or substituting experts.',
 'Replay-current keeps original native adaptation. Oracle takes sole exchange authority in its scope while native causal heat accounting continues. Total native/oracle traffic is reported rather than only incremental oracle copies. Full-future next-use information guides victims; the rolling issue frontier is 64 main routed-layer invocations, and measured progress determines roughly 2–16 invocation lead. This is one feasible next-use/slack heuristic, not an optimal schedule or upper bound. Transfers are triggered by logical milestones, never recorded absolute seconds.',
 'Request-comparable wall includes buffered trace flush, final asynchronous state commit, pending-copy drain and mandatory spare restoration. Native decode timing ends before the final commit/drain/restoration; their measured cost remains in total wall and is not hidden as free work. Request wall does not include fresh process loading or offline tape construction; these are separately preserved startup/recording/planning costs. The future index is built in RAM before request timing in both replay arms. Final persistent resident identity need not equal the initial set; fresh starts re-establish the exact initial state for the next arm.', '',
 'The next funnel table uses attempt 1 only at each profile, so its count conservation is literal. These are oracle transaction counts; native published traffic is a separate column. All per-run funnels remain in analysis. Main performance and hardware tables use medians. No unlogged selection rejection is invented as zero.',
 table(['Context','Policy','Issued','Staged GB','Oracle completed GB','Native published GB','Published','Target-ready','Late','Resident demand uses','Victim-absent entries','Unused MB'],funnels),'',
 table(['Context','Attempt-1 published','Reused in >=2 distinct invocations','Used after intended target','Distinct resident uses','Resident lifetime censored at end'],reuse),
 'Repeated invocation counts exclude duplicate lane entries inside one batch. Resident lifetimes ending with the request are right-censored. All copies in the tested full-future schedules completed and published; unused published bytes are distinct from unpublished bytes.',
 table(['Context','Median issue lead (invocations)','Median issue-to-target ms','Median staging ms','Median copy+host-wait ms','Median completion-to-publication ms'],costs),
 '## Decode progression and hardware',
 table(['Context','Policy','TG 0–512','TG 512–1K','TG 1K–2K','TG 2K–4K','Final TG'],progress),
 'Intervals use complete verifier-window timestamps with boundary overshoot retained. They include actual MTP/draft/adaptation work. Per-interval local/CPU/mapped counts and MTP acceptance are preserved in analysis/*-progression.json; the frozen MTP trajectory is identical between policies.', '',
 table(['Context','Policy','VM CPU mean %','GPU0 mean %','GPU1 mean %','Peak decode RSS GiB','VRAM0 GiB','VRAM1 GiB','CPU steal mean %','Process CPU % (one core=100)','GPU0 / GPU1 power W'],hardware),
 'CPU steal and startup/attestation drift are retained limitations, not exclusion criteria. Aggregate 1 Hz PCIe samples are separate from logical expert-copy bytes. They do not identify event-level DMA duration or saturation. Host staging/queue/completion/publication timestamps have scheduling and CUDA-wait contributions; overlapping timers are not summed. CPU expert arithmetic and mapped GPU execution remain distinct paths. Physical process I/O cannot be attributed to experts; host arena residence is verified independently.', '',
 'CPU steal is systematically higher in the busier current arm (about 5–9% versus 0.7–1.9%). This may reflect VM scheduling sensitivity to the additional CPU demand; the data cannot identify all host activity. The measured paired gain is for this VM under retained conditions, not a hardware-only speed bound with steal eliminated.',
 table(['Context / attempt1','Policy','CPU-positive invocations','Median completion span us','P95 span us','Summed spans s (overlapping)','Mapped-positive invocations'],cpu_spans),
 'These spans include activation quantization, host group/job construction and native CPU completion. They are not pure exposed waits, and can overlap GPU work. In representative 32K native timing, CPU work fell from 11.22 to 0.75 ms/window while planner rose from 0.21 to 3.77 ms/window and GPU-reach wait rose from 5.89 to 8.24 ms/window. The complete window fell from 30.23 to 25.84 ms. These native labels overlap; they are diagnostic evidence rather than an additive causal decomposition.',
 '## Horizons and independent workload',
 'The horizon unit is one future main-model verify routed-layer batch invocation; 48 invocations correspond to one complete main window. Offline horizons 1/4/16/64 and full future are separate capacity-only or transfer-modeled simulations, with no simulated TG. An early bounded simulation accidentally protected current-window demand outside H; repaired strict simulations restrict that privileged safety knowledge. The old safety-privileged output remains diagnostic evidence, not a valid bounded arm.',
 'Both live full and H64 arms use the same 64-invocation incoming issue frontier. Full future additionally has longer victim next-use/lifetime knowledge, and utility queries beyond that issue frontier; H64 bounds both sides. Therefore the negative H64 result does not establish that incoming prediction alone must exceed 64 invocations. It particularly exposes the importance of victim/reuse knowledge and consequent admission choices.',
 f"One audited live H64 confirmation (both admission and victims bounded) took {short['run']['decode_s']:.3f} s, {short['run']['equivalent_tok_s']:.2f} replay-equivalent tok/s. It issued 99,704 copies / 317.525 GB and caused 85,392 victim-absent routed entries. Full-future attempt 1 issued 65,806 copies / 207.126 GB and caused 10,036 victim-absent entries. The extra churn and victim damage explain why this tested shorter policy loses despite more admissions. It is a later single scoped measurement, not an extra fresh paired ranking against the three-attempt primary matrix. It measures this short-horizon heuristic, not an information-theoretic limit.",
 f"A substantive independent Python zipfile/archive source task was captured separately and replayed in three fresh counterbalanced pairs with actual copied-byte checks ON in every arm. Median paired throughput ratio = {ind['median_paired_throughput_ratio']:.4f}; wall ratio = {ind['median_paired_wall_ratio']:.4f}. It is separate 1024-output diagnostic/application evidence, not mixed into the clean 4096 headline table. See phase-c/independent-v3-summary.json.", '',
 '## Remaining misses and exposed work',
 'Observed nonlocal demands are classified from live ownership/copy records in analysis/*-residual-misses.json. Victim-absent demand takes precedence; pending or complete-but-unpublished copies are separated from demand for which no admission was selected. Unlogged reasons such as worker busy versus utility rejection remain unknown. These categories do not estimate physical read bytes by multiplying routed entries by expert size.',
 table(['Context / attempt1','Nonlocal entries','Victim absent','Copy pending','Complete not published','No observed admission'],residual),
 'Victim absence dominates the remaining nonlocal entries in these full-future runs. This points to exchange scheduling/victim lifetime as remaining headroom, rather than widespread copy lateness. It does not prove a globally optimal policy or that an implementable predictor could reproduce it.',
 'Actual target-ready demand and late-but-useful demand are retained in summary rows. Published-before-target admission is not synonymous with a useful demand hit: an admission can be evicted again before its target. Queue/staging/publication evidence and lifetime/repeated-use data are in event diagnostics. Extra H2D traffic is worthwhile only when the measured CPU/mapped critical path it removes exceeds these costs.',
 '',
 '## Failures, repairs and limitations',
 'The ledger preserves malformed tape validation, relative tape-path failure, compile and stale-symlink build repairs, the native adaptation counter offset after warmup, unfrozen QSA selection in v1, initial numerical-state attestation missing in v2, and the repaired bounded-simulation knowledge leak. v1/v2 pilot timing remains excluded from v3 headlines. No model weights or original runtime were changed.',
 'Native suite: 66 PASS, 2 SKIP, 4 pre-existing missing legacy-fixture/mlock-limit failures. Targeted QSA and actual-Q4 math tests passed; the new state-contract fixture and real-copy scheduler fixture results are in tests/. This does not claim every upstream test passed.',
 'The H64 request completed all work and produced its full valid timing/funnel before owned shutdown. SIGTERM to the frontend/native process group then exposed an upstream frontend double-close BrokenPipeError. The retained shutdown traceback is outside request timing, not a hidden inference failure; final process/GPU audit confirms cleanup. A post-analysis wrong independent label and missing matplotlib package were also preserved and repaired without rerunning inference.',
 'Full future knows this tape ends after 4096 visible outputs; no guard tail was recorded. Tail victim reuse outside the tape is genuinely unknown in deployment. The schedule may exploit finite ending. Capacity-only zero-nonlocal simulation is optimistic; transfer-modeled feasibility is not measured throughput. One tape per profile plus one independent task does not prove universal performance or predictor attainability.', '',
 '## What a future causal predictor should learn',
 'The positive causal target is a useful, target-ready persistent exchange: near-term actual batch demand at sufficient logical lead, repeated residency lifetime, victim next-use/absence loss, and current staging/copy/publication queue feasibility. Generic expert popularity alone misses costly victim mistakes. A practical predictor must jointly decide whether to admit and which valuable resident to protect; oracle traffic is substantial and a cheap selective policy must avoid paying for low-value churn. Full-future results establish feasibility only for measured schedules/workloads.', '',
 '## Reproduce and normal serving',
 'All tools are preserved under scripts/ and launchers/. Experimental capture/replay tools verify identities, refuse GPU/port conflicts, have finite timeouts, create a new isolated reproduction directory after this campaign completes, and clean up only owned processes. Normal serving never selects a tape or oracle.', '',
 '```bash\n# Experimental; replace PROFILE with 32k, 128k or 256k\n./launchers/experimental/capture-128k.sh\n./launchers/experimental/validate-tape.sh --profile 128k\n./launchers/experimental/replay-current-128k.sh\n./launchers/experimental/replay-full-128k.sh\n./launchers/experimental/replay-short-128k.sh\n\n# Unchanged real-use Q4 / 100us control, default host 0.0.0.0\n./launchers/control/start-32k.sh --host 0.0.0.0 --port 8080\n./launchers/control/start-128k.sh --host 0.0.0.0 --port 8080\n./launchers/control/start-256k.sh --host 0.0.0.0 --port 8080\n./launchers/control/stop.sh\n```',
 '## Provenance and audit',
 table(['Run','State-attestation s','Tape lookup ms','Tape RAM MB','Initial bytes checked'],setup),
 table(['Run','Sample bitwise equal','Sample relative L2','Max sample absolute difference','First window/role/component','Native head top-1 agreement %'],numeric),
 'Some copied control configs retain a historical pool-experiment annotation. Effective native command/environment and per-attempt oracle configuration are authoritative; configs/interpretation.json records the metadata erratum. Preliminary v1 short-overhead evidence informed the initial funnel; the final v3 overhead guard was measured after the main matrix and before interpretation. v3 added only pre-decode state attestation to the v2 computational substrate, but this order deviation is retained transparently.',
 'Original serving source: 6f32ec070f23ced9f50e704d854d775da52591ab; binary SHA256 eca9d0d271340a114955d5af8038dbffa139ad096ef0d470bcfea9009d4f8d0d. Final common experimental source: 117bc89b3bacbf263379c336557e6c8aa07aff5e; binary SHA256 30a31432b5aff51bcd4340900c13cad0c8487a832bfdb22d05f9157b88d5bdb3. Both use Strata0.1.39 ancestry, CUDA sm_89 and identical normal build options. Model revision38bb39ee97821de2c9009abb7e93950eec396e66 and existing ud-q4_k_xl-v0132 pack are unchanged.',
 'Standalone measured-data figures are in analysis/plots/. Plotting dependencies are isolated in .analysis-venv with requirements-plotting.txt; they do not modify the frozen control environment. scripts/render_report.py recreates this report from the audited summaries, scripts/aggregate.py recreates CSV/JSON, and scripts/refresh_audits.py recomputes conservation/fidelity analyses. No learned predictor, helper comparison, pool/K/PCIe tuning, or ordinary free-generation oracle run was performed.',
 '## Unfinished and future work',
 'No required bounded phase remains unfinished due to the deadline; the campaign finishes early. A globally optimal variable-size schedule, a recorded guard tail, secondary-device exact KV DMA counters, full hidden-tensor parity and a deployable causal predictor were not established. The optional longer-output amortization test was not necessary after the full matrix and independent task answered feasibility. H64 was one negative scoped confirmation rather than a full context matrix. These are limitations, not hidden positive claims.',
 'Start 2026-10-06 04:06:56 UTC; absolute deadline12:06:56 UTC; no substantial work after11:21:56 UTC. Actual completion, local research commit, launcher checks and no-owned-GPU-process audit are recorded in STATUS and final-audit artifacts. Previous campaigns and normal user launchers remain untouched. No push, PR, remote compute or weight changes.', '',conclusion]
 (C/'report.md').write_text('\n\n'.join(lines)+'\n');(C/'phase-c/report.md').write_text('# Phase C — controlled live replay\n\nSee ../report.md for the complete raw-derived tables. Primary matrix has 18 valid executions with exact work and initial-state match. Extra overhead, independent-task and short-horizon evidence is separated in their JSON summaries.\n')
 print('REPORT_RENDERED',conclusion,flush=True);return conclusion
if __name__=='__main__':render()
