"""Separate phase clocks only with exact clean-candidate trajectory/accounting parity."""
from lab import ROOT,load,save
import csv,re,statistics,pathlib
base=ROOT/'experiments/E029-persistent-runtime';out=base/'analysis/copy-diagnostic.json';rows=[]
for profile in ['32k','128k']:
 d=base/f'v2-diagnostic/{profile}';c=base/f'v2-fixed/final/{profile}/on/rep1';diag=load(d/'raw/run.json');clean=load(c/'raw/run.json');fields=['actual_input_tokens','actual_output_tokens','mtp_proposed','mtp_accepted','verify_windows','local_vram_entries','cpu_fallback_entries','offloaded_entries']
 parity={k:diag.get(k)==clean.get(k) for k in fields};parity['actual_output_IDs']=load(d/'raw/output-ids-request2.json')==load(c/'raw/output-ids-request2.json');parity['input_IDs']=diag['payload']['input_ids_sha256']==clean['payload']['input_ids_sha256']
 log=(d/'raw/run-engine.log').read_text();m=re.search(r'strata persistent: request=(\d+) (.+?); safe-boundary',log);assert m
 stats={k:float(v) if '.' in v else int(v) for k,v in re.findall(r'(\w+)=([\d.]+)',m[2])}
 data=list(csv.DictReader(open(d/'raw/admissions-request2.csv')));a=[{k:int(v) for k,v in row.items()} for row in data]
 def dist(v):return {'min':min(v),'median':statistics.median(v),'p95':sorted(v)[int(.95*(len(v)-1))],'max':max(v)} if v else None
 life={'ready_before_first_subsequent_use':sum(x['first_use_ns']>0 and x['copy_complete_observed_upperbound_publish_ns']>0 and x['first_use_ns']>=x['copy_complete_observed_upperbound_publish_ns'] for x in a),'repeated_use':sum(x['use_windows']>1 for x in a),'uses_per_useful_admission':dist([x['uses'] for x in a if x['uses']]),'lifetime_us_evicted':dist([(x['evicted_ns']-x['copy_complete_observed_upperbound_publish_ns'])/1000 for x in a if x['evicted_ns'] and x['copy_complete_observed_upperbound_publish_ns']]),'publication_after_enqueue_return':all(x['copy_complete_observed_upperbound_publish_ns']>=x['enqueue_return_ns'] for x in a if x['copy_complete_observed_upperbound_publish_ns']),'enqueue_to_publication_us':dist([(x['copy_complete_observed_upperbound_publish_ns']-x['enqueue_begin_ns'])/1000 for x in a if x['copy_complete_observed_upperbound_publish_ns']]),'admissions_with_recorded_prediction':sum(x['prediction_observed_ns']>0 for x in a),'predicted_useful_but_current_miss_preceded_enqueue':sum(x['prediction_observed_ns']>0 and x['prediction_observed_ns']<x['last_nonlocal_demand_before_copy_ns']<=x['enqueue_begin_ns'] for x in a),'first_subsequent_use_after_prediction_us':dist([(x['first_use_ns']-x['prediction_observed_ns'])/1000 for x in a if x['prediction_observed_ns'] and x['first_use_ns']])}
 assert life['publication_after_enqueue_return']
 rows.append({'profile':profile,'state':'PARITY_PASS' if all(parity.values()) else 'TRAJECTORY_DIFF_USE_CAUTION','parity':parity,'diagnostic_stats':stats,'lifetimes':life,'headline':False,'diagnostic_TG':diag['TG'],'clean_TG':clean['TG'],'limits':['Host enqueue interval includes CUDA-call CPU/staging/blocking cost, not isolated GPU transferduration.','Join duration measures onlyexposed adaptionthreadtail afterdraft.','Exact GPUcompletion time unavailable; publication is a checkedcompletion observationupperbound.','Prediction observed may be from anolder window forretainedheat;0meansactualdemand-onlytarget.','Diagnostic clocks/buffers excludedfromheadline. No summation ofoverlappingphases into fabricatedcausal TG.']})
r={'state':'COMPLETE_DIAGNOSTICS','rows':rows};save(out,r);print(rows,flush=True)
