"""Explicit actual-ID, warmup, command/settings, capacity, maxrepeat and OFFguard audit."""
from lab import ROOT,load,save
from pathlib import Path
base=ROOT/'experiments/E029-persistent-runtime/v2-fixed';rows=[];keys=['--spec','--spec-min-p','--mtp','--kv','--kv-resident','--max-context','--pool-workers','--pcie-frac','--prefill','--suffix-draft','--prompt-cache']
for profile in ['32k','128k']:
 for rep in [1,2,3]:
  paths={role:base/f'final/{profile}/{role}/rep{rep}' for role in ['off','on']};a=load(paths['off']/'raw/run.json');b=load(paths['on']/'raw/run.json');wa=load(paths['off']/'raw/warmup.json');wb=load(paths['on']/'raw/warmup.json');args=[r['full_config']['args'] for r in [a,b]]
  checks={'samebinary':a['binary_sha256']==b['binary_sha256'],'same_actual_input':load(paths['off']/'raw/output-ids-input-request2.json')==load(paths['on']/'raw/output-ids-input-request2.json'),'same_warmup_input':load(paths['off']/'raw/output-ids-input-request1.json')==load(paths['on']/'raw/output-ids-input-request1.json'),'same64warmup_budget':wa['actual_output_tokens']==wb['actual_output_tokens']==64,'same4096measured_budget':a['actual_output_tokens']==b['actual_output_tokens']==4096,'reuse0':a['reuse']==b['reuse']==wa['reuse']==wb['reuse']==0,'commoninferenceargs':all(x[x.index(k)+1]==args[0][args[0].index(k)+1] for x in args for k in keys),'sameK25':a['full_config']['layer_split']==b['full_config']['layer_split']=='25','samepool100':a['full_config']['env']['STRATA_POOL_SPIN_US']==b['full_config']['env']['STRATA_POOL_SPIN_US']=='100','samecaps':load(paths['off']/'raw/resource-check.json')['primary_slots']==load(paths['on']/'raw/resource-check.json')['primary_slots'] and load(paths['off']/'raw/resource-check.json')['stage1_slots']==load(paths['on']/'raw/resource-check.json')['stage1_slots']}
  p1=ROOT/f'experiments/E027-pool-baseline/v1/standard/{profile}/sleep100us/rep{rep}';original=load(p1/'raw/run.json');offguard={'sameoriginalP1outputIDs':load(paths['off']/'raw/output-ids-request2.json')==load(p1/'raw/output-ids-request2.json'),'sameoriginalP1MTP_routing':all(a.get(k)==original.get(k) for k in ['mtp_proposed','mtp_accepted','verify_windows','local_vram_entries','cpu_fallback_entries','offloaded_entries'])}
  assert all(checks.values()),checks
  rows.append({'profile':profile,'replicate':rep,'checks':checks,'OFFguard':offguard,'warmup_outputIDs_same':load(paths['off']/'raw/output-ids-request1.json')==load(paths['on']/'raw/output-ids-request1.json'),'warmup_MTPsame':all(wa.get(k)==wb.get(k) for k in ['mtp_proposed','mtp_accepted','verify_windows']),'fixed_repetitions':3})
assert all(len(list((base/f'final/{p}/{r}').glob('rep*/raw/run.json')))==3 for p in ['32k','128k'] for r in ['off','on'])
save(base/'fairness-audit.json',{'state':'PASS_CONTROLLED_PROTOCOL','rows':rows,'limits':'Warmup identicalbudget/input/settings, algorithmadaptation can changewarmupMTP/output; differencesexplicit. OFFvsP1sourceintegrationguard separatetimingcomparison. No extraunchangedpoint repetitions.'});print(rows,flush=True)
