"""Record completed GPU prediction evidence and the preserved/repaired PLE defect."""
from datetime import datetime,timezone
from lab import ROOT,load,save
now=datetime.now(timezone.utc).isoformat();s=load(ROOT/'STATUS.json')
s['updated_utc']=now;s['running']=['E016 repairedv2 numericalsnapshot/demand funnel'];s['completed']=list(dict.fromkeys(s['completed']+['E017','E018']))
s['pending']=['Finish E016 compare-r2 andbothprofile diagnostic-v2; thenconditional3x2cleanv2confirmation','E019 bounded redundanthostplan suppression onlyafterE016funnel/confirmation','Further evidence-backed followups until08:15:51 consolidation; finalaudit/report/ownedcleanup']
s['next_exact_action']='Current samebinary OFF/unsafeON/PLEfencedON snapshot repaircompare-r2. Whenfinished, strictanalysis requiringfiles; then diagnostic-device-plan-ids-v2 bothprofiles. Do notspeedrunv1.'
s['last_stage']={'id':'E018','state':'COMPLETE_NEGATIVE_CONTENDED_TEMPORARY_SCHEME','updated_utc':now,'note':'Cheap nativeGPUgatepredictor16-19us; temporarywithinwindow swaps charge fullslots/serializedqueue/restoration. Verylittle ready-tail coverageat1.8GB/s; no liveimplementation ofthisspecificscheme justified. Persistent/higherhorizon notexhausted.'}
s['excluded']+=[{'path':str(ROOT/'experiments/E016-device-plan-ids/v1'),'reason':'UNSAFE_PLE_PRODUCER_DEPENDENCY: upstreamdeviceplan can bypasslayer0waitM, so pre(layer1) readsPLEbeforeCPUgathers. Real2GPUdelayedproducerfixture reproduces stalevsfresh. StableIDs alone insufficient. No headlinev1runsperformed.'},{'path':str(ROOT/'experiments/E016-device-plan-ids/compare-v1'),'reason':'INVALID_SNAPSHOT_CAPTURE: early per-layer/headfile writes failedbecauseparenttracesdir created onlybyendflush. Derivedv1PASS_REPAIR snapshotclaim withdrawn byanalysis-audit.json. Output/heatparity andnativefixture retained. Samebinarycompare-r2precreatesdirectory; strictmissingfileguard.'}]
save(ROOT/'STATUS.json',s)
(ROOT/'STATUS.md').write_text('# Research status\n\nUpdated '+now+'\n\nAbsolute deadline09:00:51UTC; consolidation08:15:51UTC.\n\nCompleted E001–E015, E017GPUrouter cost/availability, E018temporaryplacement feasibility. E013/E014falsification prevents claiming E010128gain as a portable isolated policy effect.\n\nE016: correctedv2 native/Python/realIQ tests pass apartfromknown environmentlimits;10/10greedyanswers identical tocontrol. Two source hazards diagnosed: shared-IDoverwrite and independentPLEproducerbarrier bypass. Unsafev1 retained andexcluded. Native delayedPLEfixture passes onbothGPUs.\n\nSnapshotcapture parentdir error preservedcompare-v1; repairedcompare-r2running withstrictrequiredfilevalidation. Thenbothprofilefullrouting/headdiagnostics beforecleanspeed.\n\nE017:16–19usGPUgatesignal,100%freshCPUgate membershipmatch. Five same-devicepairs only; realoutput/router/MTP/heat unchanged.\n\nE018: no live temporaryswap scheme justifiedatcontended1.8GB/s; fullcopy/restoration budget charged. No universalrouter orpersistentplacement impossibilityclaim.\n\nE019 predeclared butnotbuilt: suppress redundantalllocalCPUplans onlyafterE016v2confirmation.\n\nNext: '+s['next_exact_action']+'\n')
for v in ['device-plan-ids-v1','diagnostic-device-plan-ids-v1']:
 p=ROOT/'variants'/v/'README.md';text=p.read_text()
 notice='\nWARNING: preserved unsafe research version. Independent host PLE readiness is not fenced when GPU device planning skips the layer0 expert wait. Do not use for production or headline speed. See E016 native reproducer and separate correctedv2.\n'
 if 'Independent host PLE' not in text:p.write_text(text+notice)
with (ROOT/'experiments.jsonl').open('a') as f:
 import json
 for id,state in [('E017','COMPLETE_POSITIVE_SIGNAL_COST_NOT_LIVE_POLICY'),('E018','COMPLETE_NEGATIVE_CONTENDED_TEMPORARY_SCHEME'),('E016','RUNNING_REPAIR_PLE_AND_CAPTURE'),('E019','PLANNED')]:f.write(json.dumps({'id':id,'state':state,'updated_utc':now,'path':str(ROOT/'experiments'/next(p.name for p in (ROOT/'experiments').iterdir() if p.name.startswith(id+'-')))})+'\n')
print(now)
