"""Close the GPU signal/cost diagnostic without making a throughput claim."""
import csv,json
from lab import ROOT,load,save
out=ROOT/'experiments/E017-gpu-router';attempt=out/'v2';names=['32k','128k','dev-code','dev-math','cal-prose','hold-code','hold-structured','hold-math']
rows=[];parity=[]
for n in names:
 a=load(attempt/'analysis'/f'{n}.json');assert a['state']=='PASS'
 s=a['summary'];rows.append({'episode':n,'top10_precision_pct':s['top10_precision_pct'],'tail_recall_pct':s['nonlocal_recall_pct'],'warm_ready_tail_12_6_pct':s['warm_ready_nonlocal_recall_pct']['12.6'],'warm_ready_tail_1_8_pct':s['warm_ready_nonlocal_recall_pct']['1.8'],'score_publish_median_us':s['native_GPU_score_publish_us']['median'],'lead_median_us':s['warm_host_lead_us']['median'],'false_nonresident_proposals':s['false_nonresident_proposals'],'true_nonlocal_entries':s['true_nonlocal_entries'],'GPU_CPU_membership_agreement_pct':s['CPU_fullgate_top10_agreement_pct'],'raw':a['prefix']})
 parity.append({'episode':n,'parity':a['unchanged_math_parity'],'first_head':a['first_head']})
identity=load(attempt/'build/identity.json')
summary={'state':'COMPLETE_POSITIVE_SIGNAL_COST_NOT_LIVE_POLICY','question':'Does same-device native GPU gate projection become timely enough to deserve a transfer feasibility follow-up?','build':identity,'rows':rows,'correctness':parity,'explicit_new_GPU_bytes':[320,320],'mapped_CPU_bytes':[864,864],'new_expert_capacity':0,'boundary_24_to_25':'NOT_TESTED: requires charged crossGPUactivation/gate placement; no P2P assumed','disposition':'GPU projection16-19us fixes CPUcostblocker, but most same-windowtail readiness failsatcontended1.8GB/s. Complete bounded queue/victim/hybrid analysis beforeanylivepromotion. Does notcloseallrouterdirections.','scope':'Five same-device pairs, first64windows, two4096repositoryrequests +sixindependent1024development/holdouttasks. Fulloutputs/router/demand/heat unchanged. Diagnosticrates notheadline.'}
save(out/'summary.json',summary)
with (out/'summary.csv').open('w') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
text='# E017: native GPU next-gate signal\n\nThe bounded diagnostic passed: all actual output IDs, MTP windows, true router IDs, execution paths, initial/final heat and residency match the fresh control diagnostics. Both full benchmark first heads are bit-identical (KL0). The extra prediction never substitutes actual expert routing.\n\nThe existing BF16 GPU gate/top10/publication path costs16–19us median, versus hundreds of microseconds for the CPUfullgate. GPU and freshCPUfullgate predicted top10 memberships agree100% on these recorded activations. Five same-device pairs only;24→25 excluded.\n\n| Task | Precision% | Tailrecall% | Ready tail12.6GB/s% | Ready tail1.8GB/s% | Score/publishus | Leadus | False nonresident proposals |\n|---|---:|---:|---:|---:|---:|---:|---:|\n'
for r in rows:text+=f"| {r['episode']} | {r['top10_precision_pct']:.2f} | {r['tail_recall_pct']:.2f} | {r['warm_ready_tail_12_6_pct']:.2f} | {r['warm_ready_tail_1_8_pct']:.2f} | {r['score_publish_median_us']:.2f} | {r['lead_median_us']:.2f} | {r['false_nonresident_proposals']} |\n"
text+='\nThe readiness columns are optimistic independent one-blob estimates: ignore queuecompetition/fullslots/victims/inflightreaders, and use CPUobserved targetrouter time ratherthan an exactGPUdeadline. They are neither TGgains nor a feasible complete policy. Contended1.8GB/s leaves only0–7.14% ready-tail recall in this sample; isolated12.6GB/s often covers40–66%, so the CPUnegative alone was insufficient.\n\nMemory:320explicitGPUbytes/device,864mappedCPUbytes/device, no duplicate gate, reused expired current-logits scratch. CUDAallocation/eventinternal costs not assumedzero; actual VRAM telemetry retained. Expertphysicalclasses/capacities matchcontrolbothprofiles. No cleanthroughput measurement or instrumentationoverheadcertificate.\n\nRetained v1 build failure: duplicate GEMV widthargument. Separatev2 removes onlythatargument. Targeted13native tests and realIQparity pass.\n\nReproduce: `variants/diagnostic-gpu-router-v2/diagnose-profiles.sh` / `diagnose-episodes.sh`; originalattempts refuseoverwrite. Analysis: `scripts/analyze_gpu_router.py`, `analyze_gpu_router_episodes.py`, `consolidate_gpu_router.py`. Identity/rawrefs in summary.json.\n\nDecision: bounded queue/victim feasibility next; no unconditional fullgatepromotion/live winner claim.\n'
(out/'report.md').write_text(text)
print(json.dumps(rows[:2],indent=2))
