"""Finish the finite E009 replay and preserve its native/runtime decision."""
import csv
from lab import ROOT,load,save
out=ROOT/'experiments/E009-placement';rows=[]
for profile in ['32k','128k']:
    p=load(out/'v1'/profile/'replay.json');c=load(ROOT/'experiments/E004-replay/v6-corrected-peak'/f'{profile}-rate12p6/current.json')
    row={'profile':profile,'reference_nonlocal':c['nonlocal_entries'],'candidate_nonlocal':p['nonlocal_entries'],'nonlocal_delta_pct':100*(p['nonlocal_entries']/c['nonlocal_entries']-1),'reference_promotion_bytes':c['promotion_bytes'],'candidate_promotion_bytes':p['promotion_bytes'],'promotion_bytes_delta_pct':100*(p['promotion_bytes']/c['promotion_bytes']-1),'candidate_useful_promotion_bytes':p['useful_promotion_bytes'],'candidate_unused_promotion_bytes':p['unused_promotion_bytes'],'reference_victim_demand':c['victim_demand_while_absent'],'candidate_victim_demand':p['victim_demand_while_absent'],'modeled_wait_s':p['modeled_pending_wait_s'],'reference_modeled_wait_s':c['modeled_pending_wait_s'],'cross_layer_promotions':p['cross_layer_promotions'],'final_capacity':p['final_per_layer_capacity'],'resource_bytes_per_GPU':p['resource_bytes_per_GPU'],'physical_slot_wasted_bytes_per_promotion_sum':p['physical_slot_wasted_bytes_per_promotion_sum'],'raw':str(out/'v1'/profile/'replay.json')}
    rows.append(row)
save(out/'summary.json',{'state':'COMPLETE_POSITIVE','rows':rows,'scope':'One causal fixed-trace placement policy, both profiles, existing immutable physical size classes. No extraGPUbytes; changed per-layer share inside the same GPU. Positive means modest miss/byte reduction, not measured latency orTG.','limitations':['Heuristic greedy matching, not optimal variable-byte packing.','Nonpromotion execution/router/MTP trajectory held fixed.','Native selector cost and runtime correctness measured separately in E010; Python selector2.2-2.6s cannot be ignored as a deployment cost.','12.6GB/s cost envelope optimistic relative to contention sensitivity.'],'next':'Complete E010 same-base native candidate correctness and both-profile live confirmation, preserve negative outcome if observed.'})
with (out/'summary.csv').open('w') as stream:
    names=[k for k in rows[0] if k!='final_capacity'];writer=csv.DictWriter(stream,fieldnames=names,extrasaction='ignore');writer.writeheader();writer.writerows(rows)
lines=['# Compatible-slot placement replay','','Status: COMPLETE_POSITIVE for the predeclared replay objective.','','| Profile | Current nonlocals | Compatible nonlocals | Delta | Current promotion GB | Compatible promotion GB | Victim damage current/candidate |','|---|---:|---:|---:|---:|---:|---:|']
for r in rows:lines.append(f"| {r['profile']} | {r['reference_nonlocal']} | {r['candidate_nonlocal']} | {r['nonlocal_delta_pct']:.2f}% | {r['reference_promotion_bytes']/1e9:.3f} | {r['candidate_promotion_bytes']/1e9:.3f} | {r['reference_victim_demand']} / {r['candidate_victim_demand']} |")
lines+=['','The policy exchanges cold slots and hot incoming experts across layers only within one device. Incoming blobs must fit the actual physical slot. Both GPUs retain their exact own bytes, fixed K25 ownership and original asynchronous safe-publication queue. Per-layer capacity changes and wasted size slack are saved in summary.json. No assumption of a shared48GiB pool.','',
        'The decline in nonlocal entries and bytes is enough to justify one bounded actual native runtime experiment, E010. It is not a TG forecast. Copies and CPU/mapped/resident work compete in real inference; predictor/selector overhead and free-generation/MTP differences must be measured.','',
        'Source feasibility and constraints: v1/source-audit.md. Existing prompt loans restore the dynamic expert identity from host_res, but extra modes (resident CPU, mmap, elastic, helper, batch) are outside the bounded candidate and rejected. Wrong predictions always use original model-selected experts through safe fallback.','',
        'Exact C++/Python selector equivalence was checked across310/362adaptations in E010, with identical complete replay outcomes. Offline native selector median about0.786ms/call, including bridge temporary vectors. This materially exceeds the old selector cost and is charged as an uncertainty/risk, not hidden.','']
(out/'report.md').write_text('\n'.join(lines)+'\n');print(rows)
