"""Derived E008 report: same retained traces, explicit diagnostic cost limitations."""
import json, numpy as np
from lab import ROOT,load,save
from trace_reader import Trace
out=ROOT/'experiments/E008-router-boundary';rows=[];comparisons=[]
for profile,previous in [('32k','v5'),('128k','v5-portfix')]:
    a=load(out/'analysis-r2'/profile/'analysis.json')
    c=Trace(ROOT/'experiments/E003-diagnostics'/previous/profile/'traces/runtime-request2')
    d=Trace(out/'v2'/profile/'traces/runtime-request2')
    r=load(out/'v2'/profile/'raw/trace-run1.json');old=load(ROOT/'experiments/E003-diagnostics'/previous/profile/'raw/trace-run1.json');clean=load(ROOT/'experiments/E002-controls/v1'/profile/'raw/run1.json')
    comparisons.append({'profile':profile,'same_v5_v7_output_ids':bool(np.array_equal(c.output_ids,d.output_ids)),'same_v5_v7_expert_entries':bool(np.array_equal(c.entries,d.entries)),'same_v5_v7_window_tokens_T_acceptance':all(np.array_equal(c.windows[key],d.windows[key]) for key in ['tokens','T','accepted','produced']),'v5_TG':old['TG'],'v7_TG':r['TG'],'clean_TG':clean['TG'],'v7_vs_v5_TG_pct':100*(r['TG']/old['TG']-1),'v7_vs_clean_TG_pct':100*(r['TG']/clean['TG']-1),'cost_interpretation':'One serial diagnostic point each, no paired randomized overhead estimate or1% guarantee. Same output/branch/routing accounting supports mechanical comparability v5/v7. Clean output token IDs unavailable.'})
    for layer,q in a['router_quality'].items():
        rows.append({'profile':profile,'target_layer':int(layer),'precision_pct':q['top10_precision_pct'],'nonlocal_recall_pct':q['nonlocal_recall_pct'],'true_nonlocal_entries':q['true_nonlocal_entries'],'predicted_nonresident_entries':q['predicted_nonresident_entries'],'lead_median_us':q['lead_us']['median'],'score_median_us':q['batch_score_us']['median'],'warm_optimistic_ready_pct':100*q['warm_windows_only']['optimistic_ready_fraction']})
    save(out/'analysis-r2'/profile/'compact.json',{k:v for k,v in a.items() if k!='records'})
summary={'state':'COMPLETE_POSITIVE_DIAGNOSTIC','cpu_full_gate_candidate':'COMPLETE_NEGATIVE for the declared next-layer CPU calculation; most predictions are too late even under the optimistic one-blob test. This does not close GPU/low-rank/earlier-layer predictors.','router_rows':rows,'comparisons':comparisons,'timing_excluded':load(out/'analysis-r2/protocol.json'),'artifacts':{p:str(out/'analysis-r2'/p/'analysis.json') for p in ['32k','128k']},'failures':['v1 diagnostic load succeeded, warmup invalid because default-captured events were not observable. Preserved source/binary/logs and invalid request. Repaired with external event nodes; two-device graph reproducer and13targeted native tests pass.','Initial CPU scorer analyses were concurrent; their timing costs excluded. Serial analysis-r2 is authoritative; no new inference request was needed.'],'next':'Compatible-slot placement replay; targeted GPU wait diagnostics if needed to explain the CPU/mapped tail. Optional numeric same-input head comparison strengthens frequency correctness.'}
save(out/'summary.json',summary)
lines=['# Actual split handoff and causal router availability','',summary['state'],'',summary['cpu_full_gate_candidate'],'','| Profile | Next layer | Top10 precision | Nonlocal recall | True nonlocals | Predicted nonresidents | Lead median us | CPU score median us | Warm optimistic ready |','|---|---:|---:|---:|---:|---:|---:|---:|---:|']
for r in rows:lines.append(f"| {r['profile']} | {r['target_layer']} | {r['precision_pct']:.1f}% | {r['nonlocal_recall_pct']:.1f}% | {r['true_nonlocal_entries']} | {r['predicted_nonresident_entries']} | {r['lead_median_us']:.1f} | {r['score_median_us']:.1f} | {r['warm_optimistic_ready_pct']:.1f}% |")
lines+=['','Predictions use the current normalized MoE activation and the actual next BF16 gate. True next-router experts are labels only. First64windows and six chosen layer pairs are a bounded study of repository maintenance, with small rare-tail counts. No universal generalization claim.','',
        'The optimistic readiness check charges the measured single-thread CPU score/top10 cost and one weight blob at12.6GB/s with4.2uslaunch floor. It ignores multiple predicted blobs, victim selection and reader hazards; passing does not establish a feasible policy. Many predicted nonresidents are false positives, particularly layer47. Model math/routing never changed.','']
for p in ['32k','128k']:
    a=load(out/'analysis-r2'/p/'analysis.json');b=a['boundary_timings']
    lines.append(f"{p}: actual GPU0 outgoing-copy median {b['0']['11']['gpu_elapsed_us']['median']:.3f}us; GPU1 incoming-copy median {b['1']['10']['gpu_elapsed_us']['median']:.3f}us. Host transition median {a['host_stage_transition_gap_us']['median']:.3f}us. GPU0 tail-sync median {b['0']['2']['host_elapsed_us']['median']:.3f}us; GPU1 tail-sync median {b['1']['2']['host_elapsed_us']['median']:.3f}us.")
lines+=['','These are event-bracket durations on each GPU, plus separate CPU observations. The two transfer medians are not summed into a claimed measured boundary total. GPU1 tail-sync includes head/dense/resident/KV work and cannot be labeled transfer or miss cost. No direct subtraction of cross-device clocks.','',
        'Instrumentation is not a headline binary. Same diagnostic v5/v7 output IDs, branches and expert entries are recorded in summary.json; observed TG changes are not a guaranteed overhead bound. External graph events, activation copies and first-head logit copies add diagnostic work.','',
        'First-window248320-vocabulary logits are finite at both profiles. Only the same-input comparison may be interpreted as numerical parity; free-generated later heads are not teacher-forced comparisons.','',*summary['failures'],'',summary['next']]
(out/'report.md').write_text('\n'.join(lines)+'\n')
print(comparisons)
