"""Freeze exactly one baseline after measured confirmation and safety review."""
import hashlib
from lab import ROOT,load,save
base=ROOT/'experiments/E027-pool-baseline';s=load(base/'summary.json');p0=load(ROOT/'experiments/E026-pool-generalization/summary.json');safe=load(base/'safety/summary.json')
assert s['state']=='COMPLETE_MEASUREMENTS' and len(s['paired'])==6 and safe['state']=='PASS'
assert all(p['both_fixed_length_valid'] and p['same_actual_output_IDs'] and p['same_MTP'] and p['same_normal_routing'] and p['same_capacity'] for p in s['paired'])
s.update(state='COMPLETE_FROZEN_BASELINE',decision='FIXED100US',selected_variant='p1-baseline',safety=str(base/'safety/summary.json'),independent_confirmation_reused=str(ROOT/'experiments/E026-pool-generalization/summary.json'),scope='Same frozen CURRENT runtime with100us; no adaptive synchronization changes justified by P0')
save(base/'summary.json',s)
cfg={p:load(ROOT/'variants/p1-baseline'/(p+'.json')) for p in ['32k','128k']}
save(base/'frozen-baseline.json',{'state':'FROZEN','variant':'p1-baseline','profiles':cfg,'config_sha256':{p:hashlib.sha256((ROOT/'variants/p1-baseline'/(p+'.json')).read_bytes()).hexdigest() for p in cfg},'source_unchanged':True,'selected_pool_policy':'existing STRATA_POOL_SPIN_US=100','normal_controls_for_P2':'p1-baseline only','frontend_source_commit':'See campaign Git history; identical wrapper in all comparisons'})
text=(base/'report.md').read_text().replace('State: COMPLETE_MEASUREMENTS. Decision pending wait diagnostics and paired review.','State: COMPLETE_FROZEN_BASELINE. Selected policy: **fixed100us**, unchanged CURRENT binary.')
text+='\n## Independent confirmation and policy selection\n\nReused the complete E026 independent code/math/prose matrix at both profiles; no unchanged point repeated. All three32K workload families improve latency, code/prose128K improve, math128K is neutral. CPU-positive completion costs increase, but no serious consistent request regression was observed. A new adaptive synchronization policy is not justified by these data. No dense/coarse threshold sweep performed.\n\n'
text+='## Safety and scheduling mechanism\n\nTargeted test:8000batches/67200jobs across default/100us, including32-job worker bursts, zero-job periods,120/800us gaps,25ms idle periods and eight construction/destruction cycles perpolicy. Every output element finite and exactlyzero forzero immutable weights, watchdog/nohang/nojobloss. Existing random0–4job stress40s total and real nativeIQ layers0/1/2/12 passed. Exact commands/logs/source and standalone test binary hashes are in safety/. Existing seq_cst epoch/sleepers/CV protocol is unchanged; this finite stress is not a proof over all interleavings.\n\n'
text+='P0 event traces additionally preserved every outputID, routerID, path, cache/heat state, slot-byte class and first-head bit atbothprofiles (diagnostic-v1/*/strict-parity.json). Clean pairedP1 checks preserve output/MTP/normalrouting. Prior full suite limitations remain: four existing missingfixture/VMmlock failures, not newly repaired or hidden.\n\n'
text+='## Usable baseline\n\nNo source rebuild, new weights or capacity change. Source `'+cfg['32k']['source_sha']+'`; binarySHA `'+cfg['32k']['binary_sha256']+'`. K25/pcie.28/workers15/spec4/minp.5/INT8/prefillauto/suffix0/promptcache0; max32768 or131072, KVresident32768 wherevalid.\n\n'
for p in ['32k','128k']:text+='```bash\n'+str(ROOT/'variants/p1-baseline'/('start-'+p+'.sh'))+' --host 0.0.0.0 --port 8080\n```\n\n'
text+='Stop: `'+str(ROOT/'variants/p1-baseline/stop.sh')+'`. Only one server at a time. Research launcher prints/verifies frozen config and owns PID identity; original normal user launchers remain unchanged. Default bind remains127.0.0.1; explicithost override changes no inference settings. Later replay: `reproduce.sh --experiment NEW_EXPERIMENT --attempt v1 --reproduction` after campaign completion; refuses overwrite and active-campaign deadline bypass.\n\n'
text+='P2 may now begin using **p1-baseline as its only normal control**. A new policy OFF build must reproduce mathematics/capacity and be measured separately if binary layout differs.\n'
(base/'report.md').write_text(text)
(ROOT/'variants/p1-baseline/README.md').write_text('# Frozen P1 real-prompt baseline\n\n'+text.split('## Usable baseline',1)[1])
print('P1_FROZEN_FIXED100US',flush=True)
