from lab import ROOT,load,save
import subprocess
base=ROOT/'experiments/E028-persistent-replay';r=load(base/'replay-summary.json');r['state']='COMPLETE_P2A_REPLAY';r['decision']='Conservative candidate v1 is a traffic/nonlocal tradeoff, not an inferred win. Live diagnostic screening required; excessive nonlocals motivate at most one evidence-based repair if live confirms CPU cost.';r['cells']=[];save(base/'summary.json',r)
s='# E028 persistent same-device admission replay\n\nCompleted before live headline execution. This is fixed-trajectory simulation, not measured TG. P1 full4K traces have exact baseline output/MTP/routing parity. Horizon8 was selected in E020. Alpha1.0 selected from first64windows of three development episodes before fulltrace ranking.\n\n| Context | Link model GB/s | Current nonlocals | Persistent nonlocals | Current GB copied | Persistent GB | Current wait s | Persistent wait s | Useful / total | Repeated | Victim entries |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n'
for x in r['rows']:s+=f'| {x["profile"]} | {x["rate"]} | {x["current_nonlocal"]} | {x["persistent_nonlocal"]} | {x["current_bytes"]/1e9:.3f} | {x["persistent_bytes"]/1e9:.3f} | {x["current_wait"]:.3f} | {x["persistent_wait"]:.3f} | {x["useful"]}/{x["promotions"]} | {x["repeated"]} | {x["victim_damage"]} |\n'
s+='\nThe lifetime mechanism works in replay: almost all admissions get repeated subsequent uses, physical ownership/capacity invariants hold, no restoration. The conservative 16window/80us utility suppresses many useful lowheat admissions and raises nonlocals 3.6–4.7x. Large modeled copy savings cannot establish speed because CPU/mapped execution costs stay fixed in replay. Live screening will measure this tradeoff; this candidate is NOT promoted to production.\n\nThe transfer sensitivity changes queue charges only; admission uses the same conservative1.8GB/s cost. Fixed trajectory does not model altered FP path/MTP/output. Prediction arrival is observed before endverify, but copies issue only at the safe boundary after current target demands: currentwindow late opportunities are not counted as early hits. Copycompletion and nextwindow publication are separate. Initial age/history is unknown except warmup heat; no invented history. Selector offline CPU is measured but not charged to synthetic TG; no TG predicted.\n\nArtifacts: `policy-v1.json`, `selected-policy.json`, `development-v1/`, `full-v1/`, `selector-tests/`, `signal-v1/` (fullparity checks). The development view is deliberately limited to64windows because original signals stop there. The replay keeps immutable RAM canonical and original variable-byte physical slots separately on each GPU.\n'
(base/'report.md').write_text(s)
subprocess.run([str(ROOT/'src/control/.venv/bin/python'),'scripts/followup_state.py','E028-persistent-replay','COMPLETE_P2A_REPLAY','--next','E029 persistent runtime: build, correctness, OFFguard, then one32K screening before deciding live confirmation/repair.','--note','Replay completed; strong traffic reduction but more CPU/mapped misses. No TG claim. P1 remains production baseline.'],cwd=ROOT,check=True)
subprocess.run([str(ROOT/'src/control/.venv/bin/python'),'scripts/render_pool_followup.py'],cwd=ROOT,check=True)
