"""Complete bounded P2; distinguish correctness, mechanism, negative performance and future space."""
from lab import ROOT,load,save
import subprocess,statistics,pathlib,datetime
base=ROOT/'experiments/E029-persistent-runtime';py=str(ROOT/'src/control/.venv/bin/python')
assert load(base/'v2-fixed/run_persistent_v2_final-driver/command.json')['returncode']==0
subprocess.run([py,'scripts/analyze_persistent_live.py'],cwd=ROOT,check=True);subprocess.run([py,'scripts/check_persistent_final_fairness.py'],cwd=ROOT,check=True);subprocess.run([py,'scripts/analyze_persistent_diagnostic.py'],cwd=ROOT,check=True)
r=load(base/'summary.json');assert r['state']=='COMPLETE_MEASUREMENTS';r.update(state='COMPLETE_BOUNDED_PERSISTENT_RESIDENCY',decision='Pendingfinalpairedassessment; P1remainsreference unlessmeaningfulbothcontextlatency/TGwin.',correctness=load(base/'v2-fixed/correctness/paired-summary.json'),byte_audit=load(base/'v2-fixed/byte-audit/summary.json'),fairness=load(base/'v2-fixed/fairness-audit.json'),copy_diagnostic=load(base/'analysis/copy-diagnostic.json'),screen_negative=load(base/'v1-fixed/screen-analysis.json'))
# Recommendation based on completed end-to-end numbers; never cachehit alone.
def cell(p,role):return next(x for x in r['cells'] if x['profile']==p and x['role']==role)
comparisons=[]
for p in ['32k','128k']:
 a,b=cell(p,'off'),cell(p,'on');comparisons.append({'profile':p,'TG_delta_medians_pct':100*(b['metrics']['TG']['median']/a['metrics']['TG']['median']-1),'wall_delta_medians_pct':100*(b['metrics']['wall_s']['median']/a['metrics']['wall_s']['median']-1),'paired_delta_TG_median_pct':statistics.median(x['TG_delta_pct'] for x in r['paired'] if x['profile']==p),'paired_delta_wall_median_pct':statistics.median(x['wall_delta_pct'] for x in r['paired'] if x['profile']==p)})
r['comparisons']=comparisons;r['decision']='USE_PERSISTENT_RESIDENCY' if all(x['TG_delta_medians_pct']>5 and x['wall_delta_medians_pct']<-3 for x in comparisons) else 'USE_P1_BASELINE';save(base/'summary.json',r)
s='# E029: live persistent admission on P1 baseline\n\nState: '+r['state']+'. Decision: '+r['decision']+'. Frozen samebinaryOFF/ON, identicalactualinput/settings/capacities, zero reuse, suffixOFF, warm64out,3fresh measuredstarts/point,4096output.\n\n'
s+='| Profile | Role | PP median | TG min/median/max | TTFTs | Walls | MTPaccept% | CPUentries | PCIeentries | VMCPUdecode% | GPU0% | GPU1% |\n|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n'
for c in r['cells']:
 def m(k,fmt='.1f'):
  v=c['metrics'][k];return format(v['median'],fmt) if v else 'unavailable'
 t=c['metrics']['TG'];s+=f'| {c["profile"]} | {c["role"]} | {m("PP")} | {t["min"]:.1f}/{t["median"]:.1f}/{t["max"]:.1f} | {m("TTFT_s",".3f")} | {m("wall_s",".3f")} | {m("mtp_acceptance_pct")} | {m("cpu_fallback_entries",".0f")} | {m("offloaded_entries",".0f")} | {m("CPU_VM_decode_mean_pct")} | {m("GPU0_util_decode_mean")} | {m("GPU1_util_decode_mean")} |\n'
s+='\n| Profile | Admissions | CopiedGB | Useful | Repeated | Wasted | Ready | Late | Victim entries | Selector ms | Pending ms |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n'
for p in ['32k','128k']:
 c=cell(p,'on');v=lambda k:c['metrics']['residency_'+k]['median'];s+=f'| {p} | {v("promotions"):.0f} | {v("bytes")/1e9:.3f} | {v("useful"):.0f} | {v("repeated"):.0f} | {v("wasted"):.0f} | {v("ready"):.0f} | {v("late"):.0f} | {v("victim_entries"):.0f} | {v("selector_ms"):.3f} | {v("pending_ms"):.3f} |\n'
s+='\nAllheadlinemedian raw paths in summary.json/CSV. Diagnostic runs/screen are separate and never pooled into3-runmedians. Experimentalcode frozen: `'+r['cells'][0]['source']+'`, binary SHA `'+r['cells'][0]['binary']+'`. Patch/buildcommandsv2-fixed/build/. P1controlsource6f32... untouched. Sourceblockedfloatv1 andpatchanchorv2 are preserved, zeroheadlinerequests onbrokenversions.\n\n'
s+='Correctness is scoped: 10savedgreedyprompts, finiteheads andexplicitmath/JSON checks; output IDsdiffs preserved; immutableRAM/GPUreadback1793/2472experts3.609/4.949GBmatchesexactly. Sharedselector/state testsandnative suite62PASS/2SKIP, v2targeted15PASS. No generalqualityjudgment or bit-parity claim underchangedCPU/GPUplacement.\n\nThe persistent mechanism is implemented, not temporaryswap/restore. H8existingnativeGPUgate/top10 plusobservedEMA/recency/age, approximateavoidedmissutility chargedbyactualblobbytes, distinctsameGPUphysicalslots, asyncsafe-boundarycopies andevent-gatedpublication. Promotedweights remainresident acrossfutureuses. Maps/bytes/ownershipreservations audited. No global48GiBcache, noP2P, no remoteexecution, no mathematicalexpertsubstitution.\n\n'+ '\n'.join(r['limits'])+'\n\n'
s+='## Copy mechanism diagnostics\n\nOnlyseparatev2-diagnostic binary, eachprofileone4Kdiagnostic. Actualcompletion observation/promotionCSVaftertimer; no per-tokenI/O. ExactGPUcopycompletiontime unavailable, publication checkedcompletion upperbound. Hostenqueue/staging/copycalls, exposedadaptthreadjoin, publicationpending waits measuredseparately; phasesoverlap and mustnotbesummed into inventedcausalTG. Detailandtrajectoryparity in analysis/copy-diagnostic.json.\n\n'
for x in r['copy_diagnostic']['rows']:s+=f'- {x["profile"]}: {x["state"]}; enqueue{ x["diagnostic_stats"].get("enqueue_ms")}ms, join{x["diagnostic_stats"].get("join_ms")}ms, pending{x["diagnostic_stats"].get("pending_ms")}ms.\n'
s+='\n## Limits and convergence\n\nCurrentwarmchainreplay nonlocals73,926/79,719 vscurrent36,776/45,276, copied3.941/4.809GB vs10.697/14.373GB. Lifetime amortizationexists, butfewerbytesdoesnotimplylowercriticalpath latency; moreCPU/mappedexpertwork andchangedFP/freegeneration/MTP canoffsetcopygain. Conservativev1screen142.7vs179.7TG,18.9%longerwall rejected; onepredeclaredv2repair completed3repbothprofiles. No tuninguntilfavorable outcome.\n\nP2doesnotexhaustpersistentpolicyspace. Signalonly5targetlayers, uncalibratedh8confidence, approximateperentryutility andboundary-onlyissue. E004futureoracle headroom isnotdeployableprediction/latencygain. Strongerfuturework: broadercausalprediction/lifetimeutility withmeasuredexposedcost andsafe earlierdevice/queue-controlledpromotion; requiresnewresearch, not silentlycontinuednow. NooptionalcrossGPUredesign neededforthisboundedconclusion.\n'
(base/'report.md').write_text(s)
subprocess.run([py,'scripts/followup_state.py','E029-persistent-runtime','COMPLETE_BOUNDED_PERSISTENT_RESIDENCY','--next','Consolidatefinalreports/reproducibility/launchindex, stopallownedprocesses andverifybothGPUfree. No newexperimentalbranch.','--note','P0/P1/P2complete withinboundedprotocol; allnegative/invalidbuildattemptspreserved. Finalrecommendation '+r['decision']],cwd=ROOT,check=True)
subprocess.run([py,'scripts/render_pool_followup.py'],cwd=ROOT,check=True)
print(r['decision'],comparisons,flush=True)
