"""Render frozen interpretation and all paired evidence; never select or rerun timings."""
import statistics
from common import *
def median(d):return d['median'] if d else None
def num(x,n=2):return 'unknown' if x is None else f'{x:.{n}f}'
def mtable(headers,rows):return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(map(str,r))+' |' for r in rows])+'\n\n'
if __name__=='__main__':
 summary=load(C/'results/main-summary.json');runs=load(C/'results/live-attempts.json');pairs=load(C/'results/paired-blocks.json');decision=load(C/'configs/conclusion.json');identity=load(C/'configs/runtime-identity.json');guard=load(C/'tests/development-guard.json');existing=load(C/'results/existing-data-analysis.json')['rows'];clock=load(C/'clock.json');elapsed=time.monotonic()-clock['start_monotonic_s'];texts=[]
 texts.append('# Golden Swap Phase 3: planner work and dependent GPU waits\n\n**'+decision['primary']+'**\n\n'+decision['summary']+'\n\n')
 texts.append(f'{len([r for r in runs if r["kind"]=="main"])}/36 valid primary requests; {len([r for r in runs if r["kind"]=="independent"])}/6 valid independent-source replays. Start {clock["start_utc"]}; immutable deadline {clock["deadline_utc"]}; regeneration elapsed {elapsed/60:.2f} minutes. Source `{identity["source_sha"]}`; binary SHA256 `{identity["binary_sha256"]}`. Frozen Phase 2 source `{identity["phase2"]["source_sha"]}` / binary `{identity["phase2"]["binary_sha256"]}`; logistic `{identity["checkpoint_sha256"]}`. Pinned upstream base 6f32ec070f23ced9f50e704d854d775da52591ab, Qwen revision 38bb39ee97821de2c9009abb7e93950eec396e66; dependency/config/patch identities retained.\n\n')
 texts.append('This is conditional fixed-work oracle-incoming replay with causal history victims, minimum first-use TC and privileged current-window protection. All main/MTP routing, coefficients, required expert computation and initial state stay fixed. CPU/GPU arithmetic may differ: forced output/work fingerprints do not establish natural-generation quality or bitwise mathematical equivalence. Q4/K24/PCIe0.28/pool100us/15workers/MTP4minp0.5/INT8KV/prefillauto/reuseOFF and ordinary serving remain unchanged. Five charged spares 17,305,600 B remain inside existing capacity.\n\n')
 texts.append('## Existing evidence, before new inference\n\nPhase 1/2 established premature eviction before first target/use as the original unused-copy mechanism, minimum TC removed it, post-use 48 lost useful service, inactive risk thresholds did not change actions, and no confirmed learned-scorer advantage existed. These are prior results, not new Phase 3 measurements. Phase 3 read 56 prior complete journals without modifying previous campaigns.\n\n')
 er=[]
 for task in ['code-archive','math-inventory','text-websocket','mixed-chinook','text-json-rfc8259']:
  rr=[r for r in existing if r['task']==task and r['arm']=='ORACLE_IN_HISTORY_TC']
  er.append([task,rr[0]['input'],rr[0]['output'],rr[0]['windows'],num(statistics.median(r['publication_to_first_use']['median'] for r in rr),1),num(statistics.median(r['resident_lifetime_evicted']['median'] for r in rr),1),num(statistics.median(r['distinct_uses']['median'] for r in rr),1),num(statistics.median(r['avoided_entries_per_GB'] for r in rr),1),num(statistics.median(r['late'] for r in rr),1)])
 texts.append(mtable(['Task','Input','Output','Windows','First-use distance invocations','Evicted lifetime invocations','Distinct uses/admission','Avoided entries/GB','Late publications'],er))
 texts.append('Inventory/Chinook had more repeated service than Archive/WebSocket; Chinook had the highest avoided lane demand per copied byte. Late publication was rare in all four, so missed target timing alone does not explain the prior task split. Input/context lengths also differ greatly: WebSocket is near32K while Inventory is165 tokens. These four trajectories cannot establish a universal domain classifier. Survivors are right-censored; evicted lifetime distributions are separate from survivor ages. See existing-data-analysis.json for all per-run queue/stage/copy/slack/return distributions and phase0-reuse-reference.json for retained batch reuse/burst definitions. Missing exact DMA duration, native intended target, GPU absolute clock alignment and exact prevented-admission identity are explicit.\n\n')
 texts.append('## Optimization and logical parity\n\nThe whole negative admission decision depends on dynamic ownership, protection, history, queue state and the timing-derived lead. It is unsafe to memoize it as one value. The chosen smaller intervention caches only immutable incoming `(next target, lane count over768 invocations)` until the exact next lower occurrence leaves or upper occurrence enters. E64 enumeration and all mutable policy checks remain intact. Cache 491,520 B is charged in host state for all arms; preparation/request reset, rewind and exact lower/upper invalidations are counted. Full incoming only; finite-information views use the original path. No new victim-future queries, score features or weights.\n\n')
 texts.append('26 deterministic OFF/ON task/scorer pairs cover all 12 corpus tapes plus existing RFC8259. Every evaluated candidate outcome/NO_SWAP hash, complete lifecycle bytes, logical admission payload/order/ownership and required work match.16 inherited development/calibration OFF points also match retained Phase 2 results. The dense cache fixture checks 491,520 exact reference queries, same-event policy-state changes, boundary additions/removals, rewinds and finite-horizon fallback. Native safety/ownership and 9 targeted tests passed; logistic 4,000 predictions/prefix 300 batches retain maximum errors 1.32e-7/1.18e-7.\n\n')
 texts.append('The deterministic model fixes physical cadence. Live copies can become ready at different milestones and the inherited lead depends on measured copy/event timing. Live logical admission traces are therefore compared and reported, never claimed identical solely because aggregate work matches. All live requests must separately pass actual publication/slot/generation/work checks. See paired-blocks.json and the live-trajectory diagnostic for the first divergence and unchanged source dependencies.\n\n')
 texts.append('## Timer semantics and instrumentation guard\n\nPlan A is actual verifier-stream time spinning for the host-published GPU plan, measured inside the existing one-thread kernel with GPU globaltimer. Mapped B and CPU flags are separate later waits. No extra kernel launch or per-layer synchronization; request-end48B/device readback/reset is charged to whole wall after existing commit. Logical metadata96B total plus allocator granularity appears in VRAM telemetry; expert capacity is attested unchanged. Ready-flag floor in fixture0/1024ns;20ms blocking fixture passed on both GPUs. Device-plan skip paths are not profiled and remain disabled in the frozen configuration.\n\nHost thread CPU measures the oracle host hook, excludes other copy workers; planner wall includes nested selection and publication acknowledgment waits. Victim selection wraps resident enumeration; feature/model work also includes separate reserve/guard scorer calls. GPU wait A can overlap shared/peer useful work; its sum is observed blocked dependency time and an upper bound on its isolated whole-request exposure, not additive exclusive latency. No cross-device absolute clock or sum of nested counters is used as exact stall. Current hook CPU is not full native planner CPU; host-plan journal includes native assembly, while adaptation outside it remains unassigned.\n\n')
 texts.append(mtable(['Instrumentation pair','Profile ON/OFF decode change %','Completion wall change %'],[[str(i+1),num(p['decode_change_pct']),num(p['wall_change_pct'])] for i,p in enumerate(guard['instrumentation_pairs'])]))
 texts.append(f'Two opposite-order development pairs did not trigger the predeclared >3% regression-in-both-pairs gate; this small N does not prove zero instrumentation cost. Frozen Phase 2 development decode{guard["frozen_phase2_decode_s"]:.4f}s; new unprofiled OFF{guard["new_unprofiled_OFF_decode_s"]}. Separate binary observation is behavioral/overhead sanity, not a headline stale control. Main arms share one binary and identical enabled wait instrumentation.\n\n')
 texts.append('## Complete contemporaneous matrix\n\nFour exposed fixed regression tapes x3 arms x3 counterbalanced adjacent blocks, seed 730071; RFC8259 x2 reversed blocks. Fresh server, saved 4096-input/64-output warmup, native prefill, exact recorded initial state, common tape/index setup and complete tape execution. Real copies, final commit/drain/restoration, readback, attestation and flush remain charged. Startup/warmup/shutdown are separate. WebSocket emits 1773, not 2048. RFC8259 is previously evaluated independent source, not a fresh holdout. Main inputs/outputs/windows/context occupancies are given in input-manifest.json.\n\n')
 primary=[]
 for s in summary:
  for arm,z in s['arms'].items():
   a=z['metrics'];primary.append([s['task'],arm,f'{z["valid"]}/{z["attempts"]}', '/'.join(num(a['tok_s'][k]) for k in ['min','median','max']),num(a['decode_s']['median'],4),num(a['wall_s']['median'],4),num(a['local_pct']['median']),f'{a["cpu"]["median"]:.0f}/{a["mapped"]["median"]:.0f}',num(a['copy_GB']['median'],3),num(z['oracle']['planner_ms']['median'],1),num(z['planner']['host_cpu_ms']['median'],1),num(a['gpu_plan_wait_ms']['median'],1)])
 texts.append(mtable(['Task','Arm','Valid/attempts','Replay tok/s min/median/max','Decode median s','Completion wall median s','Local %','CPU/mapped entries','Copy GB','Oracle hook wall ms','Hook CPU ms','GPU plan A wait ms'],primary))
 texts.append('Copy GB includes completed ordinary payload plus mandatory restoration; sampled readback/metadata traffic is separate and charged in wall. Exact transaction partitions and reload/absence data are in live-attempts.json, not inferred from independent medians.\n\n')
 outcomes=[]; scans=[]
 for s in summary:
  for arm in ['PLANNER_BASELINE','PLANNER_OPT','REPLAY_CURRENT']:
   rr=[r for r in runs if r['task']==s['task'] and r['arm']==arm]
   keys=['published_used_before_eviction','published_evicted_without_use','published_no_use_resident_at_end','completed_unpublished']
   amounts=[sum(r['transactions']['partition'][key]['bytes'] for r in rr) for key in keys]
   completed=sum(r['transactions']['completed_bytes'] for r in rr);assert sum(amounts)==completed
   outcomes.append([s['task'],arm,len(rr),sum(r['transactions']['reconciled_generations'] for r in rr),num(completed/1e9,4),*[num(v/1e9,4) for v in amounts],num(sum(r['restoration_bytes'] for r in rr)/1e9,4),sum(r['victims']['chronological_victim_reloads'] for r in rr),sum(r['victims']['victim_absent_entries'] for r in rr)])
   scans.append([s['task'],arm,num(statistics.median(r['tc']['enumeration_ms'] for r in rr),1),num(statistics.median(r['score']['selection_ms'] for r in rr),1),num(statistics.median(r['oracle']['publication_ms'] for r in rr),1),int(statistics.median(r['planner']['opportunities'] for r in rr)),int(statistics.median(r['tc']['cost_veto'] for r in rr)),int(statistics.median(r['tc']['capacity_veto'] for r in rr)),int(statistics.median(r['tc']['risk_veto'] for r in rr))])
 texts.append('### Reconciled ordinary transaction outcomes\n\nThese are exact sums across the stated attempts, after per-run generation reconciliation; restoration is separate. Native completion is certified by publication, and any unpublished native completion remains explicitly unknown in the per-run records.\n\n')
 texts.append(mtable(['Task','Arm','N','Generations','Completed GB','Published used GB','Unused evicted GB','No-use-yet end GB','Completed unpublished GB','Restoration GB','Chronological reloads','Victim-absent entries'],outcomes))
 texts.append('### Planner and guard work\n\nMedian per-run timers are nested: victim selection wraps its resident-enumeration loop; feature/model work is inside scorer calls during enumeration and also reserve/guard calls. Publication coordination is inside the oracle hook. Incoming candidate enumeration is not the resident-enumeration timer. These counters are not additive stall. Repeated logical veto opportunities remain intentional even when their expensive immutable query results are reused.\n\n')
 texts.append(mtable(['Task','Arm','Enumeration ms','Selection ms','Publication ms','Candidate opportunities','Incoming-cost veto','Capacity veto','Risk veto'],scans))
 paired=[]
 for s in summary:
  p=s['paired'];paired.append([s['task'],s['blocks'],'/'.join(num(p['decode_OPT_BASE_pct'][k]) for k in ['min','median','max']),'/'.join(num(p['wall_OPT_BASE_pct'][k]) for k in ['min','median','max']),str(s['block_signs']['decode_OPT_BASE_pct']),str(s['block_signs']['wall_OPT_BASE_pct']),num(p['BASE_CURRENT_decode_pct']['median']),num(p['OPT_CURRENT_decode_pct']['median']),num(p['BASE_CURRENT_wall_pct']['median']),num(p['OPT_CURRENT_wall_pct']['median']),s['optimization_gain_criterion'],s['baseline_vs_current_criterion'],s['optimized_vs_current_criterion']])
 texts.append(mtable(['Task','Blocks','OPT/BASE decode % min/median/max','OPT/BASE wall % min/median/max','Decode gain signs','Wall gain signs','BASE/CURRENT decode %','OPT/CURRENT decode %','BASE/CURRENT wall %','OPT/CURRENT wall %','Optimization criterion','BASE/current criterion','OPT/current criterion'],paired))
 texts.append('Negative time changes are gains. Criterion frozen before main outcomes: median decode-time reduction>3%, faster in>=2/3 main blocks, median wall regression<=1%, and fewer than2 blocks with>3% wall regression. IndependentN2 is descriptive and not evaluated as a three-block criterion. Pair ratios retain shared-reference correlation; three repeats are not independent task generalization. All raw/slow observations are retained without CPU-steal correction.\n\n')
 mechanism=[]
 for s in summary:
  p=s['paired'];mechanism.append([s['task'],num(p['cache_recompute_reduction_pct']['median']),num(p['planner_cpu_removed_ms']['median'],1),num(p['planner_wall_removed_ms']['median'],1),num(p['gpu_plan_wait_removed_ms']['median'],1),s['blocks']])
 texts.append(mtable(['Task','Incoming recomputation removed %','Hook CPU removed ms','Hook wall removed ms','Plan A wait removed ms','Pairs'],mechanism))
 texts.append('Targeted evaluation means the expensive incoming next/count query pair. Candidate opportunities, cost-floor comparisons and logical veto scans continue, preserving policy coverage. Do not claim that all candidate enumeration disappeared. Cache lookups/hits/misses/invalidations and optional diagnostic lookup/recompute-maintenance timer are retained; maintenance timing is gated OFF for headline runs, so its zero counter means unmeasured, not free.\n\n'+decision['critical_path_interpretation']+'\n\n')
 texts.append('## Independent continuous-tail check\n\nRFC8259 uses 2699 input+2816 output, 949 verifier windows and 5515 committed context positions within 32768. Measured main boundary 2048 output/705 windows has 768 observed continuation tokens in the same request; all arms execute the complete tape.\n\n')
 ind=[]
 for r in runs:
  if r['kind']=='independent':ind.append([r['block'],r['arm'],num(r['prefix_observation_span_s'],4),num(r['prefix_tok_s']),num(r['decode_s'],4),num(r['wall_s'],4),r['transactions']['prefix']['no_use_yet_resident_bytes'],r['transactions']['prefix']['later_observed_use_bytes'],r['transactions']['prefix']['no_observed_tail_use_bytes']])
 texts.append(mtable(['Block','Arm','Prefix observation span s','Prefix tok/s','Whole decode s','Whole wall s','Unused prefix survivor B','Later-used B','No observed tail use B'],ind))
 texts.append('Prefix observation spans are a separately defined boundary readout, not the native full-decode metric. Tail completion and mandatory work remain charged. No tail nonuse proves permanent nonuse. See paired results for the actual small N transfer check.\n\n')
 texts.append('## Resources, repairs and limitations\n\nBoth devices VRAM/utilization/power/clocks/temperature/memory clocks/PCIe link generation and width, host RAM/swap, process CPU and steal are retained per request. No host changes, no overlapping compilation/training/heavy analysis during headline requests. Peak/resources and distribution fields are in live-attempts.json and complete telemetry gzip copies. Sampling does not identify DMA-only saturation.\n\n')
 resource_rows=[];phase_resources=load(C/'results/phase-resource-diagnostics.json')
 for s in summary:
  for arm in ['PLANNER_BASELINE','PLANNER_OPT','REPLAY_CURRENT']:
   rr=[r['phases']['run'] for r in phase_resources if r['task']==s['task'] and r['arm']==arm]
   def med_of_medians(key):return statistics.median(r[key]['median'] for r in rr if r[key])
   def gpu_peak(device,key):return max(r['gpus'][str(device)][key]['max'] for r in rr if r['gpus'][str(device)][key])
   resource_rows.append([s['task'],arm,num(med_of_medians('CPU_pct')),num(med_of_medians('steal_pct')),num(max(r['steal_pct']['max'] for r in rr)),num(max(r['process_RSS_GiB']['max'] for r in rr)),f'{gpu_peak(0,"vram_mib"):.0f}/{gpu_peak(1,"vram_mib"):.0f}',f'{gpu_peak(0,"power_w"):.1f}/{gpu_peak(1,"power_w"):.1f}'])
 texts.append('Request-phase telemetry below includes prefill/decode/completion, separated from startup/warmup in phase-resource-diagnostics.json. CPU/steal columns are medians of per-run sampled medians; peaks are maxima across those run samples, not pooled medians or exclusive decode attribution.\n\n')
 texts.append(mtable(['Task','Arm','System CPU %','Steal %','Peak steal %','Peak process RSS GiB','Peak VRAM MiB GPU0/1','Peak power W GPU0/1'],resource_rows))
 texts.append('The unusually fast RFC8259 OPT block1 has request-phase sampled median steal 0.8%, versus 8.0% for its baseline; block2 OPT has 8.2%, versus 4.6% baseline. Chinook block3 baseline/OPT/current have 6.35%/2.8%/0.6%. These are measured confounders, not an exclusive explanation or a correction factor. GPU0 sampled median SM clock was 2790 MHz in these requests. All observations remain in the comparisons, including the large improvements.\n\n')
 texts.append('Repairs retained: first raw simulator SHA comparison included an unmodeled host issue clock (all other fields/lifecycle identical); corrected normalization excludes only that clock. Initial scorer pickle check used an environment without sklearn; frozen Phase 1 environment passed unchanged. Administrative timeout argument placement failed before subprocess start. First integration server reached readiness but absent payload manifest prevented any warmup/request; copied frozen manifest and fresh attempt2 passed. Patch context whitespace is preserved through narrowly scoped Git attributes; CSV generators useLF. Progress heartbeat block retention was repaired for subsequent runners; frozen run order and completed counts remain authoritative. Additional actual repairs, if any, are in attempt-ledger.jsonl and completion-audit.json.\n\n')
 texts.append('Confidence is high for exact conditional query/decision parity in deterministic validation and safe required live work. Timing confidence is descriptive: one VM, four already-exposed tapes, three repeats each, independent source previously evaluated,N2, and asynchronous readiness changes. Full oracle is historical context, not a new contemporary Phase 3 arm or an optimal upper bound. No fully causal incoming predictor, natural generation quality, longer contexts, tool execution or production deployment is established.\n\n')
 texts.append('## Required answers and next experiment\n\n')
 for i,answer in enumerate(decision['answers'],1):texts.append(f'{i}. {answer}\n\n')
 texts.append('Strongest next experiment: '+decision['next_experiment']+'\n\nNo Phase 4 or causal incoming project is started. Ordinary serving remains the real-use baseline. Source patches, tested reproducers, all observations/omissions, fixed identities and publication audit are retained; large binary recovery limitations remain explicit.\n\nPrimary conclusion: **'+decision['primary']+'**.\n')
 (C/'report.md').write_text(''.join(texts));print('REPORT WRITTEN',elapsed/60,flush=True)
