"""Freeze twelve independent whole-task episodes before labels/fitting."""
from pathlib import Path
import hashlib,json,sys,sysconfig,datetime
import lab
C=Path(__file__).resolve().parents[1];R=C.parents[1]
def save(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,indent=2)+'\n')
def main():
 assert not (C/'datasets/tasks.json').exists(),'No mutation of frozen tasks'
 std=Path(sysconfig.get_path('stdlib'))
 tasks=[]
 code=[('asyncio/queues.py','Design a bounded asynchronous log ingestion service around this queue implementation. Explain cancellation, backpressure, shutdown, retries, and ordering; provide a concrete Python implementation and adversarial tests.'),
 ('concurrent/futures/thread.py','Review this executor implementation for a service that submits dependent blocking jobs. Explain deadlocks, cancellation, shutdown and failure propagation; design an application wrapper with tests without modifying this library.'),
 ('logging/handlers.py','Design reliable rotating audit logs for a multiprocess local application based on this implementation. Compare queue-based logging and direct file writes; describe failure handling, ownership and executable test scenarios.'),
 ('zipfile/__init__.py','Implement a safe offline archive importer using this implementation as reference. Discuss path normalization, links, size limits, streaming, atomic publication and interrupted extraction. Include Python code and tests.')]
 for i,(file,task) in enumerate(code,1):
  p=std/file;text=p.read_text();excerpt=text[:26000]
  tasks.append({'id':f'code-{i}','family':'code','role':'development' if i<=2 else 'calibration' if i==3 else 'holdout','source':str(p),'source_sha256':hashlib.sha256(text.encode()).hexdigest(),'source_document':excerpt,'task':task,'context_profile':'32k','output':1024})
 math=[
 ('A backup service has n=5 independent drives, each exponential failure rate lambda=.02/day. It tolerates at most2 simultaneous failed drives; one repair worker repairs at rate mu=.5/day. Derive the continuous-time Markov chain, stationary distribution, probability of data-loss state, expected time to first data loss starting healthy, and sensitivity to doubling repair rate. Explain every boundary and distinguish first passage from stationary risk. Give a reproducible numerical algorithm and check limiting cases.'),
 ('A warehouse replenishes one item every seven days. Daily demand is independent Poisson with mean18, supplier lead time is three days, fixed order cost120 and unit holding cost.04/day. Derive a periodic-review base-stock policy at99% cycle-service probability, distinguish cycle service from fill rate, estimate shortage expectation without normal-tail shortcuts, and compare with a continuous-review policy. Show numerical calculations, exact sums and assumptions; discuss how correlated demand invalidates the result.'),
 ('A sensor reports y(t)=a exp(-bt)+c with Gaussian noise sigma=.03 at t=0,1,2,4,8. Observations are1.08,.86,.66,.45,.24. Derive nonlinear least-squares gradients and Hessian, perform an explicit damped Gauss-Newton calculation, give a convergent algorithm, estimate uncertainty and discuss identifiability/parameter correlation. Compare fitting log-transformed data with fitting original measurements, including the role of unknown c. Provide pseudocode and consistency checks.'),
 ('Two queues share a server of capacity12 jobs/s. StreamA arrival4/s earns value3/job, streamB arrival6/s earns1/job. Service times exponential; a completed job is useful only if sojourn is under.5s. Compare FCFS, nonpreemptive priority and a capacity partition. Derive what can be established analytically and formulate a simulation with reproducible confidence estimates for the rest. Include stability, tail probabilities, conservation checks and a clear distinction between exact formulas and approximations.')]
 for i,task in enumerate(math,1):tasks.append({'id':f'math-{i}','family':'math','role':'development' if i<=2 else 'calibration' if i==3 else 'holdout','source':'Locally authored fully specified independent applied problem; no external API','source_document':task,'source_sha256':hashlib.sha256(task.encode()).hexdigest(),'task':'Solve this complete applied problem with derivations, implementation detail and verification.','context_profile':'32k','output':1024})
 prose=[
 ('Museum exhibit brief','A municipal museum received360 oral-history interviews from1900–1970. Consent permits public excerpts for240, research-only use for85, and no further use for35. Fifteen interviews concern a flood; residents disagree on chronology. The exhibit lasts12weeks, has six panels and a listening station. Staff: curator.5FTE, archivist.2FTE, two volunteers. Budget18000. Accessibility requires transcripts, captions and plain-language summaries. No living person should be identified without recorded permission.','Write an exhibit plan and a structured catalog schema. Include visitor-facing prose, evidence uncertainty, permissions workflow, budget, staffing, milestones and examples of completed catalog records.'),
 ('Water outage incident packet','At07:10 a pump tripped. Pressure alarms appeared07:17. Operator restart07:22 failed; a bypass opened07:38 and restored part of town08:05. Full pressure returned10:40 after replacing a contactor. Residents reported brown water until14:00. Last inspection was24days earlier; logs show two unexplained trips. No contamination test result is yet available. Three schools opened late. Dispatch messages incorrectly stated a burst pipe.','Produce a factual public update, detailed internal postmortem and JSON action register. Separate facts, hypotheses and unknowns; preserve chronology and avoid unsupported assurances. Include accountable actions and verification criteria.'),
 ('Library digitization request','Library has12000 newspaper pages,900 photographs and300 handwritten letters. OCR sample error rates: newspapers4%, letters18%. Photos include unidentified people. Two scanners process90pages/hour and150photos/hour. Available operator time240hours. Metadata review averages2minutes/item; rights review required on20% of objects. Grant deadline10weeks, budget12000, user priority local newspapers. Originals cannot leave the building.','Develop a realistic prioritization and delivery plan, explain tradeoffs, calculate capacity, design a metadata template and write a grant-progress narrative. Include explicit uncertainties and a machine-readable staged backlog.'),
 ('Community garden agreement','Forty households share30plots; ten households are waitlisted. Irrigation costs900/year, tool insurance250/year, compost500/year. Plot fee currently35/year. Six volunteers maintain common paths. Some residents cannot perform physical work. Complaints concern shade, unattended produce and chemical sprays. Lease renews annually and bans permanent structures. The council asks for transparent allocation and accessible volunteering.','Draft an inclusive operating agreement, a balanced budget proposal, conflict-resolution process and structured registration form. Provide concrete clauses and worked examples, including accessibility alternatives and fair waitlist handling.')]
 for i,(title,doc,task) in enumerate(prose,1):tasks.append({'id':f'structured-{i}','family':'structured/prose','role':'holdout','source':'Locally authored distinct realistic source packet: '+title,'source_document':doc,'source_sha256':hashlib.sha256(doc.encode()).hexdigest(),'task':task,'context_profile':'32k','output':1024})
 # Same real service tokenizer as the frozen common wrapper.
 src=R/'src/control';sys.path[:0]=[str(src),str(src/'tools')]
 import strata_tokenizer as ST
 from serve.frontend import ChatTemplate
 from serve.server import Service
 cfg=json.loads((C/'configs/control-32k.json').read_text());voc=Path(cfg['tokenizer']);v=json.loads((voc/'vocab.json').read_text());tokens=[None]*len(v)
 for token,index in v.items():tokens[index]=token
 svc=Service.__new__(Service);svc.tok=ST.Tokenizer(tokens,(voc/'merges.txt').read_text().split('\n'),json.loads((voc/'token_type.json').read_text()));svc.template=ChatTemplate(voc/'chat_template.jinja');svc.effort_end=False
 manifest=json.loads((C/'inputs/manifest.json').read_text())
 for t in tasks:
  payload={'model':cfg['model_name'],'messages':[{'role':'system','content':'Work offline. No tools are available. Answer directly with complete, detailed reasoning and concrete examples. Do not emit tool calls.'},{'role':'user','content':'Source document:\n'+t['source_document']+'\n\nTask:\n'+t['task']}],'max_tokens':t['output'],'temperature':0,'stream':True,'chat_template_kwargs':{'enable_thinking':False}}
  ids=svc.encode_prompt(payload['messages'],None,{'enable_thinking':False});raw=json.dumps(ids,separators=(',',':')).encode();sha=hashlib.sha256(raw).hexdigest();ip=C/'inputs/token-ids'/f'{sha}.json';ip.write_bytes(raw);path=C/'inputs'/f'{t["id"]}.json';save(path,payload)
  manifest['payloads'][t['id']]={'path':str(path),'payload_sha256':lab.hashjson(payload),'messages_sha256':lab.hashjson(payload['messages']),'input_ids_sha256':sha,'token_ids_path':str(ip),'actual_input_tokens':len(ids),'output':t['output'],'task_id':t['id'],'split':t['role'],'source_sha256':t['source_sha256']}
 save(C/'inputs/manifest.json',manifest);save(C/'datasets/tasks.json',{'declared_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'episodes':tasks})
 save(C/'datasets/splits.json',{'development':[t['id'] for t in tasks if t['role']=='development'],'calibration':[t['id'] for t in tasks if t['role']=='calibration'],'holdout':[t['id'] for t in tasks if t['role']=='holdout'],'unit':'Whole independent source task; no neighboring slices/nonces across splits','entire_holdout_family':'structured/prose','no_future_labels_read_before_split':True,'censoring':'Last4 verifier windows excluded from negatives/fit; unused lifetime is right-censored'})
 print('FROZEN12TASKS',[(t['id'],t['role'],manifest['payloads'][t['id']]['actual_input_tokens']) for t in tasks],flush=True)
if __name__=='__main__':main()
