"""Reproducible final report; all numbers come from preserved raw analyses."""
from campaign import C,load,save
import statistics

def f(x,n=1):return '—' if x is None else f'{x:,.{n}f}'
def med(d,k):return d[k]['median'] if d.get(k) else None
def table(h,rows):return '| '+' | '.join(h)+' |\n|'+ '|'.join(['---']*len(h))+'|\n'+''.join('| '+' | '.join(map(str,r))+' |\n' for r in rows)
def main():
 s=load(C/'summary.json');assert s['live']['complete'];decision=load(C/'decision.json');s['recommendation']=decision['recommendation'];s['decision']=decision;save(C/'summary.json',s)
 cells=s['live']['cells'];pairs=s['live']['paired_ratios'];a=load(C/'phase-a/summary.json');h=load(C/'phase-b/holdout-decision.json');details=load(C/'analysis/heldout-transaction-details.json');diag=load(C/'analysis/diagnostic-ablations.json');ind=load(C/'analysis/independent-live.json') if (C/'analysis/independent-live.json').exists() else []
 out=['# Q4 Residency v3 — conditional admission before copy','',decision['conclusion'],'',f"Recommendation: **{decision['recommendation']}**. The unchanged Q4 100 µs production reference remains available, and normal user launchers were not changed.",'','## Protocol and provenance','',
 'The control is Strata 0.1.39, source `6f32ec070f23ced9f50e704d854d775da52591ab`, binary SHA256 `eca9d0d271340a114955d5af8038dbffa139ad096ef0d470bcfea9009d4f8d0d`. The conditional candidate has source `0266e540087acb98acd183546edeab3164aee8fd`, binary `dd52147462545bcfd5e30bd252a1ae83a92e890a5b03790720168c24b5772ffc`. It reuses early-v1 parent `78a6559ec8ef6cc0db57ecd0ff4091a945ec8a7f` in a separate local worktree/build.', '',
 'Both builds use CUDA/sm_89 Release and the same control build options. Actual ggml CPU translation-unit sources and compilation flags match; linked libraries match. This rules out a different CPU compiler path as an explanation for the live timing difference. [Build commands](git/builds/conditional-v1/commands.json), [CPU build audit](git/CPU-build-flags-audit.json), [patch](patches/conditional-v1.diff), [hardware](git/environment.json).', '',
 'The existing UD-Q4_K_XL revision is `38bb39ee97821de2c9009abb7e93950eec396e66`. Pack `/srv/ai/models/strata/packs/ud-q4_k_xl-v0132` is only the preserved model-pack name; no old runtime was selected. Native GGUF shards, profile and MTP were reused without downloads or weight changes. [Model identity](git/model.json).', '',
 'Frozen common settings: K=24, PCIe fraction=0.28, pool spin=100 µs, workers=15, MTP spec=4/min-p=0.5, INT8 KV, kv-resident=32768, prefill=auto, suffix lookup=0, prompt reuse=0, greedy, serial execution. Each primary attempt uses a fresh server, the same 4096-input/64-output warmup and one measured 4096-output request. There are exactly three valid requests per cell, 18 in total. Actual input IDs match in all nine pairs; actual warmup counts match.', '',
 'Physical startup expert capacities (GPU0/GPU1) are 6031/5510 at 32K, 5999/5477 at 128K and 5954/5432 at 256K, identical between arms. Conditional decode has two fewer active experts because of its existing spares. The total context limits are 32768/131072/262144. Actual inputs around 28.38K/126.72K/257.78K leave room for 4096 generated tokens and the engine reserve. The first 12 completed points were preserved when an order audit found that 256K would always start control first. At a request boundary, the driver was safely paused with its refuse-overwrite guard; no request was interrupted or repeated. Only the final six planned points were reordered, so every context includes both arm orders. [Original/corrected order](phase-c/order-repair.json), [plan](phase-c/matrix-plan.json), [raw IDs/configs](analysis/live-records.json).', '',
 'The scheduler still uses the existing two 3.072 MB spares, one per GPU, costing two active experts during decode. Physical capacity, same-device ownership and five target layers (9,16,29,36,42) are unchanged. Publication still requires completed copy and an actually safe victim. The gate runs before enqueue, source access and staging; rejected actions create no expert-copy traffic. No extra expert VRAM, remote execution or mathematical expert substitution was introduced.', '',
 'Start: 2026-10-06 01:08:59 UTC. Experiment cutoff: 08:28:59 UTC. Absolute deadline: 09:08:59 UTC. Work stopped earlier after the declared protocol reached a defensible conclusion. No broad policy search was reopened.', '', '## LIVE RESULTS','']
 rows=[]
 for d in cells:
  predictor=med(d,'feature_plus_gate_ms')
  rows.append([d['context'],d['variant'],f(med(d,'PP')),f(med(d,'TG')),f(med(d,'wall_s'),2),f(med(d,'local_vram_share_all_pct'),2),f(med(d,'cpu_fallback_entries'),0),f(med(d,'total_nonlocal_entries'),0),f(med(d,'issued'),0),f(med(d,'rejected_before_copy'),0),f(med(d,'copied_GB'),3),f(med(d,'unpublished_GB'),3),f(med(d,'published'),0),f(med(d,'victim_absent_entries'),0),f(predictor,3)])
 out += [table(['Context','Variant','PP','TG','Wall s','Local %','CPU entries','Nonlocal entries','Issued','Rejected before copy','Copied GB','Unpublished GB','Published useful','Victim absent*','Feature+gate ms'],rows),'All headline values are medians of three valid runs. Local percentage uses all routed entries; nonlocal=CPU+mapped, summed per run before taking the median. GB is decimal. Disabled/unavailable counters are “—”, not fabricated zeros. *Victim absence is observed demand, not proven additional damage against a counterfactual native schedule. Protected-victim rejection subtypes, separate candidate-selection time and predictor-only CPU percentage were not independently logged; they remain unavailable, not zero. Feature+gate excludes the inherited early-history scorer and GPU H4 path, whose cost is also paid in wall time.','']
 rows=[]
 for d in cells:
  rows.append([d['context'],d['variant'],f"{int(d['actual_input_tokens']['min'])}–{int(d['actual_input_tokens']['max'])}",'/'.join(f(d['PP'][k]) for k in ['min','median','max']),'/'.join(f(d['TG'][k]) for k in ['min','median','max']),f(med(d,'TTFT_s'),2),f(med(d,'mtp_acceptance_pct'),2)])
 out += [table(['Context','Variant','Actual input','PP min/median/max','TG min/median/max','TTFT median s','MTP accept %'],rows),'Every primary run generated 4096 recorded output IDs with reuse=0. TTFT is time to first visible content/reasoning token; wall excludes startup and warmup. No primary OOM, crash, early EOS or invalid request was discarded.', '',table(['Context','Paired median TG delta %','Paired median wall delta %','Paired nonlocal delta %','Same output IDs /3'],[[p['context'],f(100*(p['TG_ratio']['median']-1),2),f(100*(p['wall_ratio']['median']-1),2),f(100*(p['nonlocal_entries_ratio']['median']-1),2),f"{p['same_outputs']}/3"] for p in pairs]),'',
 'Outputs and MTP trajectories can diverge when expert execution moves between existing CPU/GPU floating-point paths. Consequently these are controlled-input application-latency measurements, not fixed-output-trajectory speedups. Exact first divergence, offered/accepted drafts, verify windows and warmup parity are preserved in [paired evidence](analysis/live-pairs.json). Historical v2 speed values are not current controlled timing arms.','']
 rows=[]
 for d in cells:
  hw=d['decode_hardware'];get=lambda k:hw[k]['median'] if hw.get(k) else None
  rows.append([d['context'],d['variant'],f(get('system_CPU_pct')),f(get('process_CPU_pct')),f(get('GPU0_util_pct')),f(get('GPU1_util_pct')),f(get('GPU0_power_W')),f(get('GPU1_power_W')),f(get('GPU0_PCIe_RX_MBps')),f(get('GPU1_PCIe_RX_MBps')),f(get('RSS_sum_GiB_peak'),2)])
 out += [table(['Context','Variant','VM CPU %','Process CPU %','GPU0 %','GPU1 %','Power0 W','Power1 W','RX0 MB/s','RX1 MB/s','Peak RSS GiB'],rows),
 'Telemetry is sampled at about 1 Hz without PSS polling. Process CPU uses 100%=one core; VM CPU is normalized to all vCPUs. Summed RSS may include shared pages. Sampled PCIe includes all subsystems, not just expert traffic or critical-path waits. Prefill/decode VRAM, RAM available, power and TX are retained in [records](analysis/live-records.json). Rounded unique CPU-job means are separate from exact branch-entry counts. [Reported timing/costs](analysis/reported-timing-costs.json) retain overlapping CPU completion, host and GPU timers without claiming an exact compute/spin decomposition.', '']

 out += [table(['Clean conditional context','Wrong median','Late min/median/max','Target-censored min/median/max'],[[d['context'],f(med(d,'prediction_wrong'),0),'/'.join(f(d['late'][k],0) for k in ['min','median','max']),'/'.join(f(d['right_censored'][k],0) for k in ['min','median','max'])] for d in cells if d['variant']=='conditional']), 'Clean timing misses increase at 256K (median 63), so publication readiness is not perfect. Wrong candidates still dominate unpublished actions. Exact per-run counts are preserved; separate column medians are not an additive per-request funnel. Instrumented diagnostic late counts below are a different measurement.','']
 out += ['**Attribution warning:** the apparent 32K ON gain is not established as a gate speedup. The candidate-OFF guard below already gains 13.63% TG with identical output/MTP/routing against the earlier control. Both build identity and noncontemporaneous environmental variation therefore remain timing confounds. At 128K the practical comparison is tied; at 256K there is no gain.','']
 guard_result=load(C/'analysis/off-speed-guard.json')
 out += ['## Candidate-OFF timing guard','',f"A single later-time 32K/4096 request using the new candidate binary with both mechanisms OFF has TG {guard_result['candidate_OFF_TG']:.1f}, versus {guard_result['control_reference_TG']:.1f} for the preserved primary control replicate 1. Exact full-length IDs/MTP/routing/capacity parity: {guard_result['PASS_parity']}. The ratio {guard_result['TG_ratio_vs_earlier_primary_rep1']:.4f} is diagnostic only: this is not a contemporaneous replicated timing A/B and cannot isolate code layout from environmental drift. No fourth production-control repetition was run. This guard also checks whether a later experimental build without its algorithm can already appear faster. [Declaration](phase-c/ablation-plan-v2.json), [result](analysis/off-speed-guard.json).",'']
 out += ['', '## ADMISSION FUNNEL','']
 rows=[]
 for name,d in diag.items():
  g=d['funnel'];rows.append([name,f(g['H4_or_reactive_eligible_candidates'],0),f(g['rejected_before_copy'],0),g['copy_issued'],g['copy_completed'],g['published'],g['used_at_target'],g['reused_in_later_window_contiguous'],f(g['staged_GB'],3),f(g['published_GB'],3),f(g['unpublished_GB'],3),g['victim_absent_contiguous'],g['prospective_victim_changed_at_target']])
 out += [table(['Diagnostic arm','Eligible','Rejected','Issued','Completed','Published','Target-used','Reused later','Staged GB','Published GB','Unpublished GB','Victim absent','Victim changed'],rows),
 'These traces use the same 32K input and 4096 output budget, with buffered diagnostic logging and canonical weight readbacks excluded from headline speed. Trajectories can differ, so cross-arm publication counts are not a fixed-trajectory recall estimate. Later-use attribution ends at the first observed native-cache touch or another early publication touching that expert; subsequent readmission is not credited as exclusive early residency benefit. Victim absence remains observational. H4 unfiltered reuses the Phase A trace rather than repeating it. OFF preserves control mathematics/capacity; reactive-only, H4 unfiltered and conditional flags are distinct. [Transaction traces and attribution](analysis/diagnostic-ablations.json).', '', '## FAILURE REASONS','',
 'The original 4996 historical wrong-or-superseded outcomes remain underidentified: 15.347712 GB, plus four separately known late copies (0.012288 GB). The new diagnostic matches clean-v2 early replicate 1, but not the old diagnostic trajectory. We do not transfer newly observed labels to those historical actions.', '',table(['New matched diagnostic reason','Count','GB','% issued'],[[r['reason'],r['count'],f(r['GB'],6),f(r['percent_issued'],3)] for r in a['explicit_target_outcome_categories']]),
 'Prediction-wrong dominates count and bytes. Once issued, the worker cannot be superseded by another proposal; duplicates/inflight actions are prevented before issue. Early-v1 reserves no specific victim at enqueue, so “victim became protected” is not a defined failed-copy reason. A safe actual victim is selected at the target and can differ from the prospective victim. No generation-mismatch branch exists. Nineteen near-end actions have censored future-reuse labels, separate from known target outcomes. [Full category/source audit](phase-a/report.md), [12 episode counts/bytes](analysis/episode-failure-reasons.json).', '', table(['Diagnostic arm','Observed outcome','Count','GB','% issued'],[[r['variant'],r['reason'],r['count'],f(r['GB'],6),f(r['percent_issued'],3)] for r in load(C/'analysis/diagnostic-failure-reasons.json')]), 'The reactive trace additionally exposes 70 candidates that became native-resident before publication and one pending-retired action with an unobserved target (right-censored). The conditional trace has 41 late copies under instrumentation; this is not a clean-runtime deadline-miss estimate. These cases describe their own trajectories, not the historical 4996 aggregate.', '', '## HELD-OUT RESULTS','',
 'Data comprise 12 independent tasks: four distinct code/module documents, four fully specified authored applied-math problems and four distinct authored structured/prose packets. Actual inputs range from 162 to 6991 tokens, with a 32768 maximum context; each generated 1024 tokens. The primary 28K/126K/257K inputs and 4096-output history therefore extrapolate the training conditions. Development has four tasks; calibration two; sealed holdout six, including the entire structured family. Neighboring document slices were not split across partitions. Exact task sources, input/output IDs, trace hashes and near-end censoring are in the [manifest](datasets/manifest.json) and [task splits](datasets/tasks.json).', '',
 'The mandatory rule baseline and logistic model use causal H4 confidence/rank/margin, completed usage history, candidate state and prospective victim features. Logistic L2=1 and Platt calibration were frozen at p≥0.12 before holdout. Only three coarse rule and three coarse linear operating points were evaluated. No nonlinear model was justified; no holdout refit, threshold adjustment or unrelated parameter tuning was performed. [Feature definitions and unavailable quantities](datasets/feature-definitions.md).', '',
 f"Publication precision is {100*details['precision']:.2f}%, count recall {100*details['publication_count_recall']:.2f}%, and PR average precision {h['classification']['PR_AUC_average_precision']:.4f}, versus {h['history_only_ablation']['PR_AUC_average_precision']:.4f} for history/state-only features on the same H4 candidate set. Confusion matrix: {details['confusion_matrix']}. {details['excluded_near_end_actions']} near-end actions were excluded from future-use labels, not treated as negatives.", '',
 f"Unpublished traffic falls from {h['selected']['baseline_unpublished_GB']:.6f} to {h['selected']['unpublished_GB']:.6f} GB (−{100*h['selected']['unpublished_reduction']:.2f}%). The gate retains {100*h['selected']['benefit_recall']:.2f}% of next-four-window demand benefit and {100*h['selected']['observed_use_recall']:.2f}% of observed later uses. It loses {details['lost_target_ready_publications']} of {details['baseline_target_ready_publications']} target-ready publications. Attributed nonlocal demand rises {h['selected']['original_nonlocal_entries']}→{h['selected']['nonlocal_entries_attributed']} (+{100*(h['selected']['nonlocal_ratio']-1):.2f}%). CPU entries rise {h['selected']['original_CPU_entries']}→{h['selected']['CPU_entries_attributed']}; mapped entries {h['selected']['original_mapped_entries']}→{h['selected']['mapped_entries_attributed']}. Retained victim-absent observations fall {h['selected']['baseline_victim_absent_entries']}→{h['selected']['victim_absent_entries_retained']}.", '',
 f"The pooled practical gate passes, but code holdout is weaker: only {100*h['family'][0]['observed_use_recall']:.2f}% later-use retention and +{100*(h['family'][0]['nonlocal_ratio']-1):.2f}% nonlocal demand. The original extra 2% per-family guard therefore failed. That false decision remains preserved. The user's numerical-aid judgment clause allowed experimental live testing of the SAME frozen p=0.12 candidate because the pooled gate passed; it did not justify retuning on holdout. [Strict result](phase-b/holdout-decision.json), [explicit decision](phase-b/live-gate.json).", '',
 f"Victim-damage prediction is weak: auxiliary R²={h['victim_hazard']['R2']:.4f}, damage average precision={h['victim_hazard']['PR_AUC_nonzero_damage']:.4f}. This head was not deployed. The actual safe victim can differ from the victim scored at origin. Rules either retain too much waste or lose useful admissions; the conservative linear point also loses too much benefit. Negative thresholds/models remain preserved.", '',
 'Offline transactions are fixed-native-schedule attribution, with same byte class/capacity and censoring at native touches. They are not a deployable oracle, an exact counterfactual adaptation simulation or a TG forecast. Measured Q4 staging/queue and H2D priors are 0.293449 ms and 0.25535 ms; a 0.25 ms/CPU-entry sensitivity is explicitly modeled, not an additive exposed-latency measurement. The hot ready-vector scalar costs 26.65 ns/action; full live history, features, selection and synchronization cost are reported separately. [Costs and curves](analysis/heldout-transaction-details.json), [calibration plot](analysis/plots/admission-holdout.png), [frozen traffic data](analysis/frozen-traffic-curve.csv).', '', '## INDEPENDENT APPLICATION VALIDATION','']

 selected=h['selected'];evaluations=[load(p)['selected'] for p in sorted((C/'phase-b/holdout').glob('*.json'))]
 baseline_issued=sum(details['confusion_matrix'].values());baseline_wrong=baseline_late=0
 for task in load(C/'datasets/splits.json')['holdout']:
  evaluation=load(C/'phase-b/holdout'/f'{task}.json')['selected'];events=load(C/'datasets/episodes'/task/'events-labeled.json')
  eligible=[e for e in events if e['window']<evaluation['evaluation_windows']]
  baseline_wrong+=sum(e['classification'] in ('prediction-wrong','became-resident-before-publication') for e in eligible)
  baseline_late+=sum('late' in e['classification'] for e in eligible)
 transaction_rows=[['H4 unfiltered',baseline_issued,f(baseline_issued*.003072,6),details['baseline_target_ready_publications'],f(selected['baseline_unpublished_GB'],6),baseline_wrong,baseline_late,selected['baseline_observed_uses'],selected['baseline_victim_absent_entries'],selected['original_nonlocal_entries'],selected['original_CPU_entries'],selected['original_mapped_entries']],['Frozen conditional',selected['issued_copies'],f(selected['staged_GB'],6),selected['target_ready_publications'],f(selected['unpublished_GB'],6),sum(e['wrong_or_superseded'] for e in evaluations),sum(e['late'] for e in evaluations),selected['useful_later_observed_uses_retained'],selected['victim_absent_entries_retained'],selected['nonlocal_entries_attributed'],selected['CPU_entries_attributed'],selected['mapped_entries_attributed']]]
 out += [table(['Held-out attribution','Issued','Staged GB','Target-ready','Unpublished GB','Wrong/resident','Late','Observed uses*','Victim absent*','Nonlocal','CPU','Mapped'],transaction_rows),f"The frozen gate rejects {details['rejected_before_copy']} evaluated actions before copy. {details['excluded_near_end_actions']} near-end actions are censored/excluded separately. Modeled net cost improves by {details['modeled_net_gain_vs_unfiltered_ms']:.3f} ms versus unfiltered, under the explicitly approximate/overlapping priors; this is not measured request latency. *Aggregate event observations are checked against contiguous attribution below. Scorer-only cost is 26.65 ns/ready-vector action; it excludes full runtime feature/selection and queue costs.",'']
 contiguous=load(C/'analysis/contiguous-holdout-audit.json')['aggregate']
 out += [f"Post-hoc attribution audit with the SAME frozen model and threshold retains {contiguous['kept_contiguous_local_entries']} of {contiguous['recorded_contiguous_local_entries']} observed contiguous local entries ({100*contiguous['contiguous_entry_recall']:.2f}%). Attribution stops at the first native or other early touch. This agrees numerically with the earlier aggregate event-use ratio in this heldout set, but does not prove exclusive avoided work against a counterfactual cache policy. Contiguous victim-absent observations fall {contiguous['victim_absent_contiguous']}→{contiguous['kept_victim_absent_contiguous']}. Next-four-window 'benefit' is future demand potential, not guaranteed resident or exclusive latency benefit. No fit, threshold or selection was changed by this reporting audit. [Strict contiguous audit](analysis/contiguous-holdout-audit.json).",'']
 if ind:
  for t in ind:out += [f"**{t['task']}**: median paired TG {100*(t['median_paired_TG_ratio']-1):+.2f}%, request wall {100*(t['median_paired_wall_ratio']-1):+.2f}%. Three fresh pairs; unchanged input IDs; maximum 1024 output; no rewritten tasks or favorable retries. Natural input lengths and termination are preserved. These short real tasks use a 128K-capacity server but are not 128K-input benchmarks.",'']
  application_rows=[]
  for t in ind:
   for cell in t['cells']:
    application_rows.append([t['task'],cell['variant'],int(cell['actual_input_tokens']['median']),f"{int(cell['actual_output_tokens']['min'])}–{int(cell['actual_output_tokens']['max'])}",f(cell['PP']['median']),f(cell['TG']['median']),f(cell['TTFT_s']['median'],2),f(cell['wall_s']['median'],2)])
  out += [table(['Task','Variant','Actual input','Actual output range','PP','TG','TTFT s','Wall s'],application_rows),'']
  out+=['Outputs, actual input/output counts, MTP, first divergence and raw request paths: [independent evidence](analysis/independent-live.json). These whole tasks were not fitted or calibrated; their earlier diagnostic routing episodes were part of sealed holdout, not new unseen sources. This limits the strength of a universal generalization claim. Within-policy control outputs, MTP and routing are identical across repetitions, yet structured-task TG ranges from 89.7 to 101.2. That timing spread is independent of admission changes; its physical cause is not established. [Stability evidence](analysis/independent-within-policy-stability.json).','']
 else:out+=['The predeclared ≥5% practical primary-wall trigger was not met; no extra application requests were launched merely to consume time. [Decision](phase-c/independent-decision.json).','']
 out += ['## CORRECTNESS AND NEGATIVE RESULTS','',
 'Ten real CUDA scheduler/byte tests pass: good/bad prediction, rejection before enqueue with no staging, duplicate, native-resident candidate, protected victim, late/delayed copy, pending cancellation and next request, repeated spare reuse, request-end restoration and shutdown with pending work. Diagnostic requests compare the first 16 copied experts against canonical RAM bytes. HTTP cancellation with an artificial 5 ms copy delay drained successfully, and the next 64-token request completed.', '',
 'The OFF build preserves exact output, MTP, routing and full capacity on two short tasks. ON produces no detected NaN and passes sampled byte checks; the code task first diverges at output token 33, while the math output is identical but MTP differs. This is correctness evidence against corruption, not proof of bitwise parity or a quality ranking. [Safety](tests/scheduler/result.json), [OFF/ON](phase-c/small-correctness.json), [cancellation](phase-c/cancellation.json).', '',
 'Native suite: 62 pass, two skip, four unchanged fixture/environment failures out of 68 tests. `ple_parity` requires a missing Q2_0 PLE shard; `expert_parity` and `pool_test` require missing `pack/full/experts.bin`; `platform_memory_test` cannot mlock under the current limit. These are not new correctness failures, and the suite is not all green. [Exact failure output](tests/native-failure-causes.json). Dependency/path/NumPy-serialization preflight failures were preserved and repaired before measurements. The intentional order-checkpoint driver exit was a protocol guard, not an engine crash; no measured run was repeated. No negative threshold, holdout failure or unfavorable performance point was erased.', '', '## Answers to the 20 research questions','']
 q=[
 ('What did wrong-or-superseded contain?','The historical aggregate is underidentified. The new clean-matched trace contains 4959 wrong predictions and 1043 target-ready publications; independent episodes also expose late copies.'),
 ('Which reason dominated by count?','Prediction-wrong.'),
 ('Which dominated by bytes?','Prediction-wrong; every staged action is 3.072 MB.'),
 ('How predictable were useful admissions?',f"Held-out AP {h['classification']['PR_AUC_average_precision']:.4f}, precision {100*details['precision']:.2f}%, recall {100*details['publication_count_recall']:.2f}% at the frozen threshold."),
 ('What did H4 add beyond history?','A modest AP gain on the same H4-selected candidate set. This feature ablation does not by itself establish a causal speedup versus a reactive scheduler.'),
 ('How predictable was victim damage?','Weakly; the auxiliary R² is negative and rare-damage AP low. The victim head was not deployed.'),
 ('How much wasted traffic was rejected?',f"Held-out unpublished bytes avoided: {h['selected']['baseline_unpublished_GB']-h['selected']['unpublished_GB']:.6f} GB. Live pre-enqueue rejects and copied bytes are in the main table/funnel."),
 ('How many useful admissions were lost?',f"{details['lost_target_ready_publications']} of {details['baseline_target_ready_publications']}; count recall 80.68%, weighted next-four benefit 85.38%. Code is weaker."),
 ('Did total nonlocal work change?','Offline attributed nonlocal entries rise 1.34%; live paired ratios vary by context and output trajectory. No universal miss-reduction claim.'),
 ('Did CPU fallback change?','Offline CPU entries rise 224423→227534; live exact CPU counts are in the table. CPU percentage is not a causal decomposition.'),
 ('Did copied GB change?','Yes, versus unfiltered early copies. The unchanged production control adds no early-copy traffic, so the candidate does not reduce added copies relative to OFF.'),
 ('What was predictor CPU cost?','Hot scalar 26.65 ns/action; full feature/gate and inherited-history timers are retained. Predictor-only CPU percentage is unavailable. Wall time pays all costs.'),
 ]
 for p in pairs:q.append((f"Did TG improve at {p['context']}?",f"Median paired TG {100*(p['TG_ratio']['median']-1):+.2f}%, wall {100*(p['wall_ratio']['median']-1):+.2f}%; three pairs, with output/MTP divergence documented."))
 q += [('Did request wall improve?','See the paired wall table; prefill dominates long-input requests and decode gains cannot be evaluated alone.'),('Did it generalize?','Independent task evidence is separated above. No universal claim follows from twelve diagnostic episodes or one favorable trajectory.'),('Did output/MTP diverge?','All paired input IDs match; output/MTP and warmup-output checks are retained. Live speed comparisons are application-level.'),('What is the remaining bottleneck?',decision['remaining_bottleneck']),('What is the single best next experiment?',decision['single_best_next_experiment'])]
 assert len(q)==20
 out += [f'{i}. **{question}** {answer}' for i,(question,answer) in enumerate(q,1)]
 out += ['', '## RUN COMMANDS','', 'Retained unchanged control, one server at a time:', '', '```bash',f'cd {C}/launchers/control','./start-32k.sh --host 0.0.0.0 --port 8080','./start-128k.sh --host 0.0.0.0 --port 8080','./start-256k.sh --host 0.0.0.0 --port 8080','./stop.sh','```', '', 'Separate safe experimental candidate, subject to the recommendation above:', '', '```bash',f'cd {C}/launchers/conditional','./start-32k.sh --host 0.0.0.0 --port 8080','./start-128k.sh --host 0.0.0.0 --port 8080','./start-256k.sh --host 0.0.0.0 --port 8080','./stop.sh','```','',
 'Launchers verify binary/source/model identity, print the complete config and refuse GPU/port conflicts. They never rebuild automatically. `reproduce.sh --profile 128k --port 18144` is enabled only after campaign completion and uses three fresh servers with identical warmup, not three requests on one adaptive cache. [Six actual launcher smokes](analysis/launcher-smokes.json). Normal user launchers remain unchanged.', '', '## Final audit and unfinished work','',
 'Prior v2 files remain unchanged; full model SHA256 values match preserved hashes. No owned Strata, training or profiling process remains; both GPU compute lists are empty. [Process/provenance audit](analysis/final-audit.json), [previous-campaign hashes](git/prior-v2-final-verification.json), [full model hashes](git/model-final-fullhash-verification.json). Research/source commits are local only, with no push or PR.', '',
 'Unfinished due to deadline: none in the bounded protocol. Exact exclusive critical-path cost, invisible native-cache interactions, unseen source generalization and future victim protection remain measured/model limitations, not invented zeros. No further residency implementation is started automatically.', '',decision['recommendation'],'']
 (C/'report.md').write_text('\n'.join(out));(C/'phase-c/report.md').write_text('# Phase C — controlled live validation\n\n'+decision['conclusion']+'\n\n[Full report](../report.md), [18 raw records and summaries](../summary.json), [paired trajectory evidence](../analysis/live-pairs.json), [independent applications](../analysis/independent-live.json).\n\n'+decision['recommendation']+'\n');print('REPORT_RENDERED',decision['recommendation'],flush=True)
if __name__=='__main__':main()
