#include "strata/kernels/verify_kernels.hpp"
#include "strata/kernels/native_moe.hpp"
#include <cuda_runtime.h>
#include <vector>
#include <iostream>
using namespace strata::kernels;
void ck(cudaError_t e){if(e!=cudaSuccess)throw std::runtime_error(cudaGetErrorString(e));}
template<class T>T* alloc(size_t n){T* p;ck(cudaMalloc(&p,n*sizeof(T)));return p;}
int main(){for(int d=0;d<2;++d){ck(cudaSetDevice(d));cudaStream_t stream;ck(cudaStreamCreateWithFlags(&stream,cudaStreamNonBlocking));uint32_t *h,*m;ck(cudaHostAlloc(&h,4,cudaHostAllocMapped));ck(cudaHostGetDevicePointer(&m,h,0));*h=1;auto* stats=alloc<unsigned long long>(2);auto* rows=alloc<unsigned long long>(4*10000);auto* count=alloc<unsigned long long>(1);auto* finished=alloc<unsigned int>(1);std::vector<float> parts(4*10*3072,.1f),weights(4*10,.1f),shared(4*3072,.1f);auto *dp=alloc<float>(parts.size()),*dw=alloc<float>(weights.size()),*ds=alloc<float>(shared.size()),*out=alloc<float>(shared.size());ck(cudaMemcpy(dp,parts.data(),parts.size()*4,cudaMemcpyHostToDevice));ck(cudaMemcpy(dw,weights.data(),weights.size()*4,cudaMemcpyHostToDevice));ck(cudaMemcpy(ds,shared.data(),shared.size()*4,cudaMemcpyHostToDevice));Q4KernelTrace trace{rows,count,finished,10000,1};
 for(int kind=0;kind<2;++kind)for(int detail=0;detail<2;++detail){cudaGraph_t graph;cudaGraphExec_t ex;ck(cudaMemset(stats,0,16));ck(cudaMemset(count,0,8));ck(cudaMemset(finished,0,4));ck(cudaStreamBeginCapture(stream,cudaStreamCaptureModeGlobal));for(int i=0;i<1000;++i){if(kind==0)wait_flag_ge_timed(m,1,stats,stream,detail?rows:nullptr,detail?count:nullptr,10000);else native_moe_combine_multi(dp,dw,ds,out,3072,10,4,stream,detail?trace:Q4KernelTrace{});}ck(cudaStreamEndCapture(stream,&graph));ck(cudaGraphInstantiate(&ex,graph,0));cudaEvent_t a,b;ck(cudaEventCreate(&a));ck(cudaEventCreate(&b));for(int repeat=0;repeat<3;++repeat){ck(cudaEventRecord(a,stream));ck(cudaGraphLaunch(ex,stream));ck(cudaEventRecord(b,stream));ck(cudaEventSynchronize(b));float ms;ck(cudaEventElapsedTime(&ms,a,b));std::cout<<"{\"device\":"<<d<<",\"kind\":\""<<(kind==0?"ready_wait":"combine_3072_T4")<<"\",\"detail\":"<<detail<<",\"repeat\":"<<repeat<<",\"calls\":1000,\"gpu_ms\":"<<ms<<"}"<<std::endl;}cudaEventDestroy(a);cudaEventDestroy(b);cudaGraphExecDestroy(ex);cudaGraphDestroy(graph);}
 for(void* p:{(void*)stats,(void*)rows,(void*)count,(void*)finished,(void*)dp,(void*)dw,(void*)ds,(void*)out})cudaFree(p);cudaFreeHost(h);cudaStreamDestroy(stream);}}
