"""Render traceable English report from raw-derived summary, never historical estimates."""
import json,statistics
from pathlib import Path
C=Path(__file__).resolve().parents[1]
def load(p):return json.loads(Path(p).read_text())
def fmt(x,n=2):return 'unknown' if x is None else f'{x:,.{n}f}'
def median(cell,k):x=cell['metrics'].get(k);return x['median'] if x else None
def medpair(cell,k):x=cell['paired'].get(k);return x['median'] if x else None
def table(headers,rows):return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(map(str,r))+' |' for r in rows])
def main():
 s=load(C/'summary.json');identity=load(C/'git/oracle-decomposition-v2-identity.json');overhead=load(C/'phase-a/ordinary-replay-guard-summary.json');off=load(C/'phase-b/offline-summary.json');decision=load(C/'analysis/final-decision.json')
 cells=sorted(s['cells'],key=lambda c:({'32k':0,'128k':1,'256k':2}[c['profile']],{'current':0,'FF':1,'64F':2,'F64':3,'6464':4,'F256':5}[c['arm']]))
 mainrows=[]
 for c in cells:
  tg=medpair(c,'TG_ratio_vs_current');mainrows.append([c['profile']+'/'+c['arm'],64 if c['arm']!='current' else 'n/a',c['I'] if c['arm']!='current' else 'n/a',c['V'] if c['arm']!='current' else 'n/a',str(c['attempts'])+'/'+str(c['valid']),fmt(median(c,'decode_s')),fmt(median(c,'replay_equivalent_tok_s')),fmt((tg-1)*100) if tg else 'undefined',fmt(medpair(c,'gain_retention')),fmt(median(c,'wall_s')),fmt(median(c,'copy_GB')),fmt(median(c,'CPU_entries'),0)+'/'+fmt(median(c,'mapped_entries'),0),fmt(median(c,'victim_absent_entries'),0),fmt(median(c,'late_target_nonlocal_entries'),0),fmt(median(c,'planner_ms')) if c['arm']!='current' else 'n/a'])
 text='# Q4 oracle decomposition: incoming demand versus victim lifetime\n\n'
 text+=decision['headline']+'\n\nThe unchanged Q4/K24/PCIe0.28/pool100us normal serving baseline remains real-use configuration. This study is clairvoyant fixed-work replay, not a deployable generation speed or quality claim.\n\n'
 unique={r['profile']:r for r in s['rows']}
 text+='## Preserved work profiles\n\n'+table(['Profile','Total context limit','Actual input','Recorded visible output','Verifier windows','Work SHA256'],[[p,{'32k':32768,'128k':131072,'256k':262144}[p],unique[p]['actual_input'],unique[p]['recorded_output'],unique[p]['work_manifest']['windows'],unique[p]['work_manifest']['work_sha256']] for p in ['32k','128k','256k']])+'\n\nThe same fixed tape is repeated three times per profile for timing repeatability. These are not three independent tasks. Required reserve remains inside each total-context limit.\n\n'
 text+='## Main measured results\n\n'+table(['Profile/tape','E','I','V','Attempts/valid','Replay decode s','Replay-equivalent tok/s','Paired TG change vs current %','Full-gain retention','Wall s','Copy GB','CPU/mapped entries','Victim-absent entries','Late target nonlocal demand','Online oracle planner ms'],mainrows)+'\n\n'
 text+='Medians use three valid attempts per point; all individual min/median/max and within-block ratios are in summary.json/CSV and analysis/paired-comparisons.json. Gain retention is (T_current-T_candidate)/(T_current-T_full), computed within block and not clamped. Negligible/nonpositive full savings are undefined. Copy GB includes native or oracle completed weight payload plus mandatory17,305,600-byte oracle restoration; metadata traffic is separate. Publication-before-target is not actual target-ready demand. Late target nonlocal demand requires observed CPU/mapped service at the intended target while the copy was unfinished. Victim absence is reconstructed for both authorities: native eviction starts at copy issue, oracle eviction at completed-copy publication; readmission ends absence. Native planning time is not represented by the tiny oracle-hook timer in REPLAY_CURRENT, so that table entry is n/a. Planner includes overlapping host query/publication activity and cannot be added to GPU/CPU timers.\n\n'
 ranges=[]
 for c in cells:
  for k in ['decode_s','replay_equivalent_tok_s','PP','wall_s','TTFT_s','attestation_ms','CPU_steal']:
   r=c['metrics'][k];ranges.append([c['profile'],c['arm'],k,fmt(r['min']),fmt(r['median']),fmt(r['max'])])
 text+='## Full timing range\n\n'+table(['Profile','Arm','Metric','Min','Median','Max'],ranges)+'\n\n'
 text+='## Information boundaries and structural finding\n\nE64 is the unchanged incoming issue frontier. At logical event n, bounded information ends at n+H inclusive. First incoming relevant demand is eligible only within min(E,I); incoming count/value reads at most I, resident next-use/count/initial donor/publication selection at most V. FULL stops at finite tape end. One unit is the whole main verify routed-layer T-by-10 invocation;48/window. Role/window/position/speculative lanes/batch shapes remain in the tape identity. No batch is serialized into individual expert demand.\n\n'
 text+='Typed IncomingFutureView/VictimFutureView and query counters enforce separate views. Unknown beyond H is distinct from finite tape end and uses fixed causal heat-log fallback. No full-future cached scores or tie-breaking cross roles. Candidate enumeration reads only min(E,I). Common P=current-window safety protection reveals up to47 forward layer invocations and is explicitly retained in every arm. Therefore H4/H16 offline curves are conditional on P; H64 contains all forward P information. Full-index preparation in RAM is evaluator setup, not permission for policy leakage.\n\n'
 text+='The default deadline scheduler **selects its first feasible candidate**. Its calculated incoming/victim reuse utility never ranks two feasible choices. I>=64 therefore leaves deterministic actions unchanged when V is fixed; it can reduce online count-loop work and change physical asynchronous progress. A null I64 effect does not show that incoming retention information is unnecessary in a future utility-ranking scheduler. The unchanged internal reuse-count cap is n+768 even for FULL; FULL victim next-use can inspect the remaining finite tape.\n\n'
 text+='Source tests:1,205 old/new full decision checks, exact deterministic offline F/F=64/F, bounded suffix tests for incoming and victim decisions separately, role reclassification, inclusive endpoint/H+1 unknown, causal fallback branch activation. Full mode/default ordinary/current behavior is preserved; the common v2 diff changes only oracle information headers. See phase-a/.\n\n'
 text+='## Sparse offline curves — not measured model throughput\n\n'+table(['I','V','Nonlocal entries','CPU/mapped','Copies GB','Published','Target-ready entries','Victim absent'],[[r['I'],r['V'],r['cpu']+r['mapped'],str(r['cpu'])+'/'+str(r['mapped']),fmt(r['copied_bytes']/1e9),r['published'],r['target_ready_demand'],r['victim_absent_observations']] for r in off])+'\n\n'
 text+='One deterministic execution per unchanged point; no25-cell grid. All3classes/48layers/same5chargedspares, E64, one modeled contended link/device. Inherited staging25GB/s, H2D13.2GB/s, publication45us, main0.57ms/invocation and MTP2.5ms/window are model assumptions. No exposed CPU/mapped latency model or simulated TG is fabricated. I4/I16 also shorten eligibility/lead.\n\n'
 text+='One causal unknown repair H+640/(1+heat), derived from native .7/4-window EMA, was tested without tuning. It makes different choices in a targeted binding state but produces exactly unchanged32K modeled exchange traffic/demand. This negative is preserved; no live repair or additional fallback search. Churn cannot be blamed only on an infinity sentinel: bounded unknowns use causal heat, though that fallback remains an imperfect eviction-risk model.\n\n'
 text+='## Matched interaction and gain retention\n\n'+table(['32K block','Descriptive interaction ms'],[[x['attempt'],fmt(x['decode_interaction_ms'])] for x in s['interaction']])+'\n\n'
 text+='Interaction = T_64_64-T_64_F-T_F_64+T_F_F. This is descriptive, sensitive to changed placement trajectories/VM variability. Do not add the two losses as a linear universal law. Mechanically, I64 has no deterministic selection effect at fixed V; any small measured interaction needs timing/planner interpretation.\n\n'
 text+='## Context/task transfer\n\n'+decision['transfer_interpretation']+'\n\n'
 ind=C/'phase-c/independent-summary.json'
 if ind.exists():
  ii=load(ind);text+=ii['description']+'\n\n'+table(['Arm','Attempts','Replay-equivalent tok/s median','Wall median s','Paired TG change vs current %','Full-gain retention'],[[c['arm'],c['attempts'],fmt(c['TG_median']),fmt(c['wall_median']),fmt(c['paired_TG_pct']),fmt(c['gain_retention'])] for c in ii['cells']])+'\n\n'
 text+='## Fidelity, physical costs and uncertainty\n\nAll headline requests must pass tape fingerprint, token/MTP branch/commit/rollback/catchup schedule, routed IDs/float32 coefficients/QSA/shape/dependency counts and strict initial meaningful-state sidecar. Real dense/attention/KV/PLE/router/expert/head work computes before tape overrides. Forced output/MTP parity is not correctness proof. Selected real activation samples remain numerical diagnostics; CPU/GPU quantization/summation differ. Publication/copy ownership safety is checked separately.\n\n'
 text+='All48main layers/all3physical classes share K24 and originalVRAM envelope. Five existing slots become charged spares inside decode; no expert prepopulate/setup benefit or extra GPU memory. MTP residency stays unchanged. Current retains native adaptation; oracle is sole exchange authority in its scope, preserving causal heat. Real pinned staging/H2D completion precedes legal publication; late demand still computes using CPU/mapped fallback. Native decode time ends before final commit wait, drain/restoration and buffered trace flush, exactly as the retained v3 serving timer does. All request-comparable wall includes these costs; cleanup timers are shown separately and never added as unrelated medians. A decode-only gain is not automatically a cleanup-inclusive request gain. Future index and tape loaded in RAM outside decode, online queries/copies charged.\n\n'
 text+=f'Short ordinary/replay guard: median paired decode overhead {fmt((overhead["median_paired_decode_ratio"]-1)*100)}%, wall overhead {fmt((overhead["median_paired_wall_ratio"]-1)*100)}%; individual decode ratios .889..1.162. No performance-equivalence claim or unvalidated natural speed extrapolation. Common initial-state attestation remains pre-decode setup inside requestwall.\n\n'
 hw=[]
 for c in cells:hw.append([c['profile'],c['arm'],fmt(median(c,'VM_CPU')),fmt(median(c,'process_CPU')),fmt(median(c,'CPU_steal')),fmt(median(c,'GPU0')),fmt(median(c,'GPU1')),fmt(median(c,'local_pct')),fmt(median(c,'future_index_setup_ms')),fmt(median(c,'tape_lookup_ms'))])
 text+=table(['Profile','Arm','VM CPU%','Process CPU% (1core=100)','CPU steal%','GPU0%','GPU1%','Local all-demand%','Future index setup ms','Tape lookup ms'],hw)+'\n\n'
 memory=load(C/'analysis/future-index-memory.json')
 text+='Tape and future-index payload accounting (outside timed decode):\n\n'+table(['Profile','Tape MB','Future event/count pair payload MB'],[[m['profile'],fmt(m['tape_bytes']/1e6),fmt(m['future_index_pair_payload_bytes']/1e6)] for m in memory])+'\n\nFuture-index payload counts two int32 fields per distinct expert/invocation. This is a lower-bound logical payload, not measured allocator RSS: vector slack, allocator metadata and tape temporary copies are not included. Full index is constructed for both replay policies; its role-specific access is still bounded.\n\n'
 text+='CPU steal/load/affinity, GPU clocks/power/temperature/link state, RAM/VRAM and attestation costs remain in raw telemetry and analysis/*-system.json. No clocks/global settings changed, no parallel heavy work during speed runs.3 repetitions do not remove VM confounding. Physical streamed KV refill ordering may differ despite identical logical QSA and initial maps; primary native counters retained, secondary DMA detail unavailable.1Hz aggregate PCIe samples cannot establish event-specific bandwidth or saturation. CPU/mapped counts are distinct and all-routed denominators match. Overlapping timers are not summed.\n\n'
 text+='The native child main-thread affinity is not the affinity of every thread. A read-only snapshot retained56 thread masks:15 one-core masks for the CPU pool on cores1 through15,13 on core0, and28 permitting cores0 through15. Source creates oracle workers before the later main-session pin. Generic thread names do not identify every role; no oracle-worker/core attribution is invented and no affinity was changed.\n\n'
 text+='## Admission lifetime, tail sensitivity and smallest sufficient budget\n\n'+decision['mechanism_interpretation']+'\n\n'+decision['sufficient_budget']+'\n\n'
 funnel=load(C/'analysis/admission-funnel.json')
 text+=table(['Profile','Arm','Issued','Published','Repeat admissions','Published before target','Actual target hit entries','Reused admissions','Unused GB','Evicted without observed use','Unused end-censored'],[[r['profile'],r['arm'],fmt(r['issued'],0),fmt(r['published'],0),fmt(r['repeat_admissions_beyond_first'],0),fmt(r['published_before_target'],0),fmt(r['actual_target_admission_hits'],0),fmt(r['reused_distinct_invocations'],0),fmt(r['unused_GB'],3),fmt(r['evicted_without_observed_use'],0),fmt(r['unused_censored_at_end'],0)] for r in funnel['rows']])+'\n\n'+funnel['caveat']+' Candidate enumeration/rejection counts are unavailable, not zero. Native current has no oracle target/reuse intent; those specific metrics are unknown.\n\n'
 text+='Middle50% of verifier windows (floor(W/4) through floor(3W/4), exclusive) was declared before timing; per-row interior windows/time/logical committed advances and paired ratios retained in summary.json. No favorable interval selection or cleanup exclusion from total wall. No guard tail; full oracle has finite4096-end privilege. Resident lifetimes at end are censored, not deployment never-used labels. Victim-absent entries are observed demand while displaced, not exclusive causal latency penalties. Actual hit at target and published-before-target counts are separate.\n\n'
 text+='## Next predictor/scheduler target\n\n'+decision['next_target']+'\n\nSee analysis/predictor-specification.md for candidate population, causal features, risk/lifetime target, horizon units, cost weighting and uncertainty behavior. No predictor was trained. Do not infer that exact distant next-use is the only deployable target.\n\n'
 text+='## Repairs and negative results\n\nBootstrap tracked .venv symlink and ELF/log directory-name collision were repaired without model/runtime changes. A copied development-manifest output field inherited64 from warmup although the immutable request always specified256; metadata was corrected with no inference retry. A missing copied FNV helper caused post-request audit failure; valid inference was re-audited without a retry. Source information-v1 repairs the old incoming endpoint convention and finite-end state; v2 adds one opt-in causal unknown repair. Main heat-log policy and all physical worker/math paths unchanged. Losing sparse horizons/repair and slow observations remain retained. Any additional failures are listed in ledger.jsonl and final audit, never discarded post hoc. No new trace capture, helper/pool/K/PCIe/MTP/quantization tuning.\n\n'
 text+='## Reproduce and real use\n\nNormal Q4 serving remains **../q4-live-oracle-20261006T040656Z/launchers/control/**. No new normal launcher was created or existing one altered. Replay wrappers under launchers/replay/ are explicitly experimental; e.g. `./launchers/replay/64F-128k.sh --check` verifies identity/config/model/tape only; without `--check` creates a new finite owned manual reproduction namespace. Other retained budgets current/FF/64F/F64/6464/F256 and profiles32k/128k/256k are documented in launchers/README.md. Actual measured coverage is the table, not every possible wrapper combination. Source/binary hashes are checked; no automatic builds or hidden expert preloads.\n\n'
 text+=f'Common source **{identity["source_sha"]}**, binary **{identity["binary_sha256"]}**, original serving source/binary identities in git/prior-identities.json. Model revision38bb39ee97821de2c9009abb7e93950eec396e66, pack/shard/MTP/profile provenance and fresh aux hashes in git/model-now-verified.json. Previous campaign data/models remain immutable. All raw data/scripts/patches/manifests retained; local commits only, no push orPR. Deadline start09:57UTC, cutoff15:12UTC, absolute15:57UTC2026-10-06. Final process/GPU cleanup and reproducibility evidence in analysis/final-audit.json.\n\n'
 text+=decision['conclusion']+'\n';(C/'report.md').write_text(text)
if __name__=='__main__':main()
