#!/usr/bin/env python3
"""Export a previously checked clone witness's exact feasible selected links.

This is artifact reconstruction, not a second coefficient/frame verification.
The baseline and changed compiled hashes must match the immutable certificate.
Descriptions are regenerated by the frozen rank schedule and checked by hash.
"""
from __future__ import annotations
import argparse
from hashlib import sha256
import json
from pathlib import Path
import time

import finite_clone_recovered_witness as witness
from finite_clone_batch import BatchCloneView, build
from fast_frame_envelope import labels
import frame_reuse


def digest(value):
    return sha256(json.dumps(value,sort_keys=True,separators=(',',':')).encode()).hexdigest()


def tuples(value):
    return tuple(tuples(x) for x in value) if isinstance(value,list) else value


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--reference',required=True);ap.add_argument('--baseline',type=Path,required=True)
    ap.add_argument('--certificate',type=Path,required=True);ap.add_argument('--output',type=Path,required=True)
    args=ap.parse_args();assert not args.output.exists();witness.install_reference(args.reference)
    at=time.monotonic();certificate=json.loads(args.certificate.read_text());row=certificate['rows'][0]
    baseline=json.loads(args.baseline.read_text())
    assert sha256(args.baseline.read_bytes()).hexdigest()==certificate['candidate_input_sha256']
    assert sha256(Path(witness.__file__).read_bytes()).hexdigest()==certificate['source_sha256']
    for name,value in certificate['dependency_sha256'].items():
        assert sha256(Path(witness.__file__).with_name(name).read_bytes()).hexdigest()==value
    original=build(row['h'],row['base'],row['positions']);frames,_=labels(original,True)
    old_plan=frame_reuse.optimize_chains(original,frames,'rank')
    old_code=frame_reuse.compile_reuse(original,frames,old_plan)
    assert witness.compiled_hash(old_code)==baseline['checked']['compiled_sha256']
    jobs=[dict(job,selected=frozenset(tuples(use) for use in job['selected'])) for job in row['chosen']]
    view=BatchCloneView(original,jobs);new_frames=witness.mapped_frames(original,frames,view)
    plan=witness.recovered_plan(original,old_plan,view,new_frames,jobs)
    code=frame_reuse.compile_reuse(view,new_frames,plan)
    assert witness.compiled_hash(code)==row['duplicated']['checked']['compiled_sha256']
    selected_links=sorted([first,second] for first,second in plan[2].items())
    identity=dict(parent_candidate_id=baseline['candidate_id'],parent_input_sha256=certificate['candidate_input_sha256'],
        clone_edits_sha256=digest(row['chosen']),selected_links_sha256=digest(selected_links),
        compiler_witness_source_sha256=certificate['source_sha256'],
        changed_logical_sha256=row['duplicated']['logical']['circuit_sha256'],
        compiled_sha256=witness.compiled_hash(code),roles=code['roles'])
    value=dict(status='Terminal exact artifact reconstruction PASS',candidate_id=digest(identity),identity=identity,
        source_sha256=sha256(Path(__file__).read_bytes()).hexdigest(),
        certificate_sha256=sha256(args.certificate.read_bytes()).hexdigest(),
        baseline_sha256=sha256(args.baseline.read_bytes()).hexdigest(),
        exact_selected_links=selected_links,description_count=len(plan[1]),descriptions_sha256=digest(plan[1]),
        selected_link_count=len(selected_links),clone_count=len(jobs),
        schedule=plan[4],elapsed_seconds=time.monotonic()-at,
        recovery='Rebuild baseline with its frozen constructor/labels/optimizer; apply certificate rows[0].chosen through BatchCloneView; generate descriptions(rank, node ID); replace flow with exact_selected_links. Independently check all links and compile/check the changed witness.')
    args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text(json.dumps(value,sort_keys=True,separators=(',',':'))+'\n')
    print(json.dumps(dict(candidate_id=value['candidate_id'],roles=code['roles'],links=len(selected_links),
        bytes=args.output.stat().st_size,seconds=value['elapsed_seconds'])),flush=True)


if __name__=='__main__':main()
