// Capacity and modeled transfer simulations, never inference throughput.
#include "strata/research/q4_oracle.hpp"
#include <iostream>
#include <iomanip>
using namespace strata::research;
static void require(bool ok,const char* why){Q4Tape::require(ok,why);}
static std::vector<uint64_t> blob_sizes(){std::vector<uint64_t>b(48,3072000);b[2]=3993600;for(int l:{4,30,46,47})b[l]=3584000;return b;}
static std::vector<int32_t> initial=q4_tape.initial_res;
static std::vector<float> initial_heat=q4_tape.initial_heat;
int main(int argc,char**argv){require(argc>=2,"offline mode missing");std::string mode=argv[1];std::vector<int32_t> r=initial;std::vector<float> heat=initial_heat;auto bytes=blob_sizes();q4_oracle.blobs=bytes;uint64_t local=0,cpu=0,mapped=0,copybytes=0,proms=0,victims=0;int W=(int)q4_tape.windows.size();std::vector<int> slot_class[2];for(int d=0;d<2;++d){int mx=-1;for(int l=d*24;l<(d+1)*24;++l)for(int e=0;e<512;++e)mx=std::max(mx,r[l*512+e]);slot_class[d].assign(mx+1,-1);for(int l=d*24;l<(d+1)*24;++l)for(int e=0;e<512;++e)if(r[l*512+e]>=0)slot_class[d][r[l*512+e]]=q4_oracle.cls(l);}
 q4_oracle.configured=true;q4_oracle.runtime(r.data(),heat.data(),bytes,{nullptr,nullptr},[](int,int){return (const uint8_t*)1;},[](int,int){return (void*)1;});q4_oracle.events.reserve(W*240);q4_tape.active=true;
 auto demand=[&](int wi,int l){auto& w=q4_tape.windows[wi];int kinds[512];std::fill(kinds,kinds+512,-2);std::vector<int> misses;for(int j=0;j<w.T*10;++j){int e=w.routes.ids[l][j];if(kinds[e]!=-2)continue;kinds[e]=r[l*512+e]>=0?0:-1;if(kinds[e]<0)misses.push_back(e);}int m=(int(misses.size())*72)>>8;for(int i=int(misses.size())-m;i<int(misses.size());++i)kinds[misses[i]]=1;for(int j=0;j<w.T*10;++j){int e=w.routes.ids[l][j];if(kinds[e]==0)++local;else if(kinds[e]==1)++mapped;else ++cpu;heat[l*512+e]+=1.f;}if(q4_oracle.causal_policy)q4_oracle.scorer.observe(l,w.routes.ids[l],w.T*10,wi*48+l);};
 if(mode=="current"){
  struct Swap{float gain;int l,in,out;};
  for(int wi=0;wi<W;++wi){for(int l=0;l<48;++l)demand(wi,l);if((q4_tape.header.initial_rounds+wi+1)%4)continue;std::vector<Swap> swaps;for(int l=0;l<48;++l){std::vector<std::pair<float,int>>cand,vict;for(int e=0;e<512;++e)if(r[l*512+e]>=0)vict.emplace_back(heat[l*512+e],e);else if(heat[l*512+e]>=2)cand.emplace_back(heat[l*512+e],e);std::sort(cand.begin(),cand.end(),[](auto&a,auto&b){return a.first>b.first;});size_t n=std::min(cand.size(),vict.size());std::partial_sort(vict.begin(),vict.begin()+n,vict.end(),[](auto&a,auto&b){return a.first<b.first;});for(size_t j=0;j<n;++j){if(cand[j].first<vict[j].first+1.5f)break;swaps.push_back({cand[j].first-vict[j].first,l,cand[j].second,vict[j].second});}}std::sort(swaps.begin(),swaps.end(),[](auto&a,auto&b){return a.gain>b.gain;});if(swaps.size()>96)swaps.resize(96);for(auto&s:swaps){r[s.l*512+s.in]=r[s.l*512+s.out];r[s.l*512+s.out]=-1;copybytes+=bytes[s.l];++proms;}for(float&v:heat)v*=.7f;}
 }else if(mode=="capacity"){
  q4_oracle.horizon=0;for(int wi=0;wi<W;++wi){q4_tape.current=q4_tape.windows[wi];for(int l=0;l<48;++l){int seen[512]={};for(int j=0;j<q4_tape.current.T*10;++j){int e=q4_tape.current.routes.ids[l][j];if(seen[e]++||r[l*512+e]>=0)continue;int v=q4_oracle.victim(l,e,wi*48+l);if(v<0)continue;r[l*512+e]=r[l*512+v];r[l*512+v]=-1;++proms;copybytes+=bytes[l];}demand(wi,l);}}
 }else if(mode=="transfer"){
  std::vector<int> latest_victim(48*512,-1),latest_incoming(48*512,-1);uint64_t target_ready=0,late_useful=0;int horizon=argc>2?std::atoi(argv[2]):0;q4_oracle.horizon=horizon;q4_oracle.strategy=argc>3?std::atoi(argv[3]):0;q4_oracle.active=true;q4_oracle.incoming_event.assign(48*512,-1);
  // Identical charged physical spare accounting; conservative same-class and current-window protection.
  q4_tape.current=q4_tape.windows[0];for(int d=0;d<2;++d)for(int c=0;c<3;++c){if(d==1&&c==2)continue;int pick=-1;double best=-1e100;for(int l=d*24;l<(d+1)*24;++l)if(q4_oracle.cls(l)==c)for(int e=0;e<512;++e){if(r[l*512+e]<0||q4_oracle.protected_now(l,e))continue;double s=q4_oracle.victim_value(l,e,0);if(s>best){best=s;pick=l*512+e;}}require(pick>=0,"spare");auto&w=q4_oracle.workers[d][c];w.dev=d;w.cls=c;q4_oracle.spare[d][c]=r[pick];r[pick]=-1;}
  // One physically modeled copy queue/device (class streams share the link). Times are assumptions,
  // not recorded wall-time triggers and not claimed model TG. Real live policy uses logical events.
  double now=0,link[2]={},ready[2][3]={};double event_ms=.57;
  for(int ev=0;ev<W*48;++ev){int wi=ev/48,l=ev%48;q4_tape.current=q4_tape.windows[wi];q4_tape.index=wi;q4_oracle.current=ev;q4_oracle.advance_lifetimes(ev);
   for(auto&a:q4_oracle.workers)for(auto&w:a)if(w.dev>=0){if(w.state.load()==1&&ready[w.dev][w.cls]<=now){auto&e=q4_oracle.events[w.index];int v=q4_oracle.victim(w.layer,w.expert,ev);e.copy_end=(uint64_t)(now*1e6)+1;if(q4_oracle.transaction_control&&q4_oracle.causal_policy&&(ev>e.target+48||q4_oracle.protected_count(w.dev,w.cls)>=q4_oracle.protection_cap)){e.status=8;++q4_oracle.late_abort;w.state.store(0);continue;}if(r[w.layer*512+w.expert]>=0){e.status=2;w.state.store(0);continue;}if(v>=0&&(!q4_oracle.causal_policy||q4_oracle.scorer.accept(w.layer,v,ev,std::max(ev,e.target),q4_oracle.causal_policy,heat.data(),q4_oracle.victim_threshold))){int old=r[w.layer*512+v];require(slot_class[w.dev][old]==w.cls&&slot_class[w.dev][q4_oracle.spare[w.dev][w.cls]]==w.cls,"physical slot class violated");r[w.layer*512+v]=-1;r[w.layer*512+w.expert]=q4_oracle.spare[w.dev][w.cls];++q4_oracle.ownership_generation[w.layer];q4_oracle.spare[w.dev][w.cls]=old;e.victim=v;e.publish_ns=(uint64_t)(now*1e6)+1;e.published_at=ev;e.status=ev<=e.target?1:3;q4_oracle.note_publication(w.index,w.layer,w.expert,v,ev);q4_oracle.incoming_event[w.layer*512+w.expert]=w.index;latest_victim[w.layer*512+v]=w.index;latest_incoming[w.layer*512+w.expert]=w.index;w.state.store(0);now+=.045;}else if(q4_oracle.causal_policy){e.status=5;w.state.store(0);}}}
   for(auto&a:q4_oracle.workers)for(auto&w:a)if(w.dev>=0){int before=w.state.load();q4_oracle.plan(w);if(before==0&&w.state.load()==1){auto&e=q4_oracle.events[w.index];e.stage_begin=(uint64_t)(now*1e6)+1;e.stage_end=e.stage_begin+1;double staging=e.bytes/25e6,copy=e.bytes/13.2e6;ready[w.dev][w.cls]=std::max(now+staging,link[w.dev])+copy;link[w.dev]=ready[w.dev][w.cls];copybytes+=e.bytes;++proms;}}
   demand(wi,l);
   for(int j=0;j<q4_tape.current.T*10;++j){int e=q4_tape.current.routes.ids[l][j];victims+=r[l*512+e]<0&&latest_victim[l*512+e]>=0;int k=latest_incoming[l*512+e];if(k>=0&&r[l*512+e]>=0){++q4_oracle.events[k].uses;target_ready+=q4_oracle.events[k].target==ev;late_useful+=q4_oracle.events[k].published_at>q4_oracle.events[k].target;}}
   int32_t service_slots[40];for(int j=0;j<q4_tape.current.T*10;++j)service_slots[j]=r[l*512+q4_tape.current.routes.ids[l][j]];q4_oracle.note_service(l,q4_tape.current.routes.ids[l],service_slots,q4_tape.current.T*10,ev);
   now+=event_ms;if(l==47){now+=2.5;if((q4_tape.header.initial_rounds+wi+1)%4==0)for(float&v:heat)v*=.7f;}
  }
  // Drain is charged as completed ordinary payload; never publish after observation end.
  for(auto& a:q4_oracle.workers)for(auto& w:a)if(w.dev>=0&&w.state.load()==1){auto& e=q4_oracle.events[w.index];e.copy_end=(uint64_t)(std::max(now,ready[w.dev][w.cls])*1e6)+1;e.status=4;w.state.store(0);}
  uint64_t outcome_bytes[4]={},outcome_n[4]={},early_bytes=0,distinct_uses=0,recurring=0;uint64_t decision_hash=1469598103934665603ull;
  for(size_t i=0;i<q4_oracle.events.size();++i){auto& e=q4_oracle.events[i];auto& a=q4_oracle.lifetimes[i];int category=!e.publish_ns?0:e.uses?1:a.evicted_at>=0?2:3;outcome_bytes[category]+=e.bytes;++outcome_n[category];early_bytes+=category==2&&a.evicted_at<e.target?e.bytes:0;distinct_uses+=a.distinct_uses;recurring+=a.distinct_uses>=2;for(uint64_t v:{uint64_t(e.layer),uint64_t(e.incoming),uint64_t(e.victim+1),uint64_t(e.published_at+1)}){decision_hash^=v;decision_hash*=1099511628211ull;}}
  const char* prefix=std::getenv("STRATA_Q4_SIM_LOG");if(prefix){auto write=[&](const char* name,auto& values){FILE* f=std::fopen((std::string(prefix)+name).c_str(),"wbx");require(f,"sim artifact exists");Q4Tape::io(f,values.data(),values.size(),true);std::fclose(f);};write("-admissions.bin",q4_oracle.events);write("-lifecycle.bin",q4_oracle.lifetimes);}
  uint64_t pub=0,late=0,pbytes=0,repeated=0,unused_bytes=0;for(auto&e:q4_oracle.events){repeated+=e.uses>1;unused_bytes+=e.uses==0?e.bytes:0;}for(auto&e:q4_oracle.events)if(e.publish_ns){++pub;pbytes+=e.bytes;late+=e.status==3;}
  std::cout<<"{\"mode\":\"transfer\",\"I\":"<<q4_oracle.incoming_horizon<<",\"V\":"<<q4_oracle.victim_horizon<<",\"E\":64,\"protection\":\"full_current_window\",\"target_ready_demand\":"<<target_ready<<",\"late_useful_demand\":"<<late_useful<<",\"reused_admissions_entry_based\":"<<repeated<<",\"unused_bytes\":"<<unused_bytes<<",\"horizon\":"<<horizon<<",\"strategy\":"<<q4_oracle.strategy<<",\"issued\":"<<proms<<",\"copied_bytes\":"<<copybytes<<",\"published\":"<<pub<<",\"published_bytes\":"<<pbytes<<",\"late_publications\":"<<late<<",\"local\":"<<local<<",\"cpu\":"<<cpu<<",\"mapped\":"<<mapped<<",\"victim_absent_observations\":"<<victims<<",\"scorer_feature_ms\":"<<q4_oracle.scorer.feature_ns/1e6<<",\"scorer_model_ms\":"<<q4_oracle.scorer.score_ns/1e6<<",\"scorer_selection_ms\":"<<q4_oracle.scorer.selection_ns/1e6<<",\"scores\":"<<q4_oracle.scorer.scores<<",\"cache_hits\":"<<q4_oracle.scorer.cache_hits<<",\"rejections\":"<<q4_oracle.scorer.rejections<<",\"invalid_predictions\":"<<q4_oracle.scorer.invalid<<",\"host_model_bytes\":"<<q4_oracle.scorer.memory_bytes()<<",\"completed_unpublished_bytes\":"<<outcome_bytes[0]<<",\"published_used_bytes\":"<<outcome_bytes[1]<<",\"evicted_without_use_bytes\":"<<outcome_bytes[2]<<",\"no_use_resident_end_bytes\":"<<outcome_bytes[3]<<",\"evicted_before_first_target_bytes\":"<<early_bytes<<",\"distinct_uses\":"<<distinct_uses<<",\"recurring_admissions\":"<<recurring<<",\"decision_hash\":"<<decision_hash<<",\"protection_veto\":"<<q4_oracle.protection_veto<<",\"capacity_veto\":"<<q4_oracle.capacity_veto<<",\"cost_veto\":"<<q4_oracle.cost_veto<<",\"victim_cost_veto\":"<<q4_oracle.victim_cost_veto<<",\"risk_veto\":"<<q4_oracle.risk_veto<<",\"lease_expired\":"<<q4_oracle.expiry_count<<",\"lease_released\":"<<q4_oracle.release_count<<",\"max_protected\":"<<q4_oracle.max_protected<<",\"modeled_event_ms\":"<<event_ms<<",\"assumed_staging_GB_s\":25,\"assumed_H2D_GB_s\":13.2,\"measured_model_TG\":null}"<<std::endl;
  std::cout<<"{\"candidate_hash\":\""<<std::hex<<q4_oracle.decision_hash<<std::dec<<"\",\"candidate_records\":"<<q4_oracle.decision_records<<",\"lookups\":"<<q4_oracle.memo_lookups<<",\"hits\":"<<q4_oracle.memo_hits<<",\"misses\":"<<q4_oracle.memo_misses<<",\"lower\":"<<q4_oracle.memo_lower<<",\"upper\":"<<q4_oracle.memo_upper<<",\"rewind\":"<<q4_oracle.memo_rewind<<",\"maintenance_ms\":"<<q4_oracle.memo_time_ns/1e6<<"}"<<std::endl;
  for(auto&a:q4_oracle.workers)for(auto&w:a)w.dev=-1;return 0;
 }else require(false,"offline mode unknown");
 std::cout<<"{\"mode\":\""<<mode<<"\",\"local\":"<<local<<",\"cpu\":"<<cpu<<",\"mapped\":"<<mapped<<",\"promotions\":"<<proms<<",\"copy_bytes\":"<<copybytes<<",\"scorer_feature_ms\":"<<q4_oracle.scorer.feature_ns/1e6<<",\"scorer_model_ms\":"<<q4_oracle.scorer.score_ns/1e6<<",\"scorer_selection_ms\":"<<q4_oracle.scorer.selection_ns/1e6<<",\"scores\":"<<q4_oracle.scorer.scores<<",\"cache_hits\":"<<q4_oracle.scorer.cache_hits<<",\"rejections\":"<<q4_oracle.scorer.rejections<<",\"invalid_predictions\":"<<q4_oracle.scorer.invalid<<",\"host_model_bytes\":"<<q4_oracle.scorer.memory_bytes()<<",\"measured_model_TG\":null}"<<std::endl;
}
